# Generated by Django 5.2.1 on 2025-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='storage_limit_mb',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userstorage',
            name='max_storage',
            field=models.BigIntegerField(default=104857600),
        ),
    ]
