# Generated by Django 5.2.1 on 2025-07-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Abonnement', 'verbose_name_plural': 'Abonnements'},
        ),
        migrations.AlterModelOptions(
            name='userstorage',
            options={'verbose_name': 'Benutzer-Speicher', 'verbose_name_plural': 'Benutzer-Speicher'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='original_file',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='converted_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
