# Generated by Django 5.2.1 on 2025-07-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_subscription_options_alter_userstorage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Abonnement', 'verbose_name_plural': 'Abonnements'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='storage_limit',
        ),
        migrations.AddField(
            model_name='subscription',
            name='storage_limit_mb',
            field=models.IntegerField(default=50),
        ),
    ]
