# Generated by Django 5.2.1 on 2025-12-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_subscription_storage_limit_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='social_platforms_posted',
            field=models.TextField(blank=True, help_text='Komma-getrennte Liste der Plattformen'),
        ),
        migrations.AddField(
            model_name='video',
            name='social_post_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='social_post_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='social_post_hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='social_post_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='social_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='social_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
