# Generated by Django 5.2.1 on 2025-07-22 23:05

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_subscription_options_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.thumbnail_upload_path),
        ),
    ]
