# Generated by Django 5.2.1 on 2025-12-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_add_social_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='social_posted_urls',
            field=models.JSONField(blank=True, default=dict, help_text='URLs der geposteten Videos pro Plattform'),
        ),
    ]
