# Generated by Django 5.2.1 on 2025-12-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_add_social_posted_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='social_request_id',
            field=models.CharField(blank=True, help_text='Request-ID für Status-Abfrage bei Background-Uploads', max_length=100),
        ),
    ]
