# Generated by Django 5.2.1 on 2025-07-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_add_grace_period_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='archive_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Niedrig'), (2, 'Normal'), (3, 'Hoch'), (4, 'Kritisch')], default=2),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('archived', 'Archiviert'), ('deleted', 'Gelöscht')], default='active', max_length=20),
        ),
    ]
