# Generated by Django 5.2.1 on 2026-01-01 21:54

import django.db.models.deletion
import uuid
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_add_social_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_size', models.BigIntegerField(default=0)),
                ('uploaded_size', models.BigIntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('chunks_received', models.IntegerField(default=0)),
                ('chunk_size', models.IntegerField(default=52428800)),
                ('status', models.CharField(choices=[('uploading', 'Wird hochgeladen'), ('complete', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('expired', 'Abgelaufen')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunked_upload', to='videos.video')),
            ],
            options={
                'verbose_name': 'Chunked Upload',
                'verbose_name_plural': 'Chunked Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('chunk_size', models.IntegerField(default=0)),
                ('chunk_file', models.FileField(upload_to=videos.models.chunked_upload_path)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('chunked_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='videos.chunkedupload')),
            ],
            options={
                'verbose_name': 'Upload Chunk',
                'verbose_name_plural': 'Upload Chunks',
                'ordering': ['chunk_number'],
                'unique_together': {('chunked_upload', 'chunk_number')},
            },
        ),
    ]
