# Generated by Django 5.2.1 on 2026-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_chunkedupload_uploadchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorage',
            name='manual_storage_override',
            field=models.BooleanField(default=False),
        ),
    ]
