# Generated by Django 5.2.1 on 2025-07-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('storage', 'Storage Plan'), ('premium', 'Premium Features'), ('enterprise', 'Enterprise'), ('founder_access', 'Founder Early Access')], max_length=20),
        ),
    ]
