# Generated by Django 5.2.1 on 2025-11-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotogravurImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='fotogravur/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('shopify_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shopify_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_settings', models.JSONField(blank=True, default=dict)),
                ('custom_text', models.TextField(blank=True)),
                ('font_family', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Größe in Bytes', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotogravur_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fotogravur Bild',
                'verbose_name_plural': 'Fotogravur Bilder',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shopify_upl_created_7ad1b8_idx'), models.Index(fields=['shopify_order_id'], name='shopify_upl_shopify_93c615_idx')],
            },
        ),
    ]
