# Generated by Django 5.2.1 on 2026-02-03 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(default='bi-chat-dots', help_text='Bootstrap Icon Klasse (z.B. bi-chat-dots)', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#667eea', help_text='Hex-Farbcode (z.B. #667eea)', max_length=7, verbose_name='Farbe')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('topics_count', models.IntegerField(default=0, verbose_name='Anzahl Themen')),
                ('posts_count', models.IntegerField(default=0, verbose_name='Anzahl Beitraege')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('usage_count', models.IntegerField(default=0, verbose_name='Verwendungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content', models.TextField(max_length=10000, verbose_name='Inhalt')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('closed', 'Geschlossen'), ('pinned', 'Angepinnt'), ('archived', 'Archiviert')], default='open', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('replies_count', models.IntegerField(default=0, verbose_name='Antworten')),
                ('views_count', models.IntegerField(default=0, verbose_name='Aufrufe')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, verbose_name='Letzte Aktivitaet')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loomtalk_topics', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='loomtalk.category', verbose_name='Kategorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='topics', to='loomtalk.tag')),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': 'Themen',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=5000, verbose_name='Inhalt')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Bearbeitet')),
                ('is_solution', models.BooleanField(default=False, verbose_name='Als Loesung markiert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loomtalk_replies', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='loomtalk.reply', verbose_name='Eltern-Antwort')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='loomtalk.topic', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('notified_via_chat', models.BooleanField(default=False, verbose_name='Chat-Benachrichtigt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loomtalk_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Erwaehnte Person')),
                ('mentioning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loomtalk_mentions_made', to=settings.AUTH_USER_MODEL, verbose_name='Erwaehnende Person')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='loomtalk.reply')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='loomtalk.topic')),
            ],
            options={
                'verbose_name': 'Erwaehnung',
                'verbose_name_plural': 'Erwaehnungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='loomtalk.reply')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='loomtalk.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loomtalk_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stimme',
                'verbose_name_plural': 'Stimmen',
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-created_at'], name='loomtalk_to_created_b5abe0_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category', '-last_activity_at'], name='loomtalk_to_categor_470c49_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-score'], name='loomtalk_to_score_903ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status', 'is_active'], name='loomtalk_to_status_596a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['topic', 'created_at'], name='loomtalk_re_topic_i_6474f6_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['parent'], name='loomtalk_re_parent__9c918e_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['author', '-created_at'], name='loomtalk_re_author__7d4421_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['mentioned_user', 'is_read', '-created_at'], name='loomtalk_me_mention_e24daa_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('user', 'topic'), name='unique_user_topic_vote'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', False)), fields=('user', 'reply'), name='unique_user_reply_vote'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('topic__isnull', False), ('reply__isnull', False), _connector='OR'), name='vote_must_have_target'),
        ),
    ]
