# Generated by Django 5.2.1 on 2025-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptpro', '0002_prompt_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optionaler Link, der mit diesem Prompt verknüpft ist', verbose_name='Link'),
        ),
    ]
