# Generated by Django 5.2.1 on 2025-08-25 10:37

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True)),
                ('zoho_account_id', models.CharField(blank=True, max_length=50, verbose_name='Zoho Account ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'ordering': ['-is_default', 'email_address'],
            },
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=998)),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('participants', models.JSONField(default=list)),
                ('message_count', models.IntegerField(default=0)),
                ('unread_count', models.IntegerField(default=0)),
                ('first_message_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='mail_app.emailaccount')),
            ],
            options={
                'verbose_name': 'Email Thread',
                'verbose_name_plural': 'Email Threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('folder_type', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash'), ('spam', 'Spam'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('zoho_folder_id', models.CharField(blank=True, max_length=255)),
                ('unread_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='mail_app.emailaccount')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['account', 'folder_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('background', 'Background')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('emails_fetched', models.IntegerField(default=0)),
                ('emails_created', models.IntegerField(default=0)),
                ('emails_updated', models.IntegerField(default=0)),
                ('folders_synced', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sync_duration', models.DurationField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='mail_app.emailaccount')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('sender_name', models.CharField(blank=True, help_text='Display name of the sender', max_length=255)),
                ('subject_prefix', models.CharField(help_text='Common subject prefix for this ticket', max_length=200)),
                ('normalized_subject', models.CharField(blank=True, help_text='Normalized subject for matching', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('grouping_mode', models.CharField(choices=[('subject', 'By Subject'), ('thread', 'By Thread'), ('sender', 'By Sender'), ('none', 'No Grouping')], default='subject', help_text='How emails are grouped in this ticket', max_length=20)),
                ('email_count', models.PositiveIntegerField(default=0, help_text='Number of emails in this ticket')),
                ('first_email_at', models.DateTimeField(help_text='Timestamp of the first email')),
                ('last_email_at', models.DateTimeField(help_text='Timestamp of the most recent email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='mail_app.emailaccount')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-last_email_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_message_id', models.CharField(max_length=255, unique=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('zoho_thread_id', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(default=list)),
                ('bcc_emails', models.JSONField(default=list)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('draft', 'Draft')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False, help_text='Email is marked as open/requires action')),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_app.emailaccount')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_app.emailthread')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_app.folder')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='mail_app.ticket')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('zoho_attachment_id', models.CharField(blank=True, max_length=255)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('is_cached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_app.email')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'db_table': 'mail_app_attachment',
                'ordering': ['filename'],
                'indexes': [models.Index(fields=['email'], name='mail_app_at_email_i_a17225_idx'), models.Index(fields=['zoho_attachment_id'], name='mail_app_at_zoho_at_9f2186_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(default=list)),
                ('bcc_emails', models.JSONField(default=list)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_forward', models.BooleanField(default=False)),
                ('is_auto_saved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='mail_app.emailaccount')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_app.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['account', 'user', '-updated_at'], name='mail_app_em_account_292121_idx'), models.Index(fields=['in_reply_to'], name='mail_app_em_in_repl_39bd66_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['account', '-last_message_at'], name='mail_app_em_account_bca675_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['thread_id'], name='mail_app_em_thread__078fa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('account', 'zoho_folder_id')},
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['account', '-started_at'], name='mail_app_sy_account_474d57_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='mail_app_sy_status_3a63c7_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_type'], name='mail_app_sy_sync_ty_eb6fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['account', 'status', '-last_email_at'], name='mail_app_ti_account_283c23_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sender_email'], name='mail_app_ti_sender__bdd25b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['normalized_subject'], name='mail_app_ti_normali_b4d4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['grouping_mode'], name='mail_app_ti_groupin_903fae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('account', 'sender_email', 'normalized_subject', 'grouping_mode')},
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['account', 'folder', '-sent_at'], name='mail_app_em_account_94ac1a_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['zoho_message_id'], name='mail_app_em_zoho_me_6f39e3_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_read', 'is_starred'], name='mail_app_em_is_read_0ea6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['zoho_thread_id'], name='mail_app_em_zoho_th_5dacb0_idx'),
        ),
    ]
