# Generated by Django 5.2.1 on 2025-07-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=998)),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('participants', models.JSONField(default=list)),
                ('message_count', models.IntegerField(default=0)),
                ('unread_count', models.IntegerField(default=0)),
                ('first_message_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Thread',
                'verbose_name_plural': 'Email Threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='email',
            name='mail_app_em_thread__cebd21_idx',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='thread_id',
            new_name='zoho_thread_id',
        ),
        migrations.AddField(
            model_name='emailthread',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='mail_app.emailaccount'),
        ),
        migrations.AddField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_app.emailthread'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['zoho_thread_id'], name='mail_app_em_zoho_th_5dacb0_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['account', '-last_message_at'], name='mail_app_em_account_bca675_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['thread_id'], name='mail_app_em_thread__078fa7_idx'),
        ),
    ]
