# Generated by Django 5.2.1 on 2025-07-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_emailthread_and_more'),
    ]

    operations = [
    ]
