# Generated by Django 5.2.1 on 2025-07-24 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0003_merge_20250724_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Email is marked as open/requires action'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('sender_name', models.CharField(blank=True, help_text='Display name of the sender', max_length=255)),
                ('subject_prefix', models.CharField(help_text='Common subject prefix for this ticket', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('closed', 'Geschlossen')], default='open', max_length=20)),
                ('email_count', models.PositiveIntegerField(default=0, help_text='Number of emails in this ticket')),
                ('first_email_at', models.DateTimeField(help_text='Timestamp of the first email')),
                ('last_email_at', models.DateTimeField(help_text='Timestamp of the most recent email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='mail_app.emailaccount')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-last_email_at'],
            },
        ),
        migrations.AddField(
            model_name='email',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='mail_app.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['account', 'status', '-last_email_at'], name='mail_app_ti_account_283c23_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sender_email'], name='mail_app_ti_sender__bdd25b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('account', 'sender_email')},
        ),
    ]
