# Generated by Django 5.2.1 on 2025-07-29 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0005_alter_ticket_unique_together_ticket_grouping_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('zoho_attachment_id', models.CharField(blank=True, max_length=255)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('is_cached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'db_table': 'mail_app_attachment',
                'ordering': ['filename'],
            },
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='errors_count',
        ),
        migrations.AddField(
            model_name='synclog',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='folders_synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('background', 'Background')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='grouping_mode',
            field=models.CharField(choices=[('subject', 'By Subject'), ('thread', 'By Thread'), ('sender', 'By Sender'), ('none', 'No Grouping')], default='subject', help_text='How emails are grouped in this ticket', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['account', 'user', '-updated_at'], name='mail_app_em_account_292121_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['in_reply_to'], name='mail_app_em_in_repl_39bd66_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['account', '-started_at'], name='mail_app_sy_account_474d57_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='mail_app_sy_status_3a63c7_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_type'], name='mail_app_sy_sync_ty_eb6fdf_idx'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_app.email'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['email'], name='mail_app_at_email_i_a17225_idx'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['zoho_attachment_id'], name='mail_app_at_zoho_at_9f2186_idx'),
        ),
    ]
