# Generated by Django 5.2.1 on 2025-07-12 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Eingeladen'), ('joined', 'Beigetreten'), ('left', 'Verlassen'), ('declined', 'Abgelehnt')], default='invited', max_length=10, verbose_name='Status')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Beigetreten um')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Verlassen um')),
                ('agora_uid', models.IntegerField(blank=True, null=True, verbose_name='Agora User ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Anruf-Teilnehmer',
                'verbose_name_plural': 'Anruf-Teilnehmer',
            },
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100, unique=True, verbose_name='Kanal-Name')),
                ('call_type', models.CharField(choices=[('video', 'Video-Anruf'), ('audio', 'Audio-Anruf')], default='video', max_length=10, verbose_name='Anruf-Typ')),
                ('status', models.CharField(choices=[('waiting', 'Wartend'), ('active', 'Aktiv'), ('ended', 'Beendet'), ('missed', 'Verpasst')], default='waiting', max_length=10, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet um')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet um')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('agora_token', models.TextField(blank=True, verbose_name='Agora Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token läuft ab')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_calls', to=settings.AUTH_USER_MODEL, verbose_name='Anrufer')),
                ('participants', models.ManyToManyField(through='organization.CallParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Video-Anruf',
                'verbose_name_plural': 'Video-Anrufe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.videocall', verbose_name='Anruf'),
        ),
        migrations.AlterUniqueTogether(
            name='callparticipant',
            unique_together={('call', 'user')},
        ),
    ]
