# Generated by Django 5.2.1 on 2025-09-18 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAudioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200, verbose_name='Channel Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_session', to='organization.ideaboard', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Board Audio-Session',
                'verbose_name_plural': 'Board Audio-Sessions',
            },
        ),
        migrations.CreateModel(
            name='BoardAudioParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Beigetreten um')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Verlassen um')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Stumm geschaltet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='organization.boardaudiosession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Board Audio-Teilnehmer',
                'verbose_name_plural': 'Board Audio-Teilnehmer',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
