# Generated by Django 5.2.1 on 2025-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_boardaudiosession_boardaudioparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaboard',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Gemeinsame Notizen'),
        ),
        migrations.AlterField(
            model_name='boardelement',
            name='element_type',
            field=models.CharField(choices=[('line', 'Linie'), ('arrow', 'Pfeil'), ('rectangle', 'Rechteck'), ('circle', 'Kreis'), ('triangle', 'Dreieck'), ('text', 'Text'), ('image', 'Bild'), ('freehand', 'Freihand'), ('brush', 'Pinsel')], max_length=20, verbose_name='Element-Typ'),
        ),
    ]
