# Generated by Django 5.2.1 on 2025-07-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_callparticipant_videocall_callparticipant_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardelement',
            name='rotation',
            field=models.FloatField(default=0.0, verbose_name='Rotation (Grad)'),
        ),
        migrations.AlterField(
            model_name='boardelement',
            name='element_type',
            field=models.CharField(choices=[('line', 'Linie'), ('arrow', 'Pfeil'), ('rectangle', 'Rechteck'), ('circle', 'Kreis'), ('triangle', 'Dreieck'), ('text', 'Text'), ('image', 'Bild'), ('freehand', 'Freihand')], max_length=20, verbose_name='Element-Typ'),
        ),
    ]
