# Generated by Django 5.2.1 on 2025-07-16 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_boardelement_rotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocall',
            options={'ordering': ['-started_at'], 'verbose_name': 'Video-Anruf', 'verbose_name_plural': 'Video-Anrufe'},
        ),
        migrations.RemoveField(
            model_name='callparticipant',
            name='agora_uid',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='agora_token',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='token_expires_at',
        ),
        migrations.AddField(
            model_name='videocall',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verbunden um'),
        ),
        migrations.AddField(
            model_name='videocall',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Dauer'),
        ),
        migrations.AlterField(
            model_name='callparticipant',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participants', to='organization.videocall', verbose_name='Anruf'),
        ),
        migrations.AlterField(
            model_name='callparticipant',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left'), ('rejected', 'Rejected')], default='invited', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='callparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_call_participations', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='call_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='video', max_length=10, verbose_name='Anruf-Typ'),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_org_calls', to=settings.AUTH_USER_MODEL, verbose_name='Anrufer'),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Gestartet um'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videocall',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('ended', 'Ended'), ('missed', 'Missed'), ('rejected', 'Rejected')], default='initiated', max_length=20, verbose_name='Status'),
        ),
    ]
