# Generated by Django 5.2.1 on 2025-09-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_ideaboard_notes_alter_boardelement_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardelement',
            name='element_type',
            field=models.CharField(choices=[('line', 'Linie'), ('arrow', 'Pfeil'), ('rectangle', 'Rechteck'), ('circle', 'Kreis'), ('triangle', 'Dreieck'), ('text', 'Text'), ('emoji', 'Emoji'), ('image', 'Bild'), ('freehand', 'Freihand'), ('brush', 'Pinsel')], max_length=20, verbose_name='Element-Typ'),
        ),
    ]
