# Generated by Django 5.2.1 on 2025-09-25 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_boardelement_element_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMirrorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200, verbose_name='Channel Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_session', to='organization.ideaboard', verbose_name='Board')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_mirror_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
            ],
            options={
                'verbose_name': 'Board-Mirror-Session',
                'verbose_name_plural': 'Board-Mirror-Sessions',
            },
        ),
    ]
