# Generated by Django 5.2.1 on 2025-10-04 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('videos', 'Videos'), ('fileshare', 'FileShare'), ('streamrec', 'StreamRec'), ('shopify', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('other', 'Andere')], db_index=True, max_length=50, verbose_name='App')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('delete', 'Löschen'), ('archive', 'Archivieren'), ('restore', 'Wiederherstellen')], db_index=True, max_length=20, verbose_name='Aktion')),
                ('size_bytes', models.BigIntegerField(verbose_name='Größe (Bytes)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Zusätzliche Informationen (z.B. Dateiname, Typ, etc.)', verbose_name='Metadaten')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Storage-Log',
                'verbose_name_plural': 'Storage-Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'app_name', '-created_at'], name='core_storag_user_id_7dac9a_idx'), models.Index(fields=['user', 'action', '-created_at'], name='core_storag_user_id_2f06b7_idx'), models.Index(fields=['-created_at'], name='core_storag_created_e4e847_idx')],
            },
        ),
    ]
