# Generated by Django 5.2.1 on 2025-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelog',
            name='app_name',
            field=models.CharField(choices=[('videos', 'Videos'), ('fileshare', 'FileShare'), ('streamrec', 'StreamRec'), ('shopify', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('organization', 'Organization'), ('chat', 'Chat'), ('other', 'Andere')], db_index=True, max_length=50, verbose_name='App'),
        ),
    ]
