# Generated by Django 5.2.1 on 2026-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_storagelog_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelog',
            name='app_name',
            field=models.CharField(choices=[('videos', 'Videos'), ('fileshare', 'FileShare'), ('streamrec', 'StreamRec'), ('shopify', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('organization', 'Organization'), ('chat', 'Chat'), ('android_apk_manager', 'Android APK Manager'), ('learnloom', 'LearnLoom'), ('other', 'Andere')], db_index=True, max_length=50, verbose_name='App'),
        ),
    ]
