# Generated by Django 5.2.1 on 2025-12-19 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VSkriptProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('keyword', models.CharField(max_length=200, verbose_name='Keyword/Thema')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (optional)')),
                ('script_type', models.CharField(choices=[('fun_facts', 'Witzige Fakten'), ('interesting_facts', 'Interessante Fakten'), ('how_to', 'Schritt-für-Schritt Anleitung'), ('tips', 'Tipps & Tricks'), ('story', 'Spannende Geschichte'), ('true_false', 'Wahr/Falsch Spiel'), ('qa', 'Frage & Antwort'), ('riddle', 'Rätsel'), ('expectation_reality', 'Erwartung vs. Realität'), ('myth_busting', 'Mythen aufdecken'), ('comparison', 'Vergleich A vs B'), ('top_list', 'Top 5/10 Liste'), ('behind_scenes', 'Hinter den Kulissen'), ('challenge', 'Challenge-Format'), ('controversial', 'Kontroverse Meinung')], default='interesting_facts', max_length=50, verbose_name='Skript-Art')),
                ('tone', models.CharField(choices=[('professional', 'Professionell & seriös'), ('casual', 'Locker & entspannt'), ('humorous', 'Humorvoll & witzig'), ('inspiring', 'Inspirierend & motivierend'), ('neutral', 'Sachlich & informativ'), ('motivating', 'Motivierend & aufbauend'), ('provocative', 'Provokant & herausfordernd'), ('emotional', 'Emotional & berührend'), ('dramatic', 'Dramatisch & spannungsgeladen')], default='casual', max_length=50, verbose_name='Ton')),
                ('target_audience', models.CharField(choices=[('beginner', 'Anfänger'), ('intermediate', 'Fortgeschrittene'), ('expert', 'Experten'), ('general', 'Allgemein'), ('young', 'Kinder/Jugendliche')], default='general', max_length=50, verbose_name='Zielgruppe')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram Reels'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook')], default='youtube', max_length=50, verbose_name='Plattform')),
                ('duration', models.FloatField(default=1.0, verbose_name='Dauer (Minuten)')),
                ('script', models.TextField(blank=True, verbose_name='Skript')),
                ('word_count', models.IntegerField(default=0, verbose_name='Wortanzahl')),
                ('estimated_duration', models.FloatField(default=0, verbose_name='Geschätzte Dauer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vskript_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VSkript Projekt',
                'verbose_name_plural': 'VSkript Projekte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VSkriptGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='KI-Provider')),
                ('model', models.CharField(max_length=100, verbose_name='KI-Modell')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('response', models.TextField(verbose_name='Antwort')),
                ('tokens_input', models.IntegerField(default=0, verbose_name='Input Tokens')),
                ('tokens_output', models.IntegerField(default=0, verbose_name='Output Tokens')),
                ('duration', models.FloatField(default=0, verbose_name='Dauer (Sekunden)')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='vskript.vskriptproject')),
            ],
            options={
                'verbose_name': 'VSkript Generierung Log',
                'verbose_name_plural': 'VSkript Generierung Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
