# Generated by Django 5.2.1 on 2025-12-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vskript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vskriptproject',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (Standard)'), ('gpt-4o-mini', 'GPT-4o Mini (Schneller)'), ('gpt-4.1', 'GPT-4.1 (Neueste)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('o4-mini', 'O4 Mini (Reasoning)')], default='gpt-4o', max_length=50, verbose_name='KI-Modell'),
        ),
    ]
