# Generated by Django 5.2.1 on 2025-12-20 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vskript', '0002_vskriptproject_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vskriptproject',
            name='image_format',
            field=models.CharField(choices=[('1024x1024', '1024x1024 (Quadrat)'), ('1792x1024', '1792x1024 (Landscape)'), ('1024x1792', '1024x1792 (Portrait)'), ('512x512', '512x512 (Klein)')], default='1024x1024', max_length=20, verbose_name='Bild-Format'),
        ),
        migrations.AddField(
            model_name='vskriptproject',
            name='image_interval',
            field=models.IntegerField(choices=[(1, 'Alle 1 Sekunde'), (2, 'Alle 2 Sekunden'), (3, 'Alle 3 Sekunden'), (4, 'Alle 4 Sekunden'), (5, 'Alle 5 Sekunden'), (6, 'Alle 6 Sekunden'), (7, 'Alle 7 Sekunden'), (8, 'Alle 8 Sekunden')], default=3, verbose_name='Bild-Intervall (Sekunden)'),
        ),
        migrations.AddField(
            model_name='vskriptproject',
            name='image_model',
            field=models.CharField(choices=[('dall-e-3', 'DALL-E 3 (OpenAI)'), ('dall-e-2', 'DALL-E 2 (OpenAI)'), ('gemini', 'Imagen 3 (Google Gemini)')], default='dall-e-3', max_length=50, verbose_name='Bild-KI-Modell'),
        ),
        migrations.AddField(
            model_name='vskriptproject',
            name='image_style',
            field=models.CharField(choices=[('realistic', 'Realistisch'), ('cinematic', 'Cinematic / Filmisch'), ('anime', 'Anime / Manga'), ('cartoon', 'Cartoon / Comic'), ('3d_render', '3D Render'), ('watercolor', 'Aquarell'), ('oil_painting', 'Ölgemälde'), ('sketch', 'Skizze / Zeichnung'), ('minimalist', 'Minimalistisch'), ('vintage', 'Vintage / Retro'), ('cyberpunk', 'Cyberpunk'), ('fantasy', 'Fantasy')], default='cinematic', max_length=50, verbose_name='Bild-Stil'),
        ),
        migrations.AlterField(
            model_name='vskriptproject',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (Empfohlen)'), ('gpt-4o-mini', 'GPT-4o Mini (Schnell)'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('o3', 'O3 (Reasoning)'), ('o3-pro', 'O3 Pro (Max Reasoning)'), ('o4-mini', 'O4 Mini (Schnelles Reasoning)')], default='gpt-4o', max_length=50, verbose_name='KI-Modell'),
        ),
        migrations.CreateModel(
            name='VSkriptImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_seconds', models.FloatField(verbose_name='Position (Sekunden)')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('prompt', models.TextField(verbose_name='Bild-Prompt')),
                ('prompt_enhanced', models.TextField(blank=True, verbose_name='Erweiterter Prompt')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Bild-URL')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='vskript/images/%Y/%m/', verbose_name='Bild-Datei')),
                ('model_used', models.CharField(max_length=50, verbose_name='Verwendetes Modell')),
                ('style_used', models.CharField(max_length=50, verbose_name='Verwendeter Stil')),
                ('format_used', models.CharField(max_length=20, verbose_name='Verwendetes Format')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('generating', 'Wird generiert'), ('completed', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vskript.vskriptproject')),
            ],
            options={
                'verbose_name': 'VSkript Bild',
                'verbose_name_plural': 'VSkript Bilder',
                'ordering': ['project', 'order'],
            },
        ),
    ]
