# Generated by Django 5.2.1 on 2025-12-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vskript', '0003_vskriptproject_image_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vskriptproject',
            name='ai_model',
            field=models.CharField(choices=[('gpt-5.2', 'GPT-5.2 (Empfohlen)'), ('gpt-5.2-instant', 'GPT-5.2 Instant (Schnell)'), ('gpt-5.2-thinking', 'GPT-5.2 Thinking (Tiefgründig)'), ('gpt-5.2-pro', 'GPT-5.2 Pro (Premium)'), ('gpt-5', 'GPT-5'), ('o3', 'O3 (Reasoning)'), ('o3-pro', 'O3 Pro (Max Reasoning)'), ('o4-mini', 'O4 Mini (Schnelles Reasoning)'), ('gpt-4o', 'GPT-4o (Legacy)'), ('gpt-4o-mini', 'GPT-4o Mini (Legacy)')], default='gpt-5.2', max_length=50, verbose_name='KI-Modell'),
        ),
        migrations.AlterField(
            model_name='vskriptproject',
            name='image_format',
            field=models.CharField(choices=[('1024x1024', '1024x1024 (Quadrat)'), ('1536x1024', '1536x1024 (Landscape)'), ('1024x1536', '1024x1536 (Portrait)'), ('auto', 'Auto (KI wählt)')], default='1024x1024', max_length=20, verbose_name='Bild-Format'),
        ),
        migrations.AlterField(
            model_name='vskriptproject',
            name='image_model',
            field=models.CharField(choices=[('gpt-image-1.5', 'GPT Image 1.5 (OpenAI - Empfohlen)'), ('gpt-image-1', 'GPT Image 1 (OpenAI)'), ('gpt-image-1-mini', 'GPT Image 1 Mini (OpenAI - Günstig)'), ('imagen-4-ultra', 'Imagen 4 Ultra (Google - Beste Qualität)'), ('imagen-4', 'Imagen 4 (Google)'), ('imagen-4-fast', 'Imagen 4 Fast (Google - Schnell)'), ('dall-e-3', 'DALL-E 3 (Legacy)')], default='gpt-image-1.5', max_length=50, verbose_name='Bild-KI-Modell'),
        ),
    ]
