# Generated by Django 5.2.1 on 2025-08-03 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service-Name')),
                ('service_type', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('google', 'Google AI'), ('dalle', 'DALL-E'), ('midjourney', 'Midjourney')], max_length=20, verbose_name='Service-Typ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('api_endpoint', models.URLField(blank=True, null=True, verbose_name='API-Endpunkt')),
                ('max_tokens', models.PositiveIntegerField(default=1000, verbose_name='Maximale Tokens')),
                ('default_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Standard-Modell')),
            ],
            options={
                'verbose_name': 'KI-Service',
                'verbose_name_plural': 'KI-Services',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Kampagnenname')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('basic_idea', models.TextField(verbose_name='Grundlegende Creative-Idee')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='Detaillierte Beschreibung')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Zusätzliche Informationen')),
                ('web_links', models.TextField(blank=True, null=True, verbose_name='Web-Links (ein Link pro Zeile)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kampagne',
                'verbose_name_plural': 'Kampagnen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Creative-Titel')),
                ('description', models.TextField(verbose_name='Creative-Beschreibung')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Bild-URL')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='makeads/creatives/', verbose_name='Creative-Bild')),
                ('text_content', models.TextField(verbose_name='Text-Inhalt')),
                ('ai_prompt_used', models.TextField(blank=True, null=True, verbose_name='Verwendeter AI-Prompt')),
                ('generation_status', models.CharField(choices=[('pending', 'Wird generiert'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('revision', 'Überarbeitung')], default='pending', max_length=20, verbose_name='Generierungsstatus')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Als Favorit markiert')),
                ('generation_batch', models.PositiveIntegerField(default=1, verbose_name='Generierungs-Batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='makeads.campaign')),
            ],
            options={
                'verbose_name': 'Creative',
                'verbose_name_plural': 'Creatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_prompt', models.TextField(verbose_name='Überarbeitungsanweisung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='makeads.creative')),
                ('revised_creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_of', to='makeads.creative')),
            ],
            options={
                'verbose_name': 'Creative-Überarbeitung',
                'verbose_name_plural': 'Creative-Überarbeitungen',
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('initial', 'Initiale Generierung'), ('more', 'Weitere Generierung'), ('revision', 'Überarbeitung')], max_length=20, verbose_name='Job-Typ')),
                ('status', models.CharField(choices=[('queued', 'In Warteschlange'), ('processing', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='queued', max_length=20, verbose_name='Status')),
                ('target_count', models.PositiveIntegerField(default=10, verbose_name='Anzahl zu generierender Creatives')),
                ('generated_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl generierter Creatives')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Fehlermeldung')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='makeads.aiservice', verbose_name='KI-Service')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='makeads.campaign')),
            ],
            options={
                'verbose_name': 'Generierungs-Job',
                'verbose_name_plural': 'Generierungs-Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='makeads/references/', verbose_name='Referenzbild')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bildbeschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='makeads.campaign')),
            ],
            options={
                'verbose_name': 'Referenzbild',
                'verbose_name_plural': 'Referenzbilder',
            },
        ),
    ]
