# Generated by Django 5.2.1 on 2025-08-25 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service-Name')),
                ('service_type', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('google', 'Google AI'), ('dalle', 'DALL-E'), ('midjourney', 'Midjourney')], max_length=20, verbose_name='Service-Typ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('api_endpoint', models.URLField(blank=True, null=True, verbose_name='API-Endpunkt')),
                ('max_tokens', models.PositiveIntegerField(default=1000, verbose_name='Maximale Tokens')),
                ('default_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Standard-Modell')),
            ],
            options={
                'verbose_name': 'KI-Service',
                'verbose_name_plural': 'KI-Services',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Kampagnenname')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('basic_idea', models.TextField(verbose_name='Grundlegende Creative-Idee')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='Detaillierte Beschreibung')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Zusätzliche Informationen')),
                ('web_links', models.TextField(blank=True, null=True, verbose_name='Web-Links (ein Link pro Zeile)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kampagne',
                'verbose_name_plural': 'Kampagnen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Creative-Titel')),
                ('description', models.TextField(verbose_name='Creative-Beschreibung')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Bild-URL')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='makeads/creatives/', verbose_name='Creative-Bild')),
                ('text_content', models.TextField(verbose_name='Text-Inhalt')),
                ('ai_prompt_used', models.TextField(blank=True, null=True, verbose_name='Verwendeter AI-Prompt')),
                ('generation_status', models.CharField(choices=[('pending', 'Wird generiert'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('revision', 'Überarbeitung')], default='pending', max_length=20, verbose_name='Generierungsstatus')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Als Favorit markiert')),
                ('generation_batch', models.PositiveIntegerField(default=1, verbose_name='Generierungs-Batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='makeads.campaign')),
            ],
            options={
                'verbose_name': 'Creative',
                'verbose_name_plural': 'Creatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_prompt', models.TextField(verbose_name='Überarbeitungsanweisung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='makeads.creative')),
                ('revised_creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_of', to='makeads.creative')),
            ],
            options={
                'verbose_name': 'Creative-Überarbeitung',
                'verbose_name_plural': 'Creative-Überarbeitungen',
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('initial', 'Initiale Generierung'), ('more', 'Weitere Generierung'), ('revision', 'Überarbeitung')], max_length=20, verbose_name='Job-Typ')),
                ('status', models.CharField(choices=[('queued', 'In Warteschlange'), ('processing', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='queued', max_length=20, verbose_name='Status')),
                ('target_count', models.PositiveIntegerField(default=10, verbose_name='Anzahl zu generierender Creatives')),
                ('generated_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl generierter Creatives')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Fehlermeldung')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='makeads.aiservice', verbose_name='KI-Service')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='makeads.campaign')),
            ],
            options={
                'verbose_name': 'Generierungs-Job',
                'verbose_name_plural': 'Generierungs-Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='makeads/references/', verbose_name='Referenzbild')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bildbeschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='makeads.campaign')),
            ],
            options={
                'verbose_name': 'Referenzbild',
                'verbose_name_plural': 'Referenzbilder',
            },
        ),
        migrations.CreateModel(
            name='TextOverlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.TextField(verbose_name='Overlay-Text')),
                ('x_position', models.FloatField(default=10.0, verbose_name='X-Position (%)')),
                ('y_position', models.FloatField(default=10.0, verbose_name='Y-Position (%)')),
                ('font_family', models.CharField(choices=[('arial', 'Arial'), ('helvetica', 'Helvetica'), ('times', 'Times New Roman'), ('georgia', 'Georgia'), ('courier', 'Courier New'), ('verdana', 'Verdana'), ('tahoma', 'Tahoma'), ('impact', 'Impact'), ('comic-sans', 'Comic Sans MS'), ('trebuchet', 'Trebuchet MS')], default='arial', max_length=20, verbose_name='Schriftart')),
                ('font_size', models.PositiveIntegerField(default=24, verbose_name='Schriftgröße (px)')),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('light', 'Light'), ('black', 'Black')], default='normal', max_length=10, verbose_name='Schriftgewicht')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Textfarbe (Hex)')),
                ('background_color', models.CharField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Hintergrundfarbe (Hex)')),
                ('background_opacity', models.FloatField(default=0.0, verbose_name='Hintergrund-Transparenz (0-1)')),
                ('text_align', models.CharField(choices=[('left', 'Links'), ('center', 'Zentriert'), ('right', 'Rechts'), ('justify', 'Blocksatz')], default='left', max_length=10, verbose_name='Textausrichtung')),
                ('has_shadow', models.BooleanField(default=True, verbose_name='Text-Schatten')),
                ('shadow_color', models.CharField(default='#000000', max_length=7, verbose_name='Schatten-Farbe (Hex)')),
                ('shadow_blur', models.PositiveIntegerField(default=4, verbose_name='Schatten-Weichzeichnung')),
                ('has_border', models.BooleanField(default=False, verbose_name='Text-Rahmen')),
                ('border_color', models.CharField(default='#000000', max_length=7, verbose_name='Rahmen-Farbe (Hex)')),
                ('border_width', models.PositiveIntegerField(default=1, verbose_name='Rahmen-Breite (px)')),
                ('width', models.PositiveIntegerField(default=200, help_text='Maximale Breite des Text-Containers', verbose_name='Breite (px)')),
                ('line_height', models.FloatField(default=1.2, verbose_name='Zeilenhöhe')),
                ('letter_spacing', models.FloatField(default=0.0, verbose_name='Buchstabenabstand (px)')),
                ('rotation', models.FloatField(default=0.0, verbose_name='Rotation (Grad)')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='KI-generiert')),
                ('ai_prompt_used', models.TextField(blank=True, null=True, verbose_name='Verwendeter AI-Prompt')),
                ('has_gradient', models.BooleanField(default=False, verbose_name='Farbverlauf')),
                ('gradient_start_color', models.CharField(blank=True, default='#FF0000', max_length=7, null=True, verbose_name='Verlauf Startfarbe (Hex)')),
                ('gradient_end_color', models.CharField(blank=True, default='#0000FF', max_length=7, null=True, verbose_name='Verlauf Endfarbe (Hex)')),
                ('gradient_direction', models.CharField(choices=[('to right', 'Horizontal →'), ('to left', 'Horizontal ←'), ('to bottom', 'Vertikal ↓'), ('to top', 'Vertikal ↑'), ('45deg', 'Diagonal ↗'), ('135deg', 'Diagonal ↘'), ('radial', 'Radial')], default='to right', max_length=20, verbose_name='Verlauf-Richtung')),
                ('has_glow', models.BooleanField(default=False, verbose_name='Leuchteffekt')),
                ('glow_color', models.CharField(blank=True, default='#00FFFF', max_length=7, null=True, verbose_name='Leuchtfarbe (Hex)')),
                ('glow_intensity', models.PositiveIntegerField(default=10, verbose_name='Leuchtintensität (px)')),
                ('has_outline', models.BooleanField(default=False, verbose_name='Textumriss')),
                ('outline_color', models.CharField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Umriss-Farbe (Hex)')),
                ('outline_width', models.FloatField(default=1.0, verbose_name='Umriss-Breite (px)')),
                ('has_3d_effect', models.BooleanField(default=False, verbose_name='3D-Effekt')),
                ('effect_depth', models.PositiveIntegerField(default=3, verbose_name='3D-Tiefe (px)')),
                ('effect_color', models.CharField(blank=True, default='#333333', max_length=7, null=True, verbose_name='3D-Effekt-Farbe (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sichtbar')),
                ('z_index', models.PositiveIntegerField(default=1, verbose_name='Ebene (Z-Index)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_overlays', to='makeads.creative')),
            ],
            options={
                'verbose_name': 'Text-Overlay',
                'verbose_name_plural': 'Text-Overlays',
                'ordering': ['z_index', '-created_at'],
            },
        ),
    ]
