# Generated by Django 5.2.1 on 2025-08-18 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextOverlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.TextField(verbose_name='Overlay-Text')),
                ('x_position', models.FloatField(default=10.0, verbose_name='X-Position (%)')),
                ('y_position', models.FloatField(default=10.0, verbose_name='Y-Position (%)')),
                ('font_family', models.CharField(choices=[('arial', 'Arial'), ('helvetica', 'Helvetica'), ('times', 'Times New Roman'), ('georgia', 'Georgia'), ('courier', 'Courier New'), ('verdana', 'Verdana'), ('tahoma', 'Tahoma'), ('impact', 'Impact'), ('comic-sans', 'Comic Sans MS'), ('trebuchet', 'Trebuchet MS')], default='arial', max_length=20, verbose_name='Schriftart')),
                ('font_size', models.PositiveIntegerField(default=24, verbose_name='Schriftgröße (px)')),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('light', 'Light'), ('black', 'Black')], default='normal', max_length=10, verbose_name='Schriftgewicht')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Textfarbe (Hex)')),
                ('background_color', models.CharField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Hintergrundfarbe (Hex)')),
                ('background_opacity', models.FloatField(default=0.0, verbose_name='Hintergrund-Transparenz (0-1)')),
                ('text_align', models.CharField(choices=[('left', 'Links'), ('center', 'Zentriert'), ('right', 'Rechts')], default='left', max_length=10, verbose_name='Textausrichtung')),
                ('has_shadow', models.BooleanField(default=True, verbose_name='Text-Schatten')),
                ('shadow_color', models.CharField(default='#000000', max_length=7, verbose_name='Schatten-Farbe (Hex)')),
                ('shadow_blur', models.PositiveIntegerField(default=4, verbose_name='Schatten-Weichzeichnung')),
                ('has_border', models.BooleanField(default=False, verbose_name='Text-Rahmen')),
                ('border_color', models.CharField(default='#000000', max_length=7, verbose_name='Rahmen-Farbe (Hex)')),
                ('border_width', models.PositiveIntegerField(default=1, verbose_name='Rahmen-Breite (px)')),
                ('width', models.PositiveIntegerField(default=200, help_text='Maximale Breite des Text-Containers', verbose_name='Breite (px)')),
                ('rotation', models.FloatField(default=0.0, verbose_name='Rotation (Grad)')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='KI-generiert')),
                ('ai_prompt_used', models.TextField(blank=True, null=True, verbose_name='Verwendeter AI-Prompt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sichtbar')),
                ('z_index', models.PositiveIntegerField(default=1, verbose_name='Ebene (Z-Index)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_overlays', to='makeads.creative')),
            ],
            options={
                'verbose_name': 'Text-Overlay',
                'verbose_name_plural': 'Text-Overlays',
                'ordering': ['z_index', '-created_at'],
            },
        ),
    ]
