# Generated by Django 5.2.1 on 2025-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeads', '0002_textoverlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoverlay',
            name='letter_spacing',
            field=models.FloatField(default=0.0, verbose_name='Buchstabenabstand (px)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='line_height',
            field=models.FloatField(default=1.2, verbose_name='Zeilenhöhe'),
        ),
        migrations.AlterField(
            model_name='textoverlay',
            name='text_align',
            field=models.CharField(choices=[('left', 'Links'), ('center', 'Zentriert'), ('right', 'Rechts'), ('justify', 'Blocksatz')], default='left', max_length=10, verbose_name='Textausrichtung'),
        ),
    ]
