# Generated by Django 5.2.1 on 2025-08-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeads', '0003_textoverlay_letter_spacing_textoverlay_line_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoverlay',
            name='effect_color',
            field=models.CharField(blank=True, default='#333333', max_length=7, null=True, verbose_name='3D-Effekt-Farbe (Hex)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='effect_depth',
            field=models.PositiveIntegerField(default=3, verbose_name='3D-Tiefe (px)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='glow_color',
            field=models.CharField(blank=True, default='#00FFFF', max_length=7, null=True, verbose_name='Leuchtfarbe (Hex)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='glow_intensity',
            field=models.PositiveIntegerField(default=10, verbose_name='Leuchtintensität (px)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='gradient_direction',
            field=models.CharField(choices=[('to right', 'Horizontal →'), ('to left', 'Horizontal ←'), ('to bottom', 'Vertikal ↓'), ('to top', 'Vertikal ↑'), ('45deg', 'Diagonal ↗'), ('135deg', 'Diagonal ↘'), ('radial', 'Radial')], default='to right', max_length=20, verbose_name='Verlauf-Richtung'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='gradient_end_color',
            field=models.CharField(blank=True, default='#0000FF', max_length=7, null=True, verbose_name='Verlauf Endfarbe (Hex)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='gradient_start_color',
            field=models.CharField(blank=True, default='#FF0000', max_length=7, null=True, verbose_name='Verlauf Startfarbe (Hex)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='has_3d_effect',
            field=models.BooleanField(default=False, verbose_name='3D-Effekt'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='has_glow',
            field=models.BooleanField(default=False, verbose_name='Leuchteffekt'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='has_gradient',
            field=models.BooleanField(default=False, verbose_name='Farbverlauf'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='has_outline',
            field=models.BooleanField(default=False, verbose_name='Textumriss'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='outline_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Umriss-Farbe (Hex)'),
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='outline_width',
            field=models.FloatField(default=1.0, verbose_name='Umriss-Breite (px)'),
        ),
    ]
