# Generated by Django 5.2.1 on 2025-08-25 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Projektname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('source_type', models.CharField(choices=[('upload', 'Hochgeladen'), ('ai_generated', 'KI-generiert'), ('canva_import', 'Canva Import'), ('shopify_import', 'Shopify Import')], default='upload', max_length=20)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='images/originals/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('ai_prompt', models.TextField(blank=True, verbose_name='KI-Prompt')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='KI-Modell')),
                ('ai_generation_params', models.JSONField(blank=True, default=dict)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='images/processed/')),
                ('processing_history', models.JSONField(blank=True, default=list)),
                ('current_settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('processing', 'Wird bearbeitet'), ('completed', 'Abgeschlossen'), ('error', 'Fehler')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_width', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_height', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildprojekt',
                'verbose_name_plural': 'Bildprojekte',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('PNG', 'PNG - Verlustfrei'), ('JPEG', 'JPEG - Komprimiert'), ('WEBP', 'WebP - Modern'), ('SVG', 'SVG - Vektor'), ('PDF', 'PDF - Dokument'), ('TIFF', 'TIFF - Professionell')], max_length=10)),
                ('quality', models.CharField(choices=[('low', 'Niedrig (kleiner)'), ('medium', 'Mittel'), ('high', 'Hoch'), ('max', 'Maximum')], default='high', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('dpi', models.PositiveIntegerField(default=300, help_text='DPI für Druck')),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='image_editor.imageproject')),
            ],
            options={
                'verbose_name': 'Export-Format',
                'verbose_name_plural': 'Export-Formate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngravingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_width', models.FloatField(default=0.1, help_text='Laserstrahl-Breite in mm')),
                ('line_thickness', models.FloatField(default=0.1, help_text='Mindest-Linienstärke in mm')),
                ('depth_levels', models.PositiveIntegerField(default=5, help_text='Anzahl Tiefenstufen')),
                ('max_depth', models.FloatField(default=0.5, help_text='Maximale Gravurtiefe in mm')),
                ('vectorize_threshold', models.FloatField(default=128, help_text='Schwellwert für Vektorisierung (0-255)')),
                ('simplify_tolerance', models.FloatField(default=1.0, help_text='Vereinfachungstoleranz')),
                ('optimize_paths', models.BooleanField(default=True, help_text='Gravurpfade optimieren')),
                ('remove_duplicates', models.BooleanField(default=True, help_text='Doppelte Pfade entfernen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engraving_settings', to='image_editor.imageproject')),
            ],
            options={
                'verbose_name': 'Gravur-Einstellungen',
                'verbose_name_plural': 'Gravur-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='AIGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('negative_prompt', models.TextField(blank=True, verbose_name='Negativ-Prompt')),
                ('ai_model', models.CharField(choices=[('dall-e-3', 'DALL-E 3'), ('dall-e-2', 'DALL-E 2'), ('midjourney', 'Midjourney'), ('stable-diffusion', 'Stable Diffusion')], default='dall-e-3', max_length=30)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('quality', models.CharField(default='standard', max_length=20)),
                ('size', models.CharField(default='1024x1024', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='images/ai_generated/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_editor.imageproject')),
            ],
            options={
                'verbose_name': 'KI-Generierung',
                'verbose_name_plural': 'KI-Generierungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('invert', 'Invertieren'), ('grayscale', 'Schwarzweiß'), ('brightness', 'Helligkeit'), ('contrast', 'Kontrast'), ('saturation', 'Sättigung'), ('hue', 'Farbton'), ('resize', 'Größe ändern'), ('crop', 'Zuschneiden'), ('rotate', 'Drehen'), ('flip_horizontal', 'Horizontal spiegeln'), ('flip_vertical', 'Vertikal spiegeln'), ('remove_background', 'Hintergrund entfernen'), ('prepare_engraving', 'Gravur vorbereiten'), ('vectorize', 'Vektorisieren'), ('enhance_lines', 'Linien verstärken'), ('blur', 'Weichzeichnen'), ('sharpen', 'Schärfen'), ('emboss', 'Prägen'), ('edge_detect', 'Kantenerkennung')], max_length=30)),
                ('parameters', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='images/steps/')),
                ('processing_time', models.FloatField(blank=True, help_text='Zeit in Sekunden', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='image_editor.imageproject')),
            ],
            options={
                'verbose_name': 'Bearbeitungsschritt',
                'verbose_name_plural': 'Bearbeitungsschritte',
                'ordering': ['applied_at'],
            },
        ),
    ]
