# Generated by Django 5.2.1 on 2025-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproject',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Hochgeladen'), ('ai_generated', 'KI-generiert'), ('canva_import', 'Canva Import')], default='upload', max_length=20),
        ),
    ]
