# Generated by Django 5.2.1 on 2025-10-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectprofile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='connectprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standort'),
        ),
        migrations.AddField(
            model_name='connectprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
