# Generated by Django 5.2.1 on 2025-10-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomconnect', '0002_connectprofile_linkedin_connectprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectprofile',
            name='notify_messages',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigung bei neuen Nachrichten'),
        ),
        migrations.AddField(
            model_name='connectprofile',
            name='notify_new_matches',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigung bei neuen Matches'),
        ),
        migrations.AddField(
            model_name='connectprofile',
            name='notify_weekly_digest',
            field=models.BooleanField(default=False, verbose_name='Wöchentliche Zusammenfassung'),
        ),
    ]
