# Generated by Django 5.2.1 on 2025-10-13 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomconnect', '0003_connectprofile_notify_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Öffentlich'), ('connections', 'Nur meine Connections'), ('local', 'Nur aus meiner Umgebung')], default='public', max_length=20, verbose_name='Sichtbarkeit'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Die Anzahl der Jahre muss mindestens 0 sein.'), django.core.validators.MaxValueValidator(50, message='Die Anzahl der Jahre darf maximal 50 sein.')], verbose_name='Jahre Erfahrung'),
        ),
    ]
