# Generated by Django 5.2.1 on 2025-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomconnect', '0004_connectpost_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectpost',
            name='location',
            field=models.CharField(blank=True, help_text='Nur relevant bei "Nur aus meiner Umgebung"', max_length=200, verbose_name='Standort'),
        ),
    ]
