# Generated by Django 5.2.1 on 2025-10-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomconnect', '0005_connectpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectpost',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='loomconnect.connectpost', verbose_name='Geteilt von'),
        ),
    ]
