# Generated by Django 5.2.1 on 2025-10-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomconnect', '0006_connectpost_shared_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Verfügbar'), ('busy', 'Beschäftigt'), ('away', 'Abwesend'), ('dnd', 'Nicht stören')], default='available', max_length=20, verbose_name='Verfügbarkeit'),
        ),
    ]
