# Generated by Django 5.2.1 on 2025-10-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomconnect', '0007_connectprofile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userneed',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Beschreibung'),
        ),
    ]
