# Generated by Django 5.2.1 on 2026-03-28 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('exported_video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Project',
                'verbose_name_plural': 'Video Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('character', 'Character'), ('style', 'Style'), ('product', 'Product')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='videocreator/uploads/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='videocreator.videoproject')),
            ],
            options={
                'verbose_name': 'Video Asset',
                'verbose_name_plural': 'Video Assets',
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True)),
                ('model', models.CharField(default='nano-banana-pro', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='videocreator/generated/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='videocreator.videoproject')),
            ],
            options={
                'verbose_name': 'Generated Image',
                'verbose_name_plural': 'Generated Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField(blank=True)),
                ('video_model', models.CharField(choices=[('kling-2.6/image-to-video', 'Kling 2.6'), ('veo3_fast', 'Veo 3.1 Fast'), ('veo3', 'Veo 3.1 Quality')], default='kling-2.6/image-to-video', max_length=50)),
                ('duration', models.PositiveIntegerField(default=5)),
                ('video_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videocreator/generated/')),
                ('video_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('audio_source', models.CharField(blank=True, max_length=20, null=True)),
                ('audio_tts_text', models.TextField(blank=True)),
                ('audio_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='videocreator/generated/')),
                ('audio_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('end_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_frame_scenes', to='videocreator.generatedimage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='videocreator.videoproject')),
                ('start_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_frame_scenes', to='videocreator.generatedimage')),
            ],
            options={
                'verbose_name': 'Video Scene',
                'verbose_name_plural': 'Video Scenes',
                'ordering': ['order'],
            },
        ),
    ]
