# Generated by Django 5.2.1 on 2025-08-27 08:21

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP Server Host', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP Server Port')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('email_host_user', models.EmailField(help_text='Email address for sending', max_length=254)),
                ('email_host_password', encrypted_model_fields.fields.EncryptedCharField(help_text='Email account password/app password')),
                ('default_from_email', models.EmailField(help_text='Default "From" email address', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Use this configuration')),
                ('backend_type', models.CharField(choices=[('smtp', 'SMTP Backend'), ('console', 'Console Backend (Development)'), ('filebased', 'File-based Backend (Testing)')], default='smtp', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zoho_client_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Zoho Client ID', null=True)),
                ('zoho_client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Zoho Client Secret', null=True)),
                ('zoho_redirect_uri', models.URLField(blank=True, help_text='Zoho Redirect URI', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuperuserEmailShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(help_text='Display name for this email', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description or purpose of this email')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Superuser Email',
                'verbose_name_plural': 'Shared Superuser Emails',
                'ordering': ['display_name'],
            },
        ),
    ]
