# Generated by Django 5.2.1 on 2025-09-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superconfig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel der Nachricht', max_length=200)),
                ('content', models.TextField(help_text='Inhalt der Nachricht')),
                ('display_position', models.CharField(choices=[('popup_center', 'Popup - Mitte'), ('popup_top', 'Popup - Oben'), ('banner_top', 'Banner - Oben'), ('banner_bottom', 'Banner - Unten'), ('toast_top_right', 'Toast - Oben Rechts'), ('toast_top_left', 'Toast - Oben Links'), ('toast_bottom_right', 'Toast - Unten Rechts'), ('toast_bottom_left', 'Toast - Unten Links'), ('sidebar_right', 'Seitlich - Rechts'), ('sidebar_left', 'Seitlich - Links')], default='popup_center', help_text='Position der Nachrichtenanzeige', max_length=50)),
                ('display_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warnung'), ('success', 'Erfolg'), ('error', 'Fehler'), ('announcement', 'Ankündigung')], default='info', help_text='Art der Nachricht (bestimmt Farbe/Icon)', max_length=20)),
                ('visibility', models.CharField(choices=[('all', 'Alle Besucher'), ('authenticated', 'Nur angemeldete Benutzer'), ('unauthenticated', 'Nur nicht angemeldete Besucher')], default='all', help_text='Wer soll diese Nachricht sehen', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Anzeigedauer in Sekunden (leer = unendlich)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Nachricht aktiv anzeigen')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Benutzer kann Nachricht schließen')),
                ('start_date', models.DateTimeField(blank=True, help_text='Startdatum (leer = sofort)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Enddatum (leer = unbegrenzt)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Globale Nachricht',
                'verbose_name_plural': 'Globale Nachrichten',
                'ordering': ['-created_at'],
            },
        ),
    ]
