# Generated by Django 5.2.1 on 2025-09-29 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superconfig', '0002_globalmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMessageDebugSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_debug_enabled', models.BooleanField(default=True, help_text='Debug-Anzeige aktivieren/deaktivieren')),
                ('debug_visibility', models.CharField(choices=[('disabled', 'Ausgeschaltet'), ('staff_only', 'Nur Staff-Benutzer'), ('superuser_only', 'Nur Superuser'), ('authenticated', 'Alle angemeldeten Benutzer'), ('all', 'Alle Benutzer')], default='staff_only', help_text='Wer soll die Debug-Anzeige sehen können', max_length=20)),
                ('show_message_details', models.BooleanField(default=True, help_text='Details der aktiven Nachrichten anzeigen')),
                ('show_user_info', models.BooleanField(default=True, help_text='Benutzerinformationen anzeigen')),
                ('show_statistics', models.BooleanField(default=True, help_text='Nachrichtenstatistiken anzeigen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Messages Debug-Einstellungen',
                'verbose_name_plural': 'Global Messages Debug-Einstellungen',
            },
        ),
    ]
