# Generated by Django 5.2.1 on 2025-09-29 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superconfig', '0003_globalmessagedebugsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmessage',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Spezifische Benutzer für diese Nachricht (nur relevant wenn Sichtbarkeit = "Bestimmte Benutzer")', related_name='targeted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalmessage',
            name='visibility',
            field=models.CharField(choices=[('all', 'Alle Besucher'), ('authenticated', 'Nur angemeldete Benutzer'), ('unauthenticated', 'Nur nicht angemeldete Besucher'), ('specific_users', 'Bestimmte Benutzer'), ('staff_only', 'Nur Staff-Benutzer'), ('superuser_only', 'Nur Superuser')], default='all', help_text='Wer soll diese Nachricht sehen', max_length=20),
        ),
    ]
