# Generated by Django 5.2.1 on 2026-01-02 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superconfig', '0004_globalmessage_target_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('youtube', 'YouTube'), ('zoho', 'Zoho Mail'), ('ideogram', 'Ideogram'), ('gemini', 'Gemini'), ('shopify', 'Shopify'), ('pinterest', 'Pinterest'), ('upload_post', 'Upload-Post')], help_text='API Provider', max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Anzeigename (falls abweichend vom Standard)', max_length=100)),
                ('affiliate_link', models.URLField(blank=True, help_text='Affiliate Link (öffnet in neuem Tab)', max_length=500)),
                ('affiliate_link_text', models.CharField(default='API-Key erhalten', help_text='Button-Text für den Affiliate Link', max_length=100)),
                ('is_visible', models.BooleanField(default=True, help_text='Karte für normale Nutzer anzeigen')),
                ('sort_order', models.IntegerField(default=0, help_text='Sortierreihenfolge (niedrigere Werte zuerst)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Provider Einstellung',
                'verbose_name_plural': 'API Provider Einstellungen',
                'ordering': ['sort_order', 'provider'],
            },
        ),
    ]
