# Generated by Django 5.2.1 on 2026-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superconfig', '0005_add_api_provider_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiprovidersettings',
            name='direct_link',
            field=models.URLField(blank=True, help_text='Direkter Link zum Anbieter (erscheint nach Affiliate-Klick)', max_length=500),
        ),
        migrations.AddField(
            model_name='apiprovidersettings',
            name='direct_link_text',
            field=models.CharField(default='Direkt zum Anbieter', help_text='Button-Text für den Direkt-Link', max_length=100),
        ),
    ]
