# Generated by Django 5.2.1 on 2026-01-03 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superconfig', '0006_add_direct_link_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Button-Titel')),
                ('url', models.URLField(help_text='Ziel-URL beim Klick', verbose_name='URL')),
                ('description', models.CharField(blank=True, help_text='Optionale Beschreibung unter dem Button', max_length=200, verbose_name='Beschreibung')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Klicks (gesamt)')),
                ('last_clicked', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Klick')),
            ],
            options={
                'verbose_name': 'Social Page Button',
                'verbose_name_plural': 'Social Page Buttons',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='social_page/', verbose_name='Profilbild')),
                ('profile_description', models.TextField(blank=True, help_text='Optionale Beschreibung unter dem Profilbild (max. 500 Zeichen)', max_length=500, verbose_name='Profil-Beschreibung')),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex-Farbcode (z.B. #ffffff)', max_length=7, verbose_name='Hintergrundfarbe')),
                ('button_color', models.CharField(default='#000000', help_text='Hex-Farbcode für die Buttons', max_length=7, verbose_name='Button-Farbe')),
                ('button_text_color', models.CharField(default='#ffffff', help_text='Hex-Farbcode für den Button-Text', max_length=7, verbose_name='Button-Textfarbe')),
                ('show_affiliate_disclaimer', models.BooleanField(default=False, verbose_name='Affiliate-Hinweis anzeigen')),
                ('affiliate_disclaimer_text', models.TextField(blank=True, default='Diese Seite enthält Affiliate-Links. Bei einem Kauf über diese Links erhalte ich eine kleine Provision.', verbose_name='Affiliate-Hinweis Text')),
                ('is_active', models.BooleanField(default=True, help_text='Seite öffentlich zugänglich machen', verbose_name='Seite aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Page Konfiguration',
                'verbose_name_plural': 'Social Page Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='SocialPageClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse (anonymisiert)')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('referer', models.URLField(blank=True, verbose_name='Referrer')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='superconfig.socialpagebutton')),
            ],
            options={
                'verbose_name': 'Button-Klick',
                'verbose_name_plural': 'Button-Klicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddField(
            model_name='socialpagebutton',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='superconfig.socialpageconfig'),
        ),
        migrations.CreateModel(
            name='SocialPageIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'E-Mail')], max_length=20, verbose_name='Plattform')),
                ('url', models.URLField(help_text='Link zum Social Media Profil', verbose_name='URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='superconfig.socialpageconfig')),
            ],
            options={
                'verbose_name': 'Social Media Icon',
                'verbose_name_plural': 'Social Media Icons',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
