# Generated by Django 5.2.1 on 2026-01-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superconfig', '0007_social_page_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpageconfig',
            name='profile_text_color',
            field=models.CharField(default='#333333', help_text='Hex-Farbcode für die Profilbeschreibung', max_length=7, verbose_name='Profil-Textfarbe'),
        ),
    ]
