# Generated by Django 5.2.1 on 2025-09-23 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name des SEO-Projekts', max_length=200, verbose_name='Projektname')),
                ('description', models.TextField(blank=True, help_text='Kurze Projektbeschreibung', verbose_name='Beschreibung')),
                ('domain', models.CharField(blank=True, help_text='Website-Domain (z.B. example.com)', max_length=255, verbose_name='Domain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Was wurde erledigt?', max_length=200, verbose_name='Aufgabe')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Beschreibung (optional)', verbose_name='Details')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erledigt am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingetragen am')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='loomline.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Erledigte Aufgabe',
                'verbose_name_plural': 'Erledigte Aufgaben',
                'ordering': ['-completed_at'],
            },
        ),
    ]
