# Generated by Django 5.2.1 on 2025-09-23 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Andere Nutzer, die an diesem Projekt mitarbeiten können', related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, help_text='Website oder relevante URL (optional)', max_length=255, verbose_name='Website/URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name des Projekts', max_length=200, verbose_name='Projektname'),
        ),
    ]
