# Generated by Django 5.2.1 on 2025-09-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomline', '0002_project_members_alter_project_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskentry',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Verweis auf die Hauptaufgabe (bei Sub-Aufgaben)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='loomline.taskentry', verbose_name='Übergeordnete Aufgabe'),
        ),
    ]
