# Generated by Django 5.2.1 on 2025-09-24 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomline', '0003_taskentry_parent_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('send_at', models.DateTimeField(verbose_name='Sendezeitpunkt')),
                ('sent', models.BooleanField(default=False, verbose_name='Gesendet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('task_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='loomline.taskentry', verbose_name='Aufgabe')),
                ('user_to_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zu benachrichtigender Nutzer')),
            ],
            options={
                'verbose_name': 'Geplante Benachrichtigung',
                'verbose_name_plural': 'Geplante Benachrichtigungen',
                'ordering': ['-send_at'],
            },
        ),
    ]
