"""
Django settings for Schuch project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(kg*xcvmm*p(77-ai*pa5tz1&g(o2x!jyd)f##sf7820y=*yo8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'tarasyuzkiv.pythonanywhere.com',
    'www.workloom.de',
    'workloom.de',
    '10.63.100.139',
    '127.0.0.1',
    'localhost',
    'testserver',  # For Django testing
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps',  # SEO: Sitemap Framework
    # django-allauth für Social Login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'channels',
    'rest_framework',
    'accounts',
    'sportplatzApp',
    'pdf_sucher',
    'amortization_calculator',
    'core',
    'naturmacher',
    'todos',
    'chat',
    'shopify_manager',
    'shopify_uploads',
    'image_editor',
    'bug_report',
    'videos',
    'mycut',
    'encrypted_model_fields',
    'organization',
    'payments',
    'lighting_tools',
    'mail_app',
    'email_templates',
    'somi_plan',
    'makeads',
    'streamrec',
    'superconfig',
    'codelib',
    'promptpro',
    'loomads',
    'lighting_classification',
    'loomline',
    'fileshare',
    'loomconnect',
    'myprompter',
    'stats',
    'keyengine',
    'ideopin',
    'questionfinder',
    'imageforge',
    'blogprep',
    'vskript',
    'linkloom',
]



MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',  # Komprimiert Responses (40-70% kleiner)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'shopify_uploads.middleware.DisableRedirectForAPIMiddleware',  # Disable redirects for Shopify API
    'shopify_uploads.middleware.MediaCORSMiddleware',  # CORS headers for media files
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # django-allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.PublicAppRedirectMiddleware',  # Redirect unauthenticated users to app info pages
    'stats.middleware.StatsTrackingMiddleware',  # Website statistics tracking
    'stats.error_middleware.DetailedErrorLoggingMiddleware',  # Enhanced error logging
    'chat.middleware.RateLimitMiddleware',
    'chat.middleware.ChatRateLimitMiddleware',
    'makeads.middleware.APIKeyCacheMiddleware',  # MakeAds API-Key Cache Management
]

ROOT_URLCONF = 'Schuch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'core.context_processors.seo_defaults',  # SEO Context Processor
                'core.context_processors.dynamic_menu',  # Dynamisches Menü
            ],
        },
    },
]

WSGI_APPLICATION = 'Schuch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use MySQL if DB_ENGINE is set, otherwise fall back to SQLite
if os.getenv('DB_ENGINE') == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'workloom'),
            'USER': os.getenv('DB_USER', 'workloom'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'workloom123'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                # Enforce strict mode and ensure utf8mb4 support for emojis/special chars
                'init_command': "SET SESSION sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
                'use_unicode': True,
            },
            # Connection Health Checks: Prüft Verbindung vor Wiederverwendung (Django 4.1+)
            # Löst PythonAnywhere MySQL "Lost connection" Fehler
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    # SQLite fallback (default für lokale Entwicklung ohne ENV-Variablen)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'CONN_MAX_AGE': 600,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# E-Mail-Konfiguration
EMAIL_BACKEND = 'superconfig.email_backend.AutoFallbackEmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.zoho.eu')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'kontakt@workloom.de')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Workloom <kontakt@workloom.de>')

# Domain-Konfiguration für E-Mail-Links
SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'workloom.de')
SITE_PROTOCOL = os.getenv('SITE_PROTOCOL', 'https')

# Django Sites Framework
SITE_ID = 1

# WICHTIG: Immer unser AutoFallbackEmailBackend verwenden!
# Das Backend lädt die Konfiguration automatisch aus der Datenbank
# Kein Console-Fallback mehr - SuperConfig verwaltet alles über die Datenbank
print("📧 Email-System: Verwendet SuperConfig AutoFallbackEmailBackend (Datenbank-Konfiguration)")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#STATIC_ROOT = BASE_DIR / 'staticfiles'

# KI-API Konfiguration für Naturmacher Schulungserstellung
# Laden der .env Datei für lokale Entwicklung
# API-Keys werden jetzt über die Datenbank pro User verwaltet
# Fallback für Kompatibilität (falls alte Funktionen diese noch verwenden)
OPENAI_API_KEY = None
ANTHROPIC_API_KEY = None
GOOGLE_AI_API_KEY = None

# Einstellungen für von Benutzern hochgeladene Dateien (Media Files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File Upload Settings - Erhöhte Limits für Video-Uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500 MB

# Agora Video/Audio Configuration
AGORA_APP_ID = os.getenv('AGORA_APP_ID', 'your_agora_app_id_here')
AGORA_APP_CERTIFICATE = os.getenv('AGORA_APP_CERTIFICATE', 'your_agora_app_certificate_here')

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# django-allauth: Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# django-allauth: Konfiguration
ACCOUNT_LOGIN_ON_GET = True  # Direkter Redirect statt Login-Button
ACCOUNT_LOGOUT_ON_GET = True  # Direkter Logout ohne Bestätigung
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Erlaube Login mit Username oder Email
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Keine Email-Verifikation (optional: 'mandatory')
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'
ACCOUNT_ADAPTER = 'accounts.allauth_adapter.CustomAccountAdapter'  # Custom Adapter
SOCIALACCOUNT_ADAPTER = 'accounts.allauth_adapter.CustomSocialAccountAdapter'  # Custom Social Adapter

# django-allauth: Socialaccount Konfiguration
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatische Account-Erstellung bei Social Login
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True  # Google soll Email abfragen
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # Automatisches Verbinden wenn Email bereits existiert
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

FIELD_ENCRYPTION_KEY = 'JFkYsizDtDsUc1MTl5RogD_uPnyRB0wWFAZ5VtKRqow='

# WebSocket support enabled for WebRTC signaling only
ASGI_APPLICATION = 'Schuch.asgi.application'

# Channel Layers for WebSocket support
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Allow same-origin iframes for content editor
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Caching configuration for rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Video hosting without processing - direct file serving

# Stripe Settings
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Mail App Configuration - EU Region
ZOHO_MAIL_CONFIG = {
    'CLIENT_ID': os.getenv('ZOHO_CLIENT_ID', ''),
    'CLIENT_SECRET': os.getenv('ZOHO_CLIENT_SECRET', ''),
    'REDIRECT_URI': os.getenv('ZOHO_REDIRECT_URI', ''),
    'SCOPE': 'ZohoMail.messages.ALL,ZohoMail.folders.ALL,ZohoMail.accounts.READ',
    'BASE_URL': 'https://mail.zoho.eu/api/',
    'AUTH_URL': 'https://accounts.zoho.eu/oauth/v2/auth',
    'TOKEN_URL': 'https://accounts.zoho.eu/oauth/v2/token',
    'REGION': 'EU',
}

# Email Settings for Mail App
MAIL_APP_SETTINGS = {
    'DEFAULT_EMAIL_ACCOUNT': 'kontakt@workloom.de',
    'EMAIL_SYNC_INTERVAL': 300,  # 5 minutes
    'MAX_ATTACHMENT_SIZE': 25,   # MB
    'MAX_EMAILS_PER_SYNC': 100,
    'ENABLE_REAL_TIME_SYNC': True,
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# Celery Configuration for Background Tasks
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Site Configuration für E-Mail Links
SITE_DOMAIN = 'www.workloom.de'
SITE_NAME = 'WorkLoom'

# Celery Beat Scheduler for periodic tasks
CELERY_BEAT_SCHEDULE = {
    'sync-emails': {
        'task': 'mail_app.tasks.sync_emails',
        'schedule': MAIL_APP_SETTINGS['EMAIL_SYNC_INTERVAL'],
    },
    'send-loomline-notifications': {
        'task': 'loomline.tasks.send_scheduled_notifications',
        'schedule': 300.0,  # Every 5 minutes
    },
}
