"""
Django settings for Schuch project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(kg*xcvmm*p(77-ai*pa5tz1&g(o2x!jyd)f##sf7820y=*yo8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'tarasyuzkiv.pythonanywhere.com',
    'www.workloom.de',
    'workloom.de',
    '10.63.100.139',
    '127.0.0.1',
    'localhost',
    'testserver',  # For Django testing
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'channels',
    'rest_framework',
    'accounts',
    'sportplatzApp',
    'pdf_sucher',
    'amortization_calculator',
    'core',
    'naturmacher',
    'todos',
    'chat',
    'shopify_manager',
    'image_editor',
    'bug_report',
    'videos',
    'encrypted_model_fields',
    'organization',
    'payments',
    'mail_app',
    'email_templates',
    'somi_plan',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chat.middleware.RateLimitMiddleware',
    'chat.middleware.ChatRateLimitMiddleware',
]

ROOT_URLCONF = 'Schuch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'Schuch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# E-Mail-Konfiguration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'kontakt@workloom.de')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Workloom <kontakt@workloom.de>')

# Fallback für Entwicklung - wenn keine E-Mail-Credentials vorhanden
if not EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("⚠️  WARNUNG: Keine E-Mail-Credentials gefunden. E-Mails werden in der Konsole ausgegeben.")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#STATIC_ROOT = BASE_DIR / 'staticfiles'

# KI-API Konfiguration für Naturmacher Schulungserstellung
# Laden der .env Datei für lokale Entwicklung
# API-Keys werden jetzt über die Datenbank pro User verwaltet
# Fallback für Kompatibilität (falls alte Funktionen diese noch verwenden)
OPENAI_API_KEY = None
ANTHROPIC_API_KEY = None
GOOGLE_AI_API_KEY = None

# Einstellungen für von Benutzern hochgeladene Dateien (Media Files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Agora Video/Audio Configuration
AGORA_APP_ID = os.getenv('AGORA_APP_ID', 'your_agora_app_id_here')
AGORA_APP_CERTIFICATE = os.getenv('AGORA_APP_CERTIFICATE', 'your_agora_app_certificate_here')

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/'

FIELD_ENCRYPTION_KEY = 'JFkYsizDtDsUc1MTl5RogD_uPnyRB0wWFAZ5VtKRqow='

# WebSocket support enabled for WebRTC signaling only
ASGI_APPLICATION = 'Schuch.asgi.application'

# Channel Layers for WebSocket support
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Allow same-origin iframes for content editor
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Caching configuration for rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Video hosting without processing - direct file serving

# Stripe Settings
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Mail App Configuration - EU Region
ZOHO_MAIL_CONFIG = {
    'CLIENT_ID': os.getenv('ZOHO_CLIENT_ID', ''),
    'CLIENT_SECRET': os.getenv('ZOHO_CLIENT_SECRET', ''),
    'REDIRECT_URI': os.getenv('ZOHO_REDIRECT_URI', ''),
    'SCOPE': 'ZohoMail.messages.ALL,ZohoMail.folders.ALL,ZohoMail.accounts.READ',
    'BASE_URL': 'https://mail.zoho.eu/api/',
    'AUTH_URL': 'https://accounts.zoho.eu/oauth/v2/auth',
    'TOKEN_URL': 'https://accounts.zoho.eu/oauth/v2/token',
    'REGION': 'EU',
}

# Email Settings for Mail App
MAIL_APP_SETTINGS = {
    'DEFAULT_EMAIL_ACCOUNT': 'kontakt@workloom.de',
    'EMAIL_SYNC_INTERVAL': 300,  # 5 minutes
    'MAX_ATTACHMENT_SIZE': 25,   # MB
    'MAX_EMAILS_PER_SYNC': 100,
    'ENABLE_REAL_TIME_SYNC': True,
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# Celery Configuration for Background Tasks
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Scheduler for periodic tasks
CELERY_BEAT_SCHEDULE = {
    'sync-emails': {
        'task': 'mail_app.tasks.sync_emails',
        'schedule': MAIL_APP_SETTINGS['EMAIL_SYNC_INTERVAL'],
    },
}
