# Generated by Django 5.2.1 on 2025-12-09 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions_found', models.IntegerField(default=0)),
                ('ai_questions_generated', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fragen-Suche',
                'verbose_name_plural': 'Fragen-Suchen',
                'ordering': ['-search_date'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('keyword', models.CharField(max_length=200)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], default='informational', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('google_paa', 'Google People Also Ask'), ('google_related', 'Google Related Searches'), ('ai_generated', 'KI-Generiert')], default='google_paa', max_length=20)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionfinder.questionsearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gespeicherte Frage',
                'verbose_name_plural': 'Gespeicherte Fragen',
                'ordering': ['intent', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='questionsearch',
            index=models.Index(fields=['user', 'keyword'], name='questionfin_user_id_85be47_idx'),
        ),
        migrations.AddIndex(
            model_name='questionsearch',
            index=models.Index(fields=['search_date'], name='questionfin_search__f64ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquestion',
            index=models.Index(fields=['user', 'keyword'], name='questionfin_user_id_bc1ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquestion',
            index=models.Index(fields=['intent'], name='questionfin_intent_0e0bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquestion',
            index=models.Index(fields=['is_saved'], name='questionfin_is_save_20f2a5_idx'),
        ),
    ]
