# Generated by Django 5.2.1 on 2025-09-27 23:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_ad_clicks', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.DurationField(blank=True, null=True)),
                ('bounce_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-view_count'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=100)),
                ('ad_name', models.CharField(blank=True, max_length=200)),
                ('campaign_name', models.CharField(blank=True, max_length=200)),
                ('zone_name', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('page_url', models.URLField(max_length=500)),
                ('click_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_ad_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-click_time'],
                'indexes': [models.Index(fields=['click_time'], name='stats_adcli_click_t_db73b0_idx'), models.Index(fields=['ad_id'], name='stats_adcli_ad_id_844395_idx'), models.Index(fields=['campaign_name'], name='stats_adcli_campaig_206f22_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_time'],
                'indexes': [models.Index(fields=['visit_time'], name='stats_pagev_visit_t_f79c81_idx'), models.Index(fields=['url'], name='stats_pagev_url_f5e964_idx'), models.Index(fields=['user'], name='stats_pagev_user_id_690f16_idx'), models.Index(fields=['ip_address'], name='stats_pagev_ip_addr_5ec891_idx')],
            },
        ),
    ]
