# Generated by Django 5.2.1 on 2025-09-28 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('avg_page_load_time', models.FloatField(default=0.0)),
                ('server_response_time', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('pages_per_session', models.FloatField(default=0.0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('conversion_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='connection_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='page_load_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('step_order', models.PositiveIntegerField()),
                ('page_url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name', 'step_order'],
                'unique_together': {('name', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.conversionfunnel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('404', '404 - Page Not Found'), ('500', '500 - Server Error'), ('403', '403 - Forbidden'), ('400', '400 - Bad Request'), ('js', 'JavaScript Error')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('current_page', models.URLField(max_length=500)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
