# Generated by Django 5.2.1 on 2025-09-28 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_performancemetric_pagevisit_browser_pagevisit_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='app_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='django_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='first_occurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='memory_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='occurrence_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='pages_visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='python_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='referer_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='request_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='request_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='server_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='session_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low - Minor Issue'), ('medium', 'Medium - Needs Attention'), ('high', 'High - Important'), ('critical', 'Critical - Immediate Action Required')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='stack_trace',
            field=models.TextField(blank=True, help_text='Full stack trace'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='view_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_type',
            field=models.CharField(choices=[('404', '404 - Page Not Found'), ('500', '500 - Server Error'), ('403', '403 - Forbidden'), ('400', '400 - Bad Request'), ('js', 'JavaScript Error'), ('timeout', 'Request Timeout'), ('memory', 'Memory Error'), ('database', 'Database Error'), ('permission', 'Permission Error'), ('validation', 'Validation Error')], max_length=15),
        ),
    ]
