# Generated by Django 5.2.1 on 2026-01-03 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkLoomButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Klicks')),
                ('last_clicked', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt geklickt')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LinkLoomClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Geklickt am')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse (anonymisiert)')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, verbose_name='Referer')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='linkloom.linkloombutton', verbose_name='Button')),
            ],
            options={
                'verbose_name': 'Klick',
                'verbose_name_plural': 'Klicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkLoomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='workloom.de/l/<slug>', unique=True, validators=[django.core.validators.RegexValidator(message='Nur Kleinbuchstaben, Zahlen und Bindestriche erlaubt', regex='^[a-z0-9-]+$')], verbose_name='URL-Slug')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='linkloom/profiles/', verbose_name='Profilbild')),
                ('profile_description', models.TextField(blank=True, max_length=500, verbose_name='Beschreibung')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Hintergrundfarbe')),
                ('button_color', models.CharField(default='#000000', max_length=7, verbose_name='Button-Farbe')),
                ('button_text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Button-Textfarbe')),
                ('profile_text_color', models.CharField(default='#333333', max_length=7, verbose_name='Profil-Textfarbe')),
                ('custom_impressum', models.TextField(blank=True, help_text='Dein individuelles Impressum für diese Seite', verbose_name='Eigenes Impressum')),
                ('show_affiliate_disclaimer', models.BooleanField(default=False, verbose_name='Affiliate-Hinweis anzeigen')),
                ('affiliate_disclaimer_text', models.TextField(blank=True, default='Diese Seite enthält Affiliate-Links. Bei einem Kauf erhalte ich eine kleine Provision.', verbose_name='Affiliate-Hinweis Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkloom_page', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'LinkLoom Seite',
                'verbose_name_plural': 'LinkLoom Seiten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkLoomIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('twitch', 'Twitch'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('spotify', 'Spotify'), ('github', 'GitHub'), ('website', 'Website'), ('email', 'E-Mail')], max_length=20, verbose_name='Plattform')),
                ('url', models.URLField(verbose_name='URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='linkloom.linkloompage', verbose_name='Seite')),
            ],
            options={
                'verbose_name': 'Social Icon',
                'verbose_name_plural': 'Social Icons',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='linkloombutton',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='linkloom.linkloompage', verbose_name='Seite'),
        ),
    ]
