# Generated by Django 5.2.1 on 2025-08-25 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Font Awesome Icon Klasse', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Bootstrap Farbe oder Hex-Code', max_length=20)),
                ('character_limit', models.IntegerField(default=280, help_text='Zeichen-Limit für Posts')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plattform',
                'verbose_name_plural': 'Plattformen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('strategy_data', models.JSONField(blank=True, default=dict, help_text='KI-generierte Strategie-Vorschläge')),
                ('user_profile', models.TextField(help_text='Was bin ich, was habe ich, was kann ich')),
                ('target_audience', models.TextField(help_text='Zielgruppe und Themenbereich')),
                ('goals', models.TextField(help_text='Zielsetzung der Social Media Strategie')),
                ('vision', models.TextField(help_text='Wunschvorstellung/Vision')),
                ('story_mode', models.CharField(choices=[('individual', 'Einzelne Posts'), ('story', 'Story-Serie')], default='individual', help_text='Art der Posts: einzeln oder als zusammenhängende Story', max_length=20)),
                ('story_post_count', models.IntegerField(default=5, help_text='Anzahl Posts für Story-Serie (2-10)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somi_plan.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posting-Plan',
                'verbose_name_plural': 'Posting-Pläne',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Überschrift der Kachel', max_length=200)),
                ('content', models.TextField(help_text='Haupt-Content des Posts')),
                ('script', models.TextField(help_text='Detailliertes Skript und Anweisungen')),
                ('ai_generated', models.BooleanField(default=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('character_count', models.IntegerField(default=0)),
                ('hashtags', models.CharField(blank=True, help_text='Vorgeschlagene Hashtags', max_length=500)),
                ('call_to_action', models.CharField(blank=True, max_length=200)),
                ('post_type', models.CharField(blank=True, help_text='z.B. Tipp, Story, Werbung', max_length=50)),
                ('priority', models.IntegerField(default=3, help_text='1=Hoch, 2=Mittel, 3=Niedrig')),
                ('story_position', models.IntegerField(blank=True, help_text='Position in der Story-Serie (1, 2, 3, ...)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='somi_plan.postingplan')),
            ],
            options={
                'verbose_name': 'Post Content',
                'verbose_name_plural': 'Post Contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(choices=[(1, 'Schritt 1: Basis-Setup'), (2, 'Schritt 2: Strategie-Entwicklung'), (3, 'Schritt 3: Content-Erstellung')], default=1)),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='Temporary data während der Session')),
                ('completed_steps', models.JSONField(blank=True, default=list, help_text='Liste der abgeschlossenen Schritte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='somi_plan.postingplan')),
            ],
            options={
                'verbose_name': 'Planning Session',
                'verbose_name_plural': 'Planning Sessions',
            },
        ),
        migrations.CreateModel(
            name='PostSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Geplant'), ('posted', 'Veröffentlicht'), ('completed', 'Erledigt'), ('cancelled', 'Abgebrochen')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notizen zur Umsetzung')),
                ('actual_post_url', models.URLField(blank=True, help_text='Link zum veröffentlichten Post')),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='somi_plan.postcontent')),
            ],
            options={
                'verbose_name': 'Post Schedule',
                'verbose_name_plural': 'Post Schedules',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to='somi_plan.platform')),
            ],
            options={
                'verbose_name': 'Template Kategorie',
                'verbose_name_plural': 'Template Kategorien',
                'ordering': ['name'],
                'unique_together': {('name', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content_template', models.TextField(help_text='Template mit Platzhaltern: {thema}, {zielgruppe}, etc.')),
                ('script_template', models.TextField(help_text='Anweisungs-Template')),
                ('ai_system_prompt', models.TextField(blank=True)),
                ('ai_user_prompt_template', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='somi_plan.templatecategory')),
            ],
            options={
                'verbose_name': 'Post Template',
                'verbose_name_plural': 'Post Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
