# Generated by Django 5.2.1 on 2025-08-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somi_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='story_position',
            field=models.IntegerField(blank=True, help_text='Position in der Story-Serie (1, 2, 3, ...)', null=True),
        ),
        migrations.AddField(
            model_name='postingplan',
            name='story_mode',
            field=models.CharField(choices=[('individual', 'Einzelne Posts'), ('story', 'Story-Serie')], default='individual', help_text='Art der Posts: einzeln oder als zusammenhängende Story', max_length=20),
        ),
        migrations.AddField(
            model_name='postingplan',
            name='story_post_count',
            field=models.IntegerField(default=5, help_text='Anzahl Posts für Story-Serie (2-10)'),
        ),
    ]
