# Generated by Django 5.2.1 on 2025-09-29 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferstatistics',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Transfer-Statistiken'},
        ),
        migrations.AlterField(
            model_name='transfer',
            name='download_limit',
            field=models.IntegerField(default=0, help_text='Maximale Anzahl erlaubter Downloads. 0 = unbegrenzt', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='expires_at',
            field=models.DateTimeField(help_text='Wann dieser Transfer abläuft'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='message',
            field=models.TextField(blank=True, help_text='Optionale Nachricht an Empfänger'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Optionaler Passwortschutz', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='E-Mail des Absenders, falls nicht registriert', max_length=254),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(blank=True, help_text='Optionaler Titel für den Transfer', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='total_size',
            field=models.BigIntegerField(default=0, help_text='Gesamtgröße aller Dateien in Bytes'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('email', 'E-Mail-Transfer'), ('link', 'Link-Transfer')], default='link', max_length=10),
        ),
        migrations.AlterField(
            model_name='transferfile',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('clean', 'Sauber'), ('infected', 'Infiziert'), ('error', 'Scan-Fehler')], default='pending', max_length=10),
        ),
    ]
