# Generated by Django 5.2.1 on 2026-06-20 19:08

import django.db.models.deletion
import voice_pot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, default=voice_pot.models._new_uid, max_length=24, unique=True)),
                ('audio_file', models.FileField(upload_to='voice/%Y/%m/')),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Bytes')),
                ('shopify_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('shopify_product_id', models.CharField(blank=True, max_length=100)),
                ('order_name', models.CharField(blank=True, help_text='z.B. #1234', max_length=60)),
                ('gift_message', models.CharField(blank=True, help_text='Gravur-/Begleittext', max_length=300)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('consent', models.BooleanField(default=False, help_text='Nutzungsrechte bestaetigt')),
                ('is_approved', models.BooleanField(default=False, help_text='Vom Admin freigegeben (oeffentlich hoerbar)')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktiviert = nicht mehr abrufbar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='voice_pot_v_created_a73111_idx'), models.Index(fields=['shopify_order_id'], name='voice_pot_v_shopify_e1bfdf_idx')],
            },
        ),
    ]
