# Generated by Django 5.2.1 on 2025-09-18 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEmailNotificationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_send_at', models.DateTimeField(verbose_name='Geplanter Versand')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Benachrichtigung gesendet')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Abgebrochen')),
                ('cancelled_reason', models.CharField(blank=True, max_length=100, verbose_name='Grund für Abbruch')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_trackers', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_email_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat E-Mail-Benachrichtigung Tracker',
                'verbose_name_plural': 'Chat E-Mail-Benachrichtigung Tracker',
                'indexes': [models.Index(fields=['scheduled_send_at', 'notification_sent'], name='chat_chatem_schedul_291645_idx'), models.Index(fields=['user', 'notification_sent'], name='chat_chatem_user_id_9c1e15_idx')],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
