# Generated by Django 5.2.1 on 2025-07-09 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_system_message',
            field=models.BooleanField(default=False, help_text='Ist eine Systemnachricht'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name für anonyme Nachrichten', max_length=100),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_bug_report_room',
            field=models.BooleanField(default=False, help_text='Ist ein Bug-Meldungs-Chat-Raum'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
