# Generated by Django 5.2.1 on 2025-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name für anonyme Nachrichten', max_length=100, null=True),
        ),
    ]
