# Generated by Django 5.2.1 on 2025-07-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung'),
        ),
    ]
