# Generated by Django 5.2.1 on 2025-08-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionseooptimization',
            name='ai_model',
            field=models.CharField(choices=[('openai-gpt4', 'OpenAI GPT-4'), ('openai-gpt4o', 'OpenAI GPT-4o'), ('openai-gpt4o-mini', 'OpenAI GPT-4o Mini'), ('openai-gpt35', 'OpenAI GPT-3.5 Turbo')], default='openai-gpt4', max_length=50),
        ),
    ]
