# Generated by Django 5.2.1 on 2025-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0002_alter_collectionseooptimization_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyblogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Haupt-Bild URL', max_length=2048),
        ),
        migrations.AlterField(
            model_name='shopifycollection',
            name='image_url',
            field=models.URLField(blank=True, help_text='Kategorie-Bild URL', max_length=2048),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Haupt-Produktbild URL', max_length=2048),
        ),
        migrations.AlterField(
            model_name='shopifyproductimage',
            name='image_url',
            field=models.URLField(help_text='Bild URL', max_length=2048),
        ),
    ]
