# Generated by Django 5.2.1 on 2025-07-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0002_shopifystore_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom Domain (z.B. naturmacher.de)', max_length=200),
        ),
    ]
