# Generated by Django 5.2.1 on 2025-07-05 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0003_shopifystore_custom_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSEOOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Kommagetrennte Keywords für SEO-Optimierung')),
                ('ai_model', models.CharField(choices=[('openai-gpt4', 'OpenAI GPT-4'), ('openai-gpt35', 'OpenAI GPT-3.5 Turbo'), ('claude-3-sonnet', 'Claude 3 Sonnet'), ('claude-3-haiku', 'Claude 3 Haiku'), ('gemini-pro', 'Google Gemini Pro')], default='openai-gpt4', max_length=50)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('original_description', models.TextField(blank=True)),
                ('original_seo_title', models.CharField(blank=True, max_length=70)),
                ('original_seo_description', models.CharField(blank=True, max_length=160)),
                ('generated_seo_title', models.CharField(blank=True, max_length=70)),
                ('generated_seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_applied', models.BooleanField(default=False, help_text='Wurden die generierten SEO-Daten angewendet?')),
                ('ai_prompt_used', models.TextField(blank=True, help_text='Der verwendete AI-Prompt')),
                ('ai_response_raw', models.TextField(blank=True, help_text='Rohe AI-Antwort für Debug')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_optimizations', to='shopify_manager.shopifyproduct')),
            ],
            options={
                'verbose_name': 'SEO-Optimierung',
                'verbose_name_plural': 'SEO-Optimierungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
