# Generated by Django 5.2.1 on 2025-12-17 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0005_convert_additional_tables_to_utf8mb4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Produkt'), ('product_image', 'Produktbild'), ('blog', 'Blog'), ('blog_post', 'Blog-Beitrag'), ('blog_image', 'Blog-Bild'), ('collection', 'Collection'), ('order', 'Bestellung'), ('customer', 'Kunde'), ('page', 'Seite'), ('menu', 'Menü'), ('redirect', 'Weiterleitung'), ('metafield', 'Metafield'), ('discount', 'Rabattcode')], max_length=20)),
                ('shopify_id', models.BigIntegerField(help_text='Shopify ID des Elements')),
                ('title', models.CharField(help_text='Titel/Name für Anzeige', max_length=500)),
                ('raw_data', models.JSONField(help_text='Komplette API-Antwort als JSON')),
                ('image_data', models.BinaryField(blank=True, help_text='Optional: Bild als Blob', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Original Bild-URL', max_length=2048)),
                ('parent_id', models.BigIntegerField(blank=True, help_text='Parent ID z.B. Blog-ID für Posts', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backup-Element',
                'verbose_name_plural': 'Backup-Elemente',
                'ordering': ['item_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name des Backups z.B. 'Vollbackup 2025-01-15'", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('include_products', models.BooleanField(default=True, help_text='Produkte sichern')),
                ('include_product_images', models.BooleanField(default=False, help_text='Produktbilder herunterladen')),
                ('include_blogs', models.BooleanField(default=True, help_text='Blogs und Posts sichern')),
                ('include_blog_images', models.BooleanField(default=False, help_text='Blog-Bilder herunterladen')),
                ('include_collections', models.BooleanField(default=True, help_text='Collections sichern')),
                ('include_orders', models.BooleanField(default=False, help_text='Bestellungen sichern')),
                ('include_customers', models.BooleanField(default=False, help_text='Kundendaten sichern')),
                ('include_pages', models.BooleanField(default=True, help_text='Statische Seiten sichern')),
                ('include_menus', models.BooleanField(default=True, help_text='Navigationsmenüs sichern')),
                ('include_redirects', models.BooleanField(default=True, help_text='URL-Weiterleitungen sichern')),
                ('include_metafields', models.BooleanField(default=False, help_text='Metafields sichern')),
                ('include_discounts', models.BooleanField(default=False, help_text='Rabattcodes sichern')),
                ('products_count', models.IntegerField(default=0)),
                ('blogs_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('collections_count', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('customers_count', models.IntegerField(default=0)),
                ('pages_count', models.IntegerField(default=0)),
                ('menus_count', models.IntegerField(default=0)),
                ('redirects_count', models.IntegerField(default=0)),
                ('metafields_count', models.IntegerField(default=0)),
                ('discounts_count', models.IntegerField(default=0)),
                ('images_count', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='shopify_manager.shopifystore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopify Backup',
                'verbose_name_plural': 'Shopify Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Erfolgreich'), ('skipped', 'Übersprungen'), ('failed', 'Fehlgeschlagen'), ('exists', 'Existiert bereits')], max_length=20)),
                ('new_shopify_id', models.BigIntegerField(blank=True, help_text='Neue Shopify ID nach Wiederherstellung', null=True)),
                ('message', models.TextField(blank=True, help_text='Status-Nachricht oder Fehlerbeschreibung')),
                ('restored_at', models.DateTimeField(auto_now_add=True)),
                ('backup_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_logs', to='shopify_manager.backupitem')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_logs', to='shopify_manager.shopifybackup')),
            ],
            options={
                'verbose_name': 'Wiederherstellungs-Log',
                'verbose_name_plural': 'Wiederherstellungs-Logs',
                'ordering': ['-restored_at'],
            },
        ),
        migrations.AddField(
            model_name='backupitem',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopify_manager.shopifybackup'),
        ),
        migrations.AddIndex(
            model_name='backupitem',
            index=models.Index(fields=['backup', 'item_type'], name='shopify_man_backup__55a66b_idx'),
        ),
        migrations.AddIndex(
            model_name='backupitem',
            index=models.Index(fields=['shopify_id'], name='shopify_man_shopify_b2f970_idx'),
        ),
    ]
