# Generated by Django 5.2.1 on 2025-07-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0005_seoanalysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysynclog',
            name='action',
            field=models.CharField(choices=[('import', 'Import von Shopify'), ('export', 'Export zu Shopify'), ('update', 'Update zu Shopify'), ('sync_all', 'Alle Produkte synchronisieren'), ('import_blogs', 'Blogs importieren'), ('import_blog_posts', 'Blog-Posts importieren')], max_length=20),
        ),
        migrations.CreateModel(
            name='ShopifyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Blog ID', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Blog-Titel', max_length=255)),
                ('handle', models.CharField(help_text='URL Handle', max_length=255)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_shopify_data', models.JSONField(blank=True, default=dict)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='shopify_manager.shopifystore')),
            ],
            options={
                'verbose_name': 'Shopify Blog',
                'verbose_name_plural': 'Shopify Blogs',
                'ordering': ['-updated_at'],
                'unique_together': {('shopify_id', 'store')},
            },
        ),
        migrations.CreateModel(
            name='ShopifyBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Article ID', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Beitrag-Titel', max_length=255)),
                ('handle', models.CharField(help_text='URL Handle', max_length=255)),
                ('content', models.TextField(help_text='Beitrag-Inhalt (HTML)')),
                ('summary', models.TextField(blank=True, help_text='Zusammenfassung')),
                ('author', models.CharField(blank=True, help_text='Autor', max_length=255)),
                ('status', models.CharField(choices=[('published', 'Veröffentlicht'), ('draft', 'Entwurf'), ('hidden', 'Versteckt')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, help_text='SEO Titel (max. 70 Zeichen)', max_length=70)),
                ('seo_description', models.TextField(blank=True, help_text='SEO Beschreibung (max. 160 Zeichen)', max_length=160)),
                ('featured_image_url', models.URLField(blank=True, help_text='Haupt-Bild URL')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt-Text für Hauptbild', max_length=255)),
                ('tags', models.TextField(blank=True, help_text='Tags (kommagetrennt)')),
                ('published_at', models.DateTimeField(blank=True, help_text='Veröffentlichungsdatum', null=True)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_shopify_data', models.JSONField(blank=True, default=dict)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='shopify_manager.shopifyblog')),
            ],
            options={
                'verbose_name': 'Shopify Blog Post',
                'verbose_name_plural': 'Shopify Blog Posts',
                'ordering': ['-published_at', '-updated_at'],
                'unique_together': {('shopify_id', 'blog')},
            },
        ),
    ]
