# Generated by Django 5.2.1 on 2025-12-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0006_backup_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifybackup',
            name='current_step',
            field=models.CharField(blank=True, help_text='Aktueller Backup-Schritt', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifybackup',
            name='progress_message',
            field=models.CharField(blank=True, help_text='Aktuelle Fortschrittsnachricht', max_length=255),
        ),
    ]
