# Generated by Django 5.2.1 on 2025-12-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0007_backup_progress_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifybackup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
