# Generated by Django 5.2.1 on 2025-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0007_blogpostseooptimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyblogpost',
            name='is_grayed_out',
            field=models.BooleanField(default=False, help_text='Blog-Post ist ausgegraut nach SEO-Anwendung'),
        ),
    ]
