# Generated by Django 5.2.1 on 2025-07-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0008_add_is_grayed_out_to_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='is_grayed_out',
            field=models.BooleanField(default=False, help_text='Produkt ist ausgegraut/erledigt'),
        ),
    ]
