# Generated by Django 5.2.1 on 2025-12-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0008_backup_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifybackup',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20),
        ),
    ]
