# Generated by Django 5.2.1 on 2025-07-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0009_add_is_grayed_out_to_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyproduct',
            name='is_grayed_out',
        ),
    ]
