# Generated by Django 5.2.1 on 2025-12-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0009_add_paused_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupitem',
            name='image_data',
        ),
        migrations.AddField(
            model_name='backupitem',
            name='image_path',
            field=models.CharField(blank=True, help_text='Pfad zur Bilddatei relativ zu MEDIA_ROOT', max_length=500),
        ),
    ]
