# Generated by Django 5.2.1 on 2025-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0010_remove_is_grayed_out_from_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyblogpost',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyblogpost',
            name='needs_sync',
            field=models.BooleanField(default=False, help_text='Wurde lokal geändert und muss synchronisiert werden'),
        ),
        migrations.AddField(
            model_name='shopifyblogpost',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Letzter Sync-Fehler'),
        ),
    ]
