# Generated by Django 5.2.1 on 2025-07-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0011_add_sync_fields_to_blog_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyblogpost',
            name='is_grayed_out',
        ),
    ]
