# Generated by Django 5.2.1 on 2025-07-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0012_remove_grayout_functionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='shopify_id',
            field=models.CharField(help_text='Shopify Product ID', max_length=50),
        ),
    ]
