# Generated by Django 5.2.1 on 2025-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0013_alter_shopifyproduct_shopify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyblog',
            name='shopify_id',
            field=models.CharField(help_text='Shopify Blog ID', max_length=50),
        ),
    ]
