# Generated by Django 5.2.1 on 2025-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0014_alter_shopifyblog_shopify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyblogpost',
            name='shopify_id',
            field=models.CharField(help_text='Shopify Article ID', max_length=50),
        ),
    ]
