# Generated by Django 5.2.1 on 2025-07-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0015_alter_shopifyblogpost_shopify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('tiktok_ads', 'TikTok Ads'), ('other', 'Andere')], help_text='Werbeplattform', max_length=20)),
                ('campaign_name', models.CharField(help_text='Name der Kampagne', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Werbekosten', max_digits=10)),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Anzahl Klicks')),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Anzahl Impressionen')),
                ('conversions', models.PositiveIntegerField(default=0, help_text='Anzahl Conversions')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Umsatz aus Werbung', max_digits=10)),
                ('date', models.DateField(help_text='Datum der Werbemaßnahme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_costs', to='shopify_manager.shopifystore')),
            ],
            options={
                'verbose_name': 'Werbekosten',
                'verbose_name_plural': 'Werbekosten',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der laufenden Kosten', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Kosten')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kostenbetrag', max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monatlich'), ('yearly', 'Jährlich'), ('one_time', 'Einmalig')], default='monthly', max_length=20)),
                ('start_date', models.DateField(help_text='Startdatum der Kosten')),
                ('end_date', models.DateField(blank=True, help_text='Enddatum (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_costs', to='shopify_manager.shopifystore')),
            ],
            options={
                'verbose_name': 'Laufende Kosten',
                'verbose_name_plural': 'Laufende Kosten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name des Versandprofils', max_length=200)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Tatsächliche Versandkosten', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_profiles', to='shopify_manager.shopifystore')),
            ],
            options={
                'verbose_name': 'Versandprofil',
                'verbose_name_plural': 'Versandprofile',
                'unique_together': {('name', 'store')},
            },
        ),
        migrations.CreateModel(
            name='ProductShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_profile', to='shopify_manager.shopifyproduct')),
                ('shipping_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopify_manager.shippingprofile')),
            ],
            options={
                'verbose_name': 'Produkt-Versandprofil',
                'verbose_name_plural': 'Produkt-Versandprofile',
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.CharField(help_text='Shopify Order ID', max_length=50)),
                ('shopify_line_item_id', models.CharField(help_text='Shopify Line Item ID', max_length=50)),
                ('order_date', models.DateTimeField(help_text='Bestelldatum')),
                ('quantity', models.PositiveIntegerField(help_text='Verkaufte Menge')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Verkaufspreis pro Einheit', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Gesamtpreis', max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Einkaufspreis pro Einheit', max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Versandkosten', max_digits=10)),
                ('shopify_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Shopify Provision', max_digits=10)),
                ('paypal_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='PayPal Provision', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Mehrwertsteuer', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='shopify_manager.shopifyproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='shopify_manager.shopifystore')),
            ],
            options={
                'verbose_name': 'Verkaufsdaten',
                'verbose_name_plural': 'Verkaufsdaten',
                'ordering': ['-order_date'],
                'unique_together': {('shopify_order_id', 'shopify_line_item_id')},
            },
        ),
        migrations.CreateModel(
            name='SalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Datum der Statistik')),
                ('period_type', models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], default='daily', max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_shipping_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_shopify_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_paypal_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_ads_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_recurring_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_statistics', to='shopify_manager.shopifystore')),
            ],
            options={
                'verbose_name': 'Verkaufsstatistik',
                'verbose_name_plural': 'Verkaufsstatistiken',
                'ordering': ['-date'],
                'unique_together': {('store', 'date', 'period_type')},
            },
        ),
    ]
