# Generated by Django 5.2.1 on 2025-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0016_adscost_recurringcost_shippingprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='actual_shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tatsächliche Versandkosten (aus Versandprofil)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='payment_gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Payment Gateway Gebühren', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='shop_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Versandkosten die der Kunde bezahlt hat', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Einkaufspreis pro Einheit aus Shopify', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Versandkosten (Legacy - nutze shop_shipping_cost)', max_digits=10),
        ),
    ]
