# Generated by Django 5.2.1 on 2025-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0018_add_detailed_cost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Mehrwertsteuer', max_digits=10),
        ),
    ]
