# Generated by Django 5.2.1 on 2025-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0019_alter_salesdata_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='paypal_account_type',
            field=models.CharField(choices=[('standard', 'Standard Account'), ('business', 'Business Account'), ('handler', 'Handler Account')], default='standard', help_text='PayPal Account-Typ für Gebührenberechnung', max_length=20),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='paypal_handler_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text='Handler Account Fixgebühr (Standard: 0.35€)', max_digits=5),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='paypal_handler_rate',
            field=models.DecimalField(decimal_places=4, default=0.0199, help_text='Handler Account Gebührensatz (Standard: 1.99%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='paypal_monthly_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monatliches PayPal-Transaktionsvolumen für gestaffelte Gebühren', max_digits=12),
        ),
    ]
