# Generated by Django 5.2.1 on 2025-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0020_shopifystore_paypal_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Payment Gateway (z.B. paypal, shopify_payments, manual)', max_length=100),
        ),
    ]
