# Generated by Django 5.2.1 on 2025-07-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0021_add_payment_gateway_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='google_ads_client_id',
            field=models.CharField(blank=True, help_text='Google OAuth2 Client ID', max_length=100),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='google_ads_client_secret',
            field=models.CharField(blank=True, help_text='Google OAuth2 Client Secret', max_length=100),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='google_ads_customer_id',
            field=models.CharField(blank=True, help_text='Google Ads Customer ID (z.B. 123-456-7890)', max_length=20),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='google_ads_developer_token',
            field=models.CharField(blank=True, help_text='Google Ads Developer Token', max_length=100),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='google_ads_refresh_token',
            field=models.CharField(blank=True, help_text='Google Ads OAuth2 Refresh Token', max_length=200),
        ),
        migrations.CreateModel(
            name='GoogleAdsProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(help_text='Google Ads Campaign ID', max_length=100)),
                ('campaign_name', models.CharField(help_text='Campaign Name', max_length=200)),
                ('ad_group_id', models.CharField(blank=True, help_text='Ad Group ID', max_length=100, null=True)),
                ('ad_group_name', models.CharField(blank=True, help_text='Ad Group Name', max_length=200, null=True)),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Anzahl Impressionen')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Anzahl Klicks')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Werbekosten', max_digits=10)),
                ('conversions', models.DecimalField(decimal_places=2, default=0.0, help_text='Anzahl Conversions', max_digits=10)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Conversion Wert', max_digits=10)),
                ('date', models.DateField(help_text='Datum der Daten')),
                ('ctr', models.DecimalField(decimal_places=4, default=0.0, help_text='Click-Through-Rate', max_digits=6)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per Click', max_digits=8)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Conversion Rate', max_digits=6)),
                ('roas', models.DecimalField(decimal_places=2, default=0.0, help_text='Return on Ad Spend', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_data', to='shopify_manager.shopifyproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_product_data', to='shopify_manager.shopifystore')),
            ],
            options={
                'verbose_name': 'Google Ads Produktdaten',
                'verbose_name_plural': 'Google Ads Produktdaten',
                'ordering': ['-date'],
                'unique_together': {('store', 'product', 'campaign_id', 'date')},
            },
        ),
    ]
