# Generated by Django 5.2.1 on 2025-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0023_shopifycollection_collectionseooptimization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysynclog',
            name='action',
            field=models.CharField(choices=[('import', 'Import von Shopify'), ('export', 'Export zu Shopify'), ('update', 'Update zu Shopify'), ('sync_all', 'Alle Produkte synchronisieren'), ('import_blogs', 'Blogs importieren'), ('import_blog_posts', 'Blog-Posts importieren'), ('import_collections', 'Collections importieren')], max_length=20),
        ),
    ]
