# Generated by Django 5.2.1 on 2025-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0024_alter_shopifysynclog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycollection',
            name='collection_type',
            field=models.CharField(choices=[('custom', 'Custom Collection'), ('smart', 'Smart Collection')], default='custom', help_text='Typ der Collection (Custom oder Smart)', max_length=20),
        ),
    ]
