# Generated by Django 5.2.1 on 2025-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0025_add_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproductimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt-Text', max_length=255, null=True),
        ),
    ]
