# Generated by Django 5.2.1 on 2026-01-17 18:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255, verbose_name='Suchbegriff')),
                ('category', models.CharField(choices=[('forum', 'Forum'), ('directory', 'Verzeichnis'), ('guest_post', 'Gastbeitrag'), ('comment', 'Kommentar'), ('social', 'Social Media'), ('video', 'Video'), ('qa', 'Frage & Antwort'), ('profile', 'Profil'), ('wiki', 'Wiki'), ('news', 'News/Presse'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=5, verbose_name='Priorität (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Suchbegriff',
                'verbose_name_plural': 'Suchbegriffe',
                'ordering': ['-priority', 'query'],
            },
        ),
        migrations.CreateModel(
            name='BacklinkSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('sources_found', models.PositiveIntegerField(default=0, verbose_name='Gefundene Quellen')),
                ('new_sources', models.PositiveIntegerField(default=0, verbose_name='Neue Quellen')),
                ('updated_sources', models.PositiveIntegerField(default=0, verbose_name='Aktualisierte Quellen')),
                ('error_log', models.TextField(blank=True, verbose_name='Fehlerprotokoll')),
                ('progress_log', models.TextField(blank=True, verbose_name='Fortschrittsprotokoll')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backloom_searches', to=settings.AUTH_USER_MODEL, verbose_name='Ausgelöst von')),
            ],
            options={
                'verbose_name': 'Backlink-Suche',
                'verbose_name_plural': 'Backlink-Suchen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacklinkSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(verbose_name='URL')),
                ('url_hash', models.CharField(help_text='SHA256-Hash der URL für Duplikat-Erkennung', max_length=64, unique=True, verbose_name='URL-Hash')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Seitentitel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('favicon_url', models.URLField(blank=True, max_length=500, verbose_name='Favicon URL')),
                ('category', models.CharField(choices=[('forum', 'Forum'), ('directory', 'Verzeichnis'), ('guest_post', 'Gastbeitrag'), ('comment', 'Kommentar'), ('social', 'Social Media'), ('video', 'Video'), ('qa', 'Frage & Antwort'), ('profile', 'Profil'), ('wiki', 'Wiki'), ('news', 'News/Presse'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie')),
                ('source_type', models.CharField(choices=[('google', 'Google'), ('bing', 'Bing'), ('duckduckgo', 'DuckDuckGo'), ('ecosia', 'Ecosia'), ('yahoo', 'Yahoo'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('quora', 'Quora'), ('manual', 'Manuell')], default='google', max_length=20, verbose_name='Gefunden über')),
                ('quality_score', models.PositiveIntegerField(default=50, verbose_name='Qualitätsbewertung (0-100)')),
                ('domain_authority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Domain Authority')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Bearbeitet')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Backlink erstellt')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Abgelehnt/Ungeeignet')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('first_found', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstmals gefunden')),
                ('last_found', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zuletzt gefunden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('search_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_sources', to='backloom.searchquery', verbose_name='Suchbegriff')),
            ],
            options={
                'verbose_name': 'Backlink-Quelle',
                'verbose_name_plural': 'Backlink-Quellen',
                'ordering': ['-last_found'],
                'indexes': [models.Index(fields=['domain'], name='backloom_ba_domain_9455bb_idx'), models.Index(fields=['category'], name='backloom_ba_categor_e1f4e6_idx'), models.Index(fields=['is_processed'], name='backloom_ba_is_proc_f0b48a_idx'), models.Index(fields=['-last_found'], name='backloom_ba_last_fo_7c22d0_idx'), models.Index(fields=['-quality_score'], name='backloom_ba_quality_673a0f_idx'), models.Index(fields=['url_hash'], name='backloom_ba_url_has_a9b3e3_idx')],
            },
        ),
    ]
