# Generated by Django 5.2.1 on 2026-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backloom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlinksource',
            name='source_type',
            field=models.CharField(choices=[('google', 'Google'), ('bing', 'Bing'), ('duckduckgo', 'DuckDuckGo'), ('ecosia', 'Ecosia'), ('yahoo', 'Yahoo'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('quora', 'Quora'), ('manual', 'Manuell')], default='google', max_length=20, verbose_name='Gefunden über'),
        ),
    ]
