# Generated by Django 5.2.1 on 2026-05-04 11:43

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backloom', '0002_alter_backlinksource_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backlinksource',
            name='captcha_type',
            field=models.CharField(blank=True, default='', help_text='Wird beim ersten Bot-Lauf gesetzt (recaptcha_v2, hcaptcha, ...)', max_length=24, verbose_name='Erkannter Captcha-Typ'),
        ),
        migrations.AddField(
            model_name='backlinksource',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='LLM/Bot speichert hier Selektoren-Mapping für deterministisches Replay', verbose_name='Gelerntes Formular-Schema'),
        ),
        migrations.AddField(
            model_name='backlinksource',
            name='requires_account',
            field=models.BooleanField(blank=True, help_text='Null = unbekannt, True/False = nach erstem Lauf bekannt', null=True, verbose_name='Erfordert Account-Anlage?'),
        ),
        migrations.AddField(
            model_name='backlinksource',
            name='submission_blocked_until',
            field=models.DateTimeField(blank=True, help_text='Solange darf der Bot diese Source nicht erneut anfassen', null=True, verbose_name='Cooldown bis'),
        ),
        migrations.AlterField(
            model_name='backlinksource',
            name='source_type',
            field=models.CharField(choices=[('google', 'Google'), ('bing', 'Bing'), ('duckduckgo', 'DuckDuckGo'), ('ecosia', 'Ecosia'), ('yahoo', 'Yahoo'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('quora', 'Quora'), ('pinterest', 'Pinterest'), ('medium', 'Medium'), ('manual', 'Manuell')], default='google', max_length=20, verbose_name='Gefunden über'),
        ),
        migrations.CreateModel(
            name='NaturmacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=255, verbose_name='Firmenname')),
                ('inhaber', models.CharField(blank=True, max_length=255, verbose_name='Inhaber/Geschäftsführer')),
                ('vorname', models.CharField(blank=True, max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(blank=True, max_length=100, verbose_name='Nachname')),
                ('rechtsform', models.CharField(blank=True, help_text='z.B. GbR, GmbH, e.K., Einzelunternehmen', max_length=100, verbose_name='Rechtsform')),
                ('ust_id', models.CharField(blank=True, max_length=32, verbose_name='USt-ID')),
                ('handelsregister', models.CharField(blank=True, max_length=64, verbose_name='Handelsregister')),
                ('website', models.URLField(verbose_name='Website')),
                ('email', models.EmailField(max_length=254, verbose_name='Kontakt-E-Mail (für Registrierungen)')),
                ('email_shop', models.EmailField(blank=True, max_length=254, verbose_name='Shop-E-Mail (öffentlich)')),
                ('telefon', models.CharField(blank=True, max_length=64, verbose_name='Telefon')),
                ('strasse', models.CharField(blank=True, max_length=255, verbose_name='Straße + Hausnummer')),
                ('plz', models.CharField(blank=True, max_length=16, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=128, verbose_name='Ort')),
                ('land', models.CharField(default='Deutschland', max_length=64, verbose_name='Land')),
                ('kategorie', models.CharField(blank=True, help_text='z.B. "Shopping / Geschenke / Personalisiert"', max_length=255, verbose_name='Default-Kategorie')),
                ('keywords', models.TextField(blank=True, help_text='Komma-getrennt für Verzeichnisse', verbose_name='Keywords/Tags')),
                ('default_username', models.CharField(blank=True, help_text='Wird verwendet wenn Site nicht "Email als Username" akzeptiert', max_length=128, verbose_name='Standard-Username')),
                ('default_password', models.CharField(blank=True, max_length=255, verbose_name='Standard-Passwort')),
                ('imap_host', models.CharField(blank=True, default='imappro.zoho.eu', max_length=128, verbose_name='IMAP-Server')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='IMAP-Port (SSL)')),
                ('imap_username', models.CharField(blank=True, help_text='Wenn leer: profile.email', max_length=255, verbose_name='IMAP-Username (=Email)')),
                ('imap_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='App-Passwort von Zoho/etc. — niemals Account-Hauptpasswort verwenden', null=True, verbose_name='IMAP-Passwort')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backloom_profile', to=settings.AUTH_USER_MODEL, verbose_name='Workloom-User')),
            ],
            options={
                'verbose_name': 'Naturmacher-Profil',
                'verbose_name_plural': 'Naturmacher-Profile',
            },
        ),
        migrations.CreateModel(
            name='BioVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Bio-Text')),
                ('length_bucket', models.PositiveIntegerField(choices=[(160, 'Kurz (≤160)'), (300, 'Mittel (≤300)'), (500, 'Lang (≤500)')], default=300, verbose_name='Längen-Kategorie')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl Verwendungen')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt verwendet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_variants', to='backloom.naturmacherprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Bio-Variante',
                'verbose_name_plural': 'Bio-Varianten',
                'ordering': ['length_bucket', 'use_count', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'In Warteschlange'), ('running', 'Läuft'), ('needs_manual', 'Manuell eingreifen'), ('pending_verify', '🔍 Verifiziere Link'), ('success', '✅ Verifiziert (Backlink live)'), ('failed_captcha', 'Captcha-Fehler'), ('failed_other', 'Fehler'), ('failed_no_link', '❌ Kein Backlink gefunden'), ('already_registered', 'ℹ️ Bereits registriert'), ('skipped', 'Übersprungen')], default='queued', max_length=24, verbose_name='Status')),
                ('controlled_by', models.CharField(choices=[('bot', '🤖 Bot'), ('human', '👤 Mensch')], default='bot', help_text='Wer steuert gerade den Browser. BOT = Agent macht Schritte. HUMAN = User hat per Takeover die Steuerung uebernommen.', max_length=8, verbose_name='Aktive Steuerung')),
                ('control_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Steuerung uebernommen am')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet')),
                ('backlink_url', models.URLField(blank=True, max_length=600, verbose_name='Erstellter Backlink (URL der Profilseite)')),
                ('is_dofollow', models.BooleanField(blank=True, null=True, verbose_name='DoFollow?')),
                ('is_verified_live', models.BooleanField(blank=True, null=True, verbose_name='Verifiziert live?')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('container_id', models.CharField(blank=True, help_text='Für Live-View', max_length=64, verbose_name='Docker-Container-ID')),
                ('novnc_url', models.URLField(blank=True, max_length=400, verbose_name='noVNC Live-View URL')),
                ('anchor_text_used', models.CharField(blank=True, max_length=255, verbose_name='Anchor-Text')),
                ('step_log', models.JSONField(blank=True, default=list, help_text='Liste von {ts, msg, screenshot_url}', verbose_name='Schritt-Log')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('captcha_solver_used', models.CharField(blank=True, help_text='flaresolverr/buster/capsolver/2captcha/manual', max_length=32, verbose_name='Captcha-Solver')),
                ('cost_eur', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Kosten (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='backloom.biovariant', verbose_name='Verwendete Bio')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='backloom.naturmacherprofile', verbose_name='Profil')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_attempts', to='backloom.backlinksource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Submission-Attempt',
                'verbose_name_plural': 'Submission-Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='biovariant',
            index=models.Index(fields=['profile', 'length_bucket', 'is_active'], name='backloom_bi_profile_4bfa76_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattempt',
            index=models.Index(fields=['source', '-created_at'], name='backloom_su_source__3db65d_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattempt',
            index=models.Index(fields=['status'], name='backloom_su_status_8bdbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattempt',
            index=models.Index(fields=['-created_at'], name='backloom_su_created_f8a68a_idx'),
        ),
    ]
