# Generated by Django 5.2.1 on 2026-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magvis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magvissettings',
            name='text_model',
            field=models.CharField(default='glm-5.1', max_length=64),
        ),
        migrations.AddField(
            model_name='magvissettings',
            name='text_provider',
            field=models.CharField(default='zhipu', help_text='openai, anthropic, gemini, zhipu, deepseek, openrouter', max_length=32),
        ),
    ]
