# Generated by Django 5.2.1 on 2025-07-05 21:30

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_enable_ai_keyword_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='anthropic_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Anthropic API Key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='openai_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='OpenAI API Key'),
        ),
    ]
