# Generated by Django 5.2.1 on 2025-07-05 22:20

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Google API Key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='YouTube API Key'),
        ),
    ]
