# Generated by Django 5.2.1 on 2025-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pagesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablecontent',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Ob die Änderungen live geschaltet wurden', verbose_name='Veröffentlicht'),
        ),
    ]
