# Generated by Django 5.2.1 on 2025-07-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_google_api_key_customuser_youtube_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_info',
            field=models.TextField(blank=True, help_text='Beschreibung Ihres Unternehmens, Produkte, Zielgruppe, etc.', verbose_name='Firmeninformationen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_goals',
            field=models.TextField(blank=True, help_text='Ihre Standard-Lernziele für Schulungen', verbose_name='Standard-Lernziele'),
        ),
    ]
