# Generated by Django 5.2.1 on 2025-09-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_editablecontent_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_make_audio_calls',
            field=models.BooleanField(default=False, verbose_name='Darf Audioanrufe tätigen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_make_video_calls',
            field=models.BooleanField(default=False, verbose_name='Darf Videoanrufe tätigen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_receive_audio_calls',
            field=models.BooleanField(default=False, verbose_name='Darf Audioanrufe empfangen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_receive_video_calls',
            field=models.BooleanField(default=False, verbose_name='Darf Videoanrufe empfangen'),
        ),
    ]
