# Generated by Django 5.2.1 on 2025-09-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_disable_calls_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_chat_email_notifications',
            field=models.BooleanField(default=True, help_text='E-Mail erhalten bei ungelesenen Nachrichten nach 5 Minuten', verbose_name='Chat E-Mail-Benachrichtigungen'),
        ),
    ]
