# Generated by Django 5.2.1 on 2025-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bug_chat_superuser',
            field=models.BooleanField(default=False, help_text='Kann Bug-Chat-Nachrichten empfangen und Super User verwalten', verbose_name='Bug-Chat Super User'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_anonymous_reports',
            field=models.BooleanField(default=False, help_text='Erhält auch Bug-Meldungen ohne angemeldeten User', verbose_name='Anonyme Meldungen empfangen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_bug_reports',
            field=models.BooleanField(default=False, help_text='Erhält Bug-Meldungen über das Chat-System', verbose_name='Bug-Meldungen empfangen'),
        ),
    ]
