# Generated by Django 5.2.1 on 2025-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_bug_chat_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Letzte Aktivität'),
        ),
    ]
