# Generated by Django 5.2.1 on 2025-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_online_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_make_audio_calls',
            field=models.BooleanField(default=True, verbose_name='Darf Audioanrufe tätigen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_make_video_calls',
            field=models.BooleanField(default=True, verbose_name='Darf Videoanrufe tätigen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_receive_audio_calls',
            field=models.BooleanField(default=True, verbose_name='Darf Audioanrufe empfangen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_receive_video_calls',
            field=models.BooleanField(default=True, verbose_name='Darf Videoanrufe empfangen'),
        ),
    ]
