# Generated by Django 5.2.1 on 2025-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_apppermission_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablecontent',
            name='dom_selector',
            field=models.TextField(blank=True, default='', help_text='Original Selector aus dem Visual Editor für präzises Mapping', verbose_name='DOM Selector'),
        ),
    ]
