# Generated by Django 5.2.1 on 2025-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_editablecontent_dom_selector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dark_mode',
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('email_templates', 'Email-Vorlagen'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'AdsMake'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('loomconnect', 'LoomConnect'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('beleuchtungsrechner', 'Beleuchtungsrechner'), ('din_13201', 'DIN 13201-1 Straßenklassifizierung'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen')], max_length=50, unique=True, verbose_name='App/Funktion'),
        ),
        migrations.AlterField(
            model_name='userapppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('email_templates', 'Email-Vorlagen'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'AdsMake'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('loomconnect', 'LoomConnect'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('beleuchtungsrechner', 'Beleuchtungsrechner'), ('din_13201', 'DIN 13201-1 Straßenklassifizierung'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen')], max_length=50, verbose_name='App/Funktion'),
        ),
    ]
