# Generated by Django 5.2.1 on 2025-07-13 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_app_permissions',
            field=models.BooleanField(default=False, help_text='Erlaubt dem Benutzer das App-Freigabe Tab zu sehen und zu verwalten', verbose_name='Darf App-Freigaben verwalten'),
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen')], max_length=50, unique=True, verbose_name='App/Funktion')),
                ('access_level', models.CharField(choices=[('blocked', 'Gesperrt'), ('anonymous', 'Nicht angemeldete Besucher'), ('authenticated', 'Angemeldete Nutzer'), ('selected', 'Ausgewählte Nutzer')], default='blocked', max_length=20, verbose_name='Zugriffsebene')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_users', models.ManyToManyField(blank=True, help_text="Nur relevant wenn Zugriffsebene 'Ausgewählte Nutzer' ist", related_name='app_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Ausgewählte Nutzer')),
            ],
            options={
                'verbose_name': 'App-Berechtigung',
                'verbose_name_plural': 'App-Berechtigungen',
                'ordering': ['app_name'],
            },
        ),
    ]
