# Generated by Django 5.2.1 on 2025-07-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_can_manage_app_permissions_apppermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermission',
            name='hide_in_frontend',
            field=models.BooleanField(default=False, help_text='App wird in Navigation und UI nicht angezeigt, auch wenn zugänglich', verbose_name='Im Frontend ausblenden'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='superuser_bypass',
            field=models.BooleanField(default=True, help_text='Superuser haben unabhängig von den Einstellungen vollen Zugriff', verbose_name='Superuser können immer zugreifen'),
        ),
    ]
