# Generated by Django 5.2.1 on 2025-10-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_dark_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontent',
            name='content_key',
            field=models.CharField(help_text='Eindeutige Bezeichnung für diesen Inhalt', max_length=255, verbose_name='Inhalt Schlüssel'),
        ),
    ]
