# Generated by Django 5.2.1 on 2025-10-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_editablecontent_content_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontent',
            name='content_key',
            field=models.CharField(help_text='Eindeutige Bezeichnung für diesen Inhalt (DOM-Selektor kann sehr lang sein)', max_length=500, verbose_name='Inhalt Schlüssel'),
        ),
    ]
