# Generated by Django 5.2.1 on 2025-07-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_apppermission_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablecontent',
            name='ai_prompt',
            field=models.TextField(blank=True, help_text='Beschreibung für KI-generierte Inhalte', verbose_name='KI Prompt'),
        ),
        migrations.AddField(
            model_name='editablecontent',
            name='css_content',
            field=models.TextField(blank=True, verbose_name='CSS Styles'),
        ),
        migrations.AddField(
            model_name='editablecontent',
            name='html_content',
            field=models.TextField(blank=True, verbose_name='HTML Inhalt'),
        ),
        migrations.AlterField(
            model_name='editablecontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Bild'), ('hero_title', 'Hero Titel'), ('hero_subtitle', 'Hero Untertitel'), ('section_title', 'Bereich Titel'), ('section_text', 'Bereich Text'), ('button_text', 'Button Text'), ('testimonial', 'Kundenstimme'), ('html_block', 'HTML Block'), ('ai_generated', 'KI-generiert')], max_length=50, verbose_name='Inhaltstyp'),
        ),
    ]
