# Generated by Django 5.2.1 on 2025-12-03 14:45

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_ideogram_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gemini_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Gemini API Key'),
        ),
    ]
