# Generated by Django 5.2.1 on 2025-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_editablecontent_ai_prompt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editablecontent',
            options={'ordering': ['page', 'sort_order', 'created_at'], 'verbose_name': 'Bearbeitbarer Inhalt', 'verbose_name_plural': 'Bearbeitbare Inhalte'},
        ),
        migrations.AddField(
            model_name='editablecontent',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sortierreihenfolge'),
        ),
    ]
