# Generated by Django 5.2.1 on 2025-07-13 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_editablecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontent',
            name='page',
            field=models.CharField(max_length=50, verbose_name='Seite'),
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Technischer Name für die URL', max_length=50, verbose_name='Seiten-Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Anzeigename')),
                ('page_type', models.CharField(choices=[('landing', 'Landing Page'), ('about', 'Über uns'), ('services', 'Services/Leistungen'), ('contact', 'Kontakt'), ('blog', 'Blog/News'), ('gallery', 'Galerie'), ('custom', 'Benutzerdefiniert')], max_length=20, verbose_name='Seitentyp')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzerdefinierte Seite',
                'verbose_name_plural': 'Benutzerdefinierte Seiten',
                'ordering': ['display_name'],
                'unique_together': {('user', 'page_name')},
            },
        ),
    ]
