# Generated by Django 5.2.1 on 2025-12-05 06:44

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_gemini_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinterestAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Pinterest App ID')),
                ('app_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Pinterest App Secret')),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('refresh_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_scopes', models.TextField(blank=True, default='', help_text='Kommagetrennte Liste der autorisierten Scopes')),
                ('is_configured', models.BooleanField(default=False, verbose_name='Konfiguriert')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Verbunden')),
                ('pinterest_username', models.CharField(blank=True, max_length=100, verbose_name='Pinterest Benutzername')),
                ('last_test_success', models.DateTimeField(blank=True, null=True, verbose_name='Letzter erfolgreicher Test')),
                ('last_error', models.TextField(blank=True, verbose_name='Letzter Fehler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinterest_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinterest API Einstellung',
                'verbose_name_plural': 'Pinterest API Einstellungen',
            },
        ),
    ]
