# Generated by Django 5.2.1 on 2025-07-13 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_editablecontent_page_custompage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50, verbose_name='Seite')),
                ('seo_title', models.CharField(blank=True, help_text='Empfohlen: 50-60 Zeichen', max_length=60, verbose_name='SEO Titel')),
                ('seo_description', models.TextField(blank=True, help_text='Empfohlen: 150-160 Zeichen', max_length=160, verbose_name='SEO Beschreibung')),
                ('keywords', models.TextField(blank=True, help_text='Durch Kommas getrennt', verbose_name='Keywords')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('noindex', models.BooleanField(default=False, help_text='Seite von Suchmaschinen ausschließen', verbose_name='Noindex')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Einstellung',
                'verbose_name_plural': 'SEO Einstellungen',
                'unique_together': {('user', 'page')},
            },
        ),
    ]
