# Generated by Django 5.2.1 on 2025-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_upload_post_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upload_post_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Upload-Post User ID'),
        ),
    ]
