# Generated by Django 5.2.1 on 2025-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_upload_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upload_post_subreddits',
            field=models.TextField(blank=True, help_text='Komma-getrennte Liste von Subreddits (ohne r/)', null=True, verbose_name='Reddit Subreddits'),
        ),
    ]
