# Generated by Django 5.2.1 on 2025-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_apppermission_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('chat', 'Chat'), ('videos', 'Videos'), ('shopify_manager', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('naturmacher', 'Schulungen (Naturmacher)'), ('organization', 'Organisation'), ('todos', 'ToDos'), ('pdf_sucher', 'PDF-Suche'), ('amortization_calculator', 'Wirtschaftlichkeitsrechner'), ('sportplatzApp', 'Sportplatz-Konfigurator'), ('bug_report', 'Bug Report'), ('payments', 'Zahlungen & Abos'), ('video_upload', 'Video Upload'), ('video_sharing', 'Video Sharing'), ('ai_features', 'KI-Features'), ('premium_support', 'Premium Support'), ('advanced_analytics', 'Erweiterte Analytik')], max_length=50, unique=True, verbose_name='App/Feature')),
                ('subscription_required', models.CharField(choices=[('free', 'Kostenlos verfügbar'), ('any_paid', 'Beliebiges bezahltes Abo erforderlich'), ('founder_access', "Founder's Early Access erforderlich"), ('storage_plan', 'Storage-Plan erforderlich'), ('blocked', 'Komplett gesperrt')], default='free', max_length=20, verbose_name='Erforderliches Abonnement')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('show_upgrade_prompt', models.BooleanField(default=True, verbose_name='Upgrade-Hinweis anzeigen')),
                ('upgrade_message', models.TextField(blank=True, help_text='Benutzerdefinierte Nachricht für Upgrade-Prompt', verbose_name='Upgrade-Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature-Zugriff',
                'verbose_name_plural': 'Feature-Zugriffe',
                'ordering': ['app_name'],
            },
        ),
    ]
