# Generated by Django 5.2.1 on 2025-07-23 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_schuch_dashboard_to_apppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='App/Feature Name')),
                ('url_path', models.CharField(max_length=255, verbose_name='URL Pfad')),
                ('session_start', models.DateTimeField(auto_now_add=True, verbose_name='Session Start')),
                ('session_end', models.DateTimeField(blank=True, null=True, verbose_name='Session Ende')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Dauer in Sekunden')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer URL')),
                ('is_active_session', models.BooleanField(default=True, verbose_name='Aktive Session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App-Nutzungs-Tracking',
                'verbose_name_plural': 'App-Nutzungs-Trackings',
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['user', 'app_name', 'session_start'], name='accounts_ap_user_id_fc532d_idx'), models.Index(fields=['session_start'], name='accounts_ap_session_2603f9_idx'), models.Index(fields=['is_active_session'], name='accounts_ap_is_acti_da2335_idx')],
            },
        ),
    ]
