# Generated by Django 5.2.1 on 2026-02-01 00:00

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_google_search_api_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='google_search_api_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_search_cx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bing_search_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Bing Search API Key'),
        ),
    ]
