# Generated by Django 5.2.1 on 2025-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_app_usage_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusagetracking',
            name='activity_type',
            field=models.CharField(choices=[('app_usage', 'App-Nutzung'), ('video_call', 'Videoanruf'), ('audio_call', 'Audioanruf'), ('screen_share', 'Bildschirmfreigabe'), ('file_upload', 'Datei-Upload'), ('chat_message', 'Chat-Nachricht')], default='app_usage', max_length=20, verbose_name='Aktivitätstyp'),
        ),
        migrations.AddField(
            model_name='appusagetracking',
            name='call_participants',
            field=models.JSONField(blank=True, default=list, verbose_name='Anruf-Teilnehmer'),
        ),
        migrations.AddField(
            model_name='appusagetracking',
            name='call_quality_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anruf-Qualitätsbewertung (1-5)'),
        ),
        migrations.AddField(
            model_name='appusagetracking',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Zusätzliche Daten'),
        ),
    ]
