# Generated by Django 5.2.1 on 2026-02-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_replace_google_with_bing_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bing_search_api_key',
        ),
    ]
