# Generated by Django 5.2.1 on 2025-07-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_extend_app_usage_tracking_for_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccess',
            name='subscription_required',
            field=models.CharField(choices=[('free', 'Kostenlos verfügbar'), ('any_paid', 'Beliebiges bezahltes Abo erforderlich'), ('founder_access', "Founder's Early Access erforderlich"), ('storage_plan', 'Storage-Plan erforderlich'), ('in_development', 'In Entwicklung'), ('blocked', 'Komplett gesperrt')], default='free', max_length=20, verbose_name='Erforderliches Abonnement'),
        ),
    ]
