# Generated by Django 5.2.1 on 2025-07-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_featureaccess_subscription_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('chat', 'Chat'), ('videos', 'Videos'), ('shopify_manager', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('naturmacher', 'Schulungen (Naturmacher)'), ('organization', 'Organisation'), ('todos', 'ToDos'), ('pdf_sucher', 'PDF-Suche'), ('amortization_calculator', 'Wirtschaftlichkeitsrechner'), ('sportplatzApp', 'Sportplatz-Konfigurator'), ('bug_report', 'Bug Report'), ('payments', 'Zahlungen & Abos'), ('core', 'Schuch (Startseite/Kern)')], max_length=50, unique=True, verbose_name='App/Feature')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('short_description', models.CharField(max_length=300, verbose_name='Kurzbeschreibung')),
                ('detailed_description', models.TextField(verbose_name='Detaillierte Beschreibung')),
                ('key_features', models.JSONField(default=list, help_text='Liste der wichtigsten Features als JSON Array', verbose_name='Hauptfunktionen')),
                ('subscription_requirements', models.TextField(blank=True, verbose_name='Abo-Anforderungen')),
                ('technical_requirements', models.TextField(blank=True, verbose_name='Technische Anforderungen')),
                ('icon_class', models.CharField(default='bi bi-app', max_length=100, verbose_name='Icon CSS Klasse')),
                ('screenshot_url', models.URLField(blank=True, verbose_name='Screenshot URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('development_status', models.CharField(choices=[('development', 'In Entwicklung'), ('beta', 'Beta'), ('stable', 'Stabil'), ('deprecated', 'Veraltet')], default='stable', max_length=50, verbose_name='Entwicklungsstatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'App Information',
                'verbose_name_plural': 'App Informationen',
                'ordering': ['title'],
            },
        ),
    ]
