# Generated by Django 5.2.1 on 2026-02-12 14:29

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0028_alter_appinfo_app_name_alter_apppermission_app_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bing_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True, verbose_name="Bing Search API Key"
            ),
        ),
    ]
