# Generated by Django 5.2.1 on 2025-07-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_appinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='access_level',
            field=models.CharField(choices=[('blocked', 'Gesperrt'), ('anonymous', 'Nicht angemeldete Besucher'), ('authenticated', 'Angemeldete Nutzer'), ('selected', 'Ausgewählte Nutzer'), ('in_development', 'In Entwicklung')], default='blocked', max_length=20, verbose_name='Zugriffsebene'),
        ),
    ]
