# Generated by Django 5.2.1 on 2025-07-24 12:44

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_apppermission_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Zoho Client ID')),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Zoho Client Secret')),
                ('redirect_uri', models.URLField(blank=True, verbose_name='Redirect URI')),
                ('region', models.CharField(choices=[('US', 'US'), ('EU', 'EU'), ('IN', 'India'), ('AU', 'Australia')], default='EU', max_length=5, verbose_name='Zoho Region')),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('refresh_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_configured', models.BooleanField(default=False, verbose_name='Konfiguriert')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_test_success', models.DateTimeField(blank=True, null=True, verbose_name='Letzter erfolgreicher Test')),
                ('last_error', models.TextField(blank=True, verbose_name='Letzter Fehler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_mail_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zoho Mail API Einstellung',
                'verbose_name_plural': 'Zoho Mail API Einstellungen',
            },
        ),
    ]
