# Generated by Django 5.2.1 on 2026-02-24 14:21

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_brave_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deepseek_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='DeepSeek API Key'),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('email_templates', 'Email-Vorlagen'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'AdsMake'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('loomconnect', 'LoomConnect'), ('linkloom', 'LinkLoom'), ('myprompter', 'MyPrompter'), ('android_apk_manager', 'APK Manager'), ('desktop_app_manager', 'Desktop App Manager'), ('keyengine', 'KeyEngine'), ('ideopin', 'IdeoPin - Pinterest Generator'), ('imageforge', 'ImageForge - KI Bildgenerierung'), ('vskript', 'VSkript - Video-Skript Generator'), ('questionfinder', 'QuestionFinder'), ('ploom', 'P-Loom - Shopify Produkt-Erstellung'), ('backloom', 'BackLoom - Feed Management'), ('loommarket', 'LoomMarket - Business Marketing'), ('loomtalk', 'LoomTalk - Forum'), ('learnloom', 'LearnLoom - PDF-Bibliothek'), ('seo_dashboard', 'SEO Dashboard'), ('loomline', 'LoomLine - SEO Task Timeline'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('beleuchtungsrechner', 'Beleuchtungsrechner'), ('din_13201', 'DIN 13201-1 Klassifizierung'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_kategorien', 'Shopify - Kategorien'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_stores', 'Shopify - Stores'), ('shopify_backups', 'Shopify - Backups'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('blogprep', 'BlogPrep - Blog-Vorbereitung'), ('shopify_uploads', 'Shopify - Fotogravur Uploads'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen'), ('stats', 'Statistiken Dashboard'), ('superconfig', 'SuperConfig - Systemkonfiguration'), ('visual_editor', 'Visual Editor'), ('loomads', 'LoomAds - Werbung')], max_length=50, unique=True, verbose_name='App/Funktion'),
        ),
        migrations.AlterField(
            model_name='userapppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('email_templates', 'Email-Vorlagen'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'AdsMake'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('loomconnect', 'LoomConnect'), ('linkloom', 'LinkLoom'), ('myprompter', 'MyPrompter'), ('android_apk_manager', 'APK Manager'), ('desktop_app_manager', 'Desktop App Manager'), ('keyengine', 'KeyEngine'), ('ideopin', 'IdeoPin - Pinterest Generator'), ('imageforge', 'ImageForge - KI Bildgenerierung'), ('vskript', 'VSkript - Video-Skript Generator'), ('questionfinder', 'QuestionFinder'), ('ploom', 'P-Loom - Shopify Produkt-Erstellung'), ('backloom', 'BackLoom - Feed Management'), ('loommarket', 'LoomMarket - Business Marketing'), ('loomtalk', 'LoomTalk - Forum'), ('learnloom', 'LearnLoom - PDF-Bibliothek'), ('seo_dashboard', 'SEO Dashboard'), ('loomline', 'LoomLine - SEO Task Timeline'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('beleuchtungsrechner', 'Beleuchtungsrechner'), ('din_13201', 'DIN 13201-1 Klassifizierung'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_kategorien', 'Shopify - Kategorien'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_stores', 'Shopify - Stores'), ('shopify_backups', 'Shopify - Backups'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('blogprep', 'BlogPrep - Blog-Vorbereitung'), ('shopify_uploads', 'Shopify - Fotogravur Uploads'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen'), ('stats', 'Statistiken Dashboard'), ('superconfig', 'SuperConfig - Systemkonfiguration'), ('visual_editor', 'Visual Editor'), ('loomads', 'LoomAds - Werbung')], max_length=50, verbose_name='App/Funktion'),
        ),
    ]
