# Generated by Django 5.2.1 on 2025-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_zohoapisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='app_name',
            field=models.CharField(choices=[('chat', 'Chat'), ('videos', 'Videos'), ('mail', 'Email'), ('shopify_manager', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('naturmacher', 'Schulungen (Naturmacher)'), ('organization', 'Organisation'), ('todos', 'ToDos'), ('pdf_sucher', 'PDF-Suche'), ('amortization_calculator', 'Wirtschaftlichkeitsrechner'), ('sportplatzApp', 'Sportplatz-Konfigurator'), ('bug_report', 'Bug Report'), ('payments', 'Zahlungen & Abos'), ('core', 'Schuch (Startseite/Kern)')], max_length=50, unique=True, verbose_name='App/Feature'),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen')], max_length=50, unique=True, verbose_name='App/Funktion'),
        ),
        migrations.AlterField(
            model_name='featureaccess',
            name='app_name',
            field=models.CharField(choices=[('chat', 'Chat'), ('videos', 'Videos'), ('mail', 'Email'), ('shopify_manager', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('naturmacher', 'Schulungen (Naturmacher)'), ('organization', 'Organisation'), ('todos', 'ToDos'), ('pdf_sucher', 'PDF-Suche'), ('amortization_calculator', 'Wirtschaftlichkeitsrechner'), ('sportplatzApp', 'Sportplatz-Konfigurator'), ('bug_report', 'Bug Report'), ('payments', 'Zahlungen & Abos'), ('core', 'Schuch (Startseite/Kern)'), ('video_upload', 'Video Upload'), ('video_sharing', 'Video Sharing'), ('ai_features', 'KI-Features'), ('premium_support', 'Premium Support'), ('advanced_analytics', 'Erweiterte Analytik')], max_length=50, unique=True, verbose_name='App/Feature'),
        ),
    ]
