# Generated by Django 5.2.1 on 2025-07-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_appinfo_app_name_alter_apppermission_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_openai_model',
            field=models.CharField(
                choices=[
                    ('gpt-4o', 'GPT-4o (Premium)'),
                    ('gpt-4o-mini', 'GPT-4o Mini (Standard)'),
                    ('gpt-4-turbo', 'GPT-4 Turbo'),
                    ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Günstig)'),
                ],
                default='gpt-4o-mini',
                max_length=50,
                verbose_name='Bevorzugtes OpenAI Modell'
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_anthropic_model',
            field=models.CharField(
                choices=[
                    ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet (Premium)'),
                    ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku (Schnell)'),
                    ('claude-3-opus-20240229', 'Claude 3 Opus (Top-Tier)'),
                    ('claude-3-sonnet-20240229', 'Claude 3 Sonnet (Standard)'),
                    ('claude-3-haiku-20240307', 'Claude 3 Haiku (Günstig)'),
                ],
                default='claude-3-5-sonnet-20241022',
                max_length=50,
                verbose_name='Bevorzugtes Anthropic Modell'
            ),
        ),
    ]
