# Generated by Django 5.2.1 on 2025-07-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20250728_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('somi_plan', 'SoMi-Plan'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen')], max_length=50, unique=True, verbose_name='App/Funktion'),
        ),
        migrations.CreateModel(
            name='UserAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('somi_plan', 'SoMi-Plan'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen')], max_length=50, verbose_name='App/Funktion')),
                ('override_type', models.CharField(choices=[('allow', 'Explizit erlauben'), ('deny', 'Explizit verweigern')], max_length=10, verbose_name='Überschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_app_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Individuelle App-Berechtigung',
                'verbose_name_plural': 'Individuelle App-Berechtigungen',
                'ordering': ['user__username', 'app_name'],
                'unique_together': {('user', 'app_name')},
            },
        ),
    ]
