# Generated by Django 5.2.1 on 2026-03-28 20:09

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_add_pexels_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kie_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='KIE.ai API Key'),
        ),
    ]
