# Generated by Django 5.2.1 on 2025-07-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='desktop_view',
            field=models.BooleanField(default=False, help_text='Zeigt immer die Desktop-Version an, unabhängig vom Gerät', verbose_name='Desktop-Ansicht erzwingen'),
        ),
    ]
