# Generated by Django 5.2.1 on 2026-04-21 11:18

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_apppermission_app_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='kie_api_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pexels_api_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nvidia_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='NVIDIA NIM API Key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='openrouter_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='OpenRouter API Key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zhipu_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Zhipu / GLM API Key'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='app_name',
            field=models.CharField(choices=[('chat', 'Chat'), ('videos', 'Videos'), ('mail', 'Email'), ('shopify_manager', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('naturmacher', 'Schulungen (Naturmacher)'), ('organization', 'Organisation'), ('todos', 'ToDos'), ('pdf_sucher', 'PDF-Suche'), ('amortization_calculator', 'Wirtschaftlichkeitsrechner'), ('sportplatzApp', 'Sportplatz-Konfigurator'), ('bug_report', 'Bug Report'), ('payments', 'Zahlungen & Abos'), ('core', 'Schuch (Startseite/Kern)'), ('loomline', 'LoomLine - SEO Task Timeline'), ('keyengine', 'KeyEngine - Keyword Research'), ('loomconnect', 'LoomConnect - Videocalls'), ('linkloom', 'LinkLoom - Link in Bio'), ('ideopin', 'IdeoPin - Pinterest Generator'), ('imageforge', 'ImageForge - KI Bildgenerierung'), ('vskript', 'VSkript - Video-Skript Generator'), ('questionfinder', 'QuestionFinder'), ('streamrec', 'StreamRec - Kamera-Aufnahmen'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('myprompter', 'MyPrompter'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'MakeAds'), ('loomads', 'LoomAds'), ('blogprep', 'BlogPrep - Blog-Vorbereitung'), ('email_templates', 'Email-Vorlagen'), ('codelib', 'CodeLib - Code-Bibliothek'), ('stats', 'Statistiken'), ('lighting_tools', 'Beleuchtungsrechner'), ('lighting_classification', 'DIN 13201-1 Klassifizierung'), ('shopify_uploads', 'Shopify - Fotogravur Uploads'), ('ploom', 'P-Loom - Shopify Produkt-Erstellung'), ('backloom', 'BackLoom - Feed Management'), ('loommarket', 'LoomMarket - Business Marketing'), ('loomtalk', 'LoomTalk - Forum')], max_length=50, unique=True, verbose_name='App/Feature'),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('email_templates', 'Email-Vorlagen'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'AdsMake'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('loomconnect', 'LoomConnect'), ('linkloom', 'LinkLoom'), ('myprompter', 'MyPrompter'), ('android_apk_manager', 'APK Manager'), ('desktop_app_manager', 'Desktop App Manager'), ('keyengine', 'KeyEngine'), ('ideopin', 'IdeoPin - Pinterest Generator'), ('imageforge', 'ImageForge - KI Bildgenerierung'), ('vskript', 'VSkript - Video-Skript Generator'), ('questionfinder', 'QuestionFinder'), ('ploom', 'P-Loom - Shopify Produkt-Erstellung'), ('backloom', 'BackLoom - Feed Management'), ('loommarket', 'LoomMarket - Business Marketing'), ('loomtalk', 'LoomTalk - Forum'), ('learnloom', 'LearnLoom - PDF-Bibliothek'), ('seo_dashboard', 'SEO Dashboard'), ('loomline', 'LoomLine - SEO Task Timeline'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('beleuchtungsrechner', 'Beleuchtungsrechner'), ('din_13201', 'DIN 13201-1 Klassifizierung'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_kategorien', 'Shopify - Kategorien'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_stores', 'Shopify - Stores'), ('shopify_backups', 'Shopify - Backups'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('blogprep', 'BlogPrep - Blog-Vorbereitung'), ('shopify_uploads', 'Shopify - Fotogravur Uploads'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen'), ('stats', 'Statistiken Dashboard'), ('superconfig', 'SuperConfig - Systemkonfiguration'), ('visual_editor', 'Visual Editor'), ('loomads', 'LoomAds - Werbung')], max_length=50, unique=True, verbose_name='App/Funktion'),
        ),
        migrations.AlterField(
            model_name='featureaccess',
            name='app_name',
            field=models.CharField(choices=[('chat', 'Chat'), ('videos', 'Videos'), ('mail', 'Email'), ('shopify_manager', 'Shopify Manager'), ('image_editor', 'Bild Editor'), ('naturmacher', 'Schulungen (Naturmacher)'), ('organization', 'Organisation'), ('todos', 'ToDos'), ('pdf_sucher', 'PDF-Suche'), ('amortization_calculator', 'Wirtschaftlichkeitsrechner'), ('sportplatzApp', 'Sportplatz-Konfigurator'), ('bug_report', 'Bug Report'), ('payments', 'Zahlungen & Abos'), ('core', 'Schuch (Startseite/Kern)'), ('keyengine', 'KeyEngine - Keyword Research'), ('loomconnect', 'LoomConnect - Videocalls'), ('ideopin', 'IdeoPin - Pinterest Generator'), ('imageforge', 'ImageForge - KI Bildgenerierung'), ('vskript', 'VSkript - Video-Skript Generator'), ('questionfinder', 'QuestionFinder'), ('streamrec', 'StreamRec - Kamera-Aufnahmen'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('myprompter', 'MyPrompter'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'MakeAds'), ('loomline', 'LoomLine - SEO Task Timeline'), ('loomads', 'LoomAds'), ('blogprep', 'BlogPrep - Blog-Vorbereitung'), ('email_templates', 'Email-Vorlagen'), ('codelib', 'CodeLib - Code-Bibliothek'), ('stats', 'Statistiken'), ('lighting_tools', 'Beleuchtungsrechner'), ('lighting_classification', 'DIN 13201-1 Klassifizierung'), ('shopify_uploads', 'Shopify - Fotogravur Uploads'), ('linkloom', 'LinkLoom - Link in Bio'), ('ploom', 'P-Loom - Shopify Produkt-Erstellung'), ('backloom', 'BackLoom - Feed Management'), ('loommarket', 'LoomMarket - Business Marketing'), ('loomtalk', 'LoomTalk - Forum'), ('video_upload', 'Video Upload'), ('video_sharing', 'Video Sharing'), ('ai_features', 'KI-Features'), ('premium_support', 'Premium Support'), ('advanced_analytics', 'Erweiterte Analytik')], max_length=50, unique=True, verbose_name='App/Feature'),
        ),
        migrations.AlterField(
            model_name='userapppermission',
            name='app_name',
            field=models.CharField(choices=[('schulungen', 'Schulungen'), ('shopify', 'Shopify'), ('bilder', 'Bilder'), ('todos', 'ToDos'), ('chat', 'Chat'), ('organisation', 'Organisation'), ('editor', 'Editor'), ('videos', 'Videos'), ('mail', 'Email'), ('email_templates', 'Email-Vorlagen'), ('somi_plan', 'SoMi-Plan'), ('makeads', 'AdsMake'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('fileshare', 'FileShare'), ('loomconnect', 'LoomConnect'), ('linkloom', 'LinkLoom'), ('myprompter', 'MyPrompter'), ('android_apk_manager', 'APK Manager'), ('desktop_app_manager', 'Desktop App Manager'), ('keyengine', 'KeyEngine'), ('ideopin', 'IdeoPin - Pinterest Generator'), ('imageforge', 'ImageForge - KI Bildgenerierung'), ('vskript', 'VSkript - Video-Skript Generator'), ('questionfinder', 'QuestionFinder'), ('ploom', 'P-Loom - Shopify Produkt-Erstellung'), ('backloom', 'BackLoom - Feed Management'), ('loommarket', 'LoomMarket - Business Marketing'), ('loomtalk', 'LoomTalk - Forum'), ('learnloom', 'LearnLoom - PDF-Bibliothek'), ('seo_dashboard', 'SEO Dashboard'), ('loomline', 'LoomLine - SEO Task Timeline'), ('schuch', 'Schuch'), ('schuch_dashboard', 'Schuch Dashboard'), ('wirtschaftlichkeitsrechner', 'Wirtschaftlichkeitsrechner'), ('beleuchtungsrechner', 'Beleuchtungsrechner'), ('din_13201', 'DIN 13201-1 Klassifizierung'), ('sportplatz_konfigurator', 'Sportplatz-Konfigurator'), ('pdf_suche', 'PDF-Suche'), ('ki_zusammenfassung', 'KI-Zusammenfassung'), ('shopify_produkte', 'Shopify - Produkte'), ('shopify_kategorien', 'Shopify - Kategorien'), ('shopify_blogs', 'Shopify - Blogs'), ('shopify_stores', 'Shopify - Stores'), ('shopify_backups', 'Shopify - Backups'), ('shopify_seo_dashboard', 'Shopify - SEO Dashboard'), ('shopify_verkaufszahlen', 'Shopify - Verkaufszahlen'), ('shopify_seo_optimierung', 'Shopify - SEO-Optimierung'), ('shopify_alt_text', 'Shopify - Alt-Text Manager'), ('blogprep', 'BlogPrep - Blog-Vorbereitung'), ('shopify_uploads', 'Shopify - Fotogravur Uploads'), ('organisation_notizen', 'Organisation - Notizen'), ('organisation_termine', 'Organisation - Termine'), ('organisation_ideenboards', 'Organisation - Ideenboards'), ('organisation_terminanfragen', 'Organisation - Ausstehende Terminanfragen'), ('stats', 'Statistiken Dashboard'), ('superconfig', 'SuperConfig - Systemkonfiguration'), ('visual_editor', 'Visual Editor'), ('loomads', 'LoomAds - Werbung')], max_length=50, verbose_name='App/Funktion'),
        ),
    ]
