# Generated by Django 5.2.1 on 2026-04-23 09:29

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_customuser_kie_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pexels_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Pexels API Key'),
        ),
    ]
