# Generated by Django 5.2.1 on 2026-05-02 15:23

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_appinfo_app_name_alter_apppermission_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_account_email',
            field=models.CharField(blank=True, help_text='Wird automatisch beim OAuth-Connect gesetzt.', max_length=255, null=True, verbose_name='Verbundener Google-Account'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_oauth_credentials',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='refresh_token + access_token + scopes — wird im Hintergrund verwaltet.', null=True, verbose_name='Google OAuth Token (verschlüsselt JSON)'),
        ),
    ]
