# Generated by Django 5.2.1 on 2025-12-03 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Keywords kommagetrennt oder einzeln', verbose_name='Keywords')),
                ('overlay_text', models.CharField(blank=True, help_text='Catchy Pin-Text für das Bild', max_length=200, verbose_name='Overlay-Text')),
                ('overlay_text_ai_generated', models.BooleanField(default=False)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='ideopin/products/', verbose_name='Produktbild')),
                ('background_description', models.TextField(blank=True, help_text='Beschreibung für Hintergrund-Generierung via Ideogram', verbose_name='Hintergrund-Beschreibung')),
                ('pin_format', models.CharField(choices=[('1000x1500', 'Pinterest Standard (1000x1500)'), ('1000x1000', 'Quadratisch (1000x1000)'), ('1080x1920', 'Story Format (1080x1920)'), ('600x900', 'Kompakt (600x900)')], default='1000x1500', max_length=20, verbose_name='Pin-Format')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='ideopin/generated/', verbose_name='Generiertes Bild')),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='ideopin/final/', verbose_name='Finales Bild mit Text')),
                ('pin_url', models.URLField(blank=True, help_text='Zielseite des Pinterest Pins', verbose_name='Pin-Link')),
                ('seo_description', models.TextField(blank=True, help_text='Pinterest-optimierte Beschreibung (max. 500 Zeichen)', max_length=500, verbose_name='SEO Pin-Beschreibung')),
                ('seo_description_ai_generated', models.BooleanField(default=False)),
                ('text_font', models.CharField(blank=True, default='Arial', max_length=100, verbose_name='Schriftart')),
                ('text_size', models.IntegerField(default=48, verbose_name='Schriftgröße')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Textfarbe')),
                ('text_position', models.CharField(choices=[('top', 'Oben'), ('center', 'Mitte'), ('bottom', 'Unten')], default='center', max_length=20, verbose_name='Text-Position')),
                ('text_background_color', models.CharField(blank=True, help_text='Hex-Color oder leer für transparent', max_length=7, verbose_name='Hintergrundfarbe')),
                ('text_background_opacity', models.FloatField(default=0.7, verbose_name='Hintergrund-Transparenz')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('step1', 'Keywords eingegeben'), ('step2', 'Text generiert'), ('step3', 'Bild erstellt'), ('step4', 'Link eingegeben'), ('step5', 'SEO erstellt'), ('completed', 'Fertig')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pin Projekt',
                'verbose_name_plural': 'Pin Projekte',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_font', models.CharField(default='Arial', max_length=100, verbose_name='Standard-Schriftart')),
                ('default_text_size', models.IntegerField(default=48, verbose_name='Standard-Schriftgröße')),
                ('default_text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Standard-Textfarbe')),
                ('default_text_position', models.CharField(choices=[('top', 'Oben'), ('center', 'Mitte'), ('bottom', 'Unten')], default='center', max_length=20, verbose_name='Standard-Position')),
                ('default_text_background_color', models.CharField(default='#000000', max_length=7, verbose_name='Standard-Hintergrundfarbe')),
                ('default_text_background_opacity', models.FloatField(default=0.7, verbose_name='Standard-Transparenz')),
                ('default_pin_format', models.CharField(choices=[('1000x1500', 'Pinterest Standard (1000x1500)'), ('1000x1000', 'Quadratisch (1000x1000)'), ('1080x1920', 'Story Format (1080x1920)'), ('600x900', 'Kompakt (600x900)')], default='1000x1500', max_length=20, verbose_name='Standard-Format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pin Einstellung',
                'verbose_name_plural': 'Pin Einstellungen',
            },
        ),
    ]
