# Generated by Django 5.2.1 on 2025-12-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinproject',
            name='text_integration_mode',
            field=models.CharField(choices=[('ideogram', 'Von Ideogram ins Bild integrieren'), ('pil', 'Nachträglich mit PIL hinzufügen'), ('none', 'Kein Text-Overlay')], default='ideogram', help_text='Wie soll der Text ins Bild integriert werden?', max_length=20, verbose_name='Text-Integration'),
        ),
    ]
