# Generated by Django 5.2.1 on 2025-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0002_add_text_integration_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinsettings',
            name='ideogram_model',
            field=models.CharField(choices=[('V_2A_TURBO', 'Ideogram 2a Turbo (Beste Text-Integration)'), ('V_2A', 'Ideogram 2a (Höchste Qualität)'), ('V_2', 'Ideogram 2.0'), ('V_2_TURBO', 'Ideogram 2.0 Turbo (Schnell)'), ('V_1', 'Ideogram 1.0'), ('V_1_TURBO', 'Ideogram 1.0 Turbo')], default='V_2A_TURBO', help_text='V_2A_TURBO ist am besten für Text-Overlays geeignet', max_length=20, verbose_name='Ideogram Modell'),
        ),
    ]
