# Generated by Django 5.2.1 on 2025-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0003_add_ideogram_model_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinsettings',
            name='ideogram_style',
            field=models.CharField(choices=[('REALISTIC', 'Realistisch'), ('DESIGN', 'Design/Grafisch'), ('RENDER_3D', '3D Render'), ('ANIME', 'Anime'), ('GENERAL', 'Automatisch')], default='REALISTIC', help_text='Realistisch ist für Produkt-Pins am besten geeignet', max_length=20, verbose_name='Bild-Style'),
        ),
    ]
