# Generated by Django 5.2.1 on 2025-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0004_add_ideogram_style_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinsettings',
            name='ai_provider',
            field=models.CharField(choices=[('ideogram', 'Ideogram'), ('gemini', 'Google Gemini (Imagen 3)')], default='gemini', help_text='Gemini (Imagen 3) ist empfohlen für beste Text- und Bildqualität', max_length=20, verbose_name='KI-Anbieter'),
        ),
        migrations.AddField(
            model_name='pinsettings',
            name='gemini_model',
            field=models.CharField(choices=[('imagen-3.0-generate-002', 'Imagen 3 (Beste Qualität)'), ('imagen-3.0-fast-generate-001', 'Imagen 3 Fast (Schneller)')], default='imagen-3.0-generate-002', help_text='Imagen 3 liefert beste Qualität, Fast ist schneller', max_length=50, verbose_name='Gemini Modell'),
        ),
    ]
