# Generated by Django 5.2.1 on 2025-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0005_add_ai_provider_and_gemini_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinsettings',
            name='ai_provider',
            field=models.CharField(choices=[('ideogram', 'Ideogram'), ('gemini', 'Google Gemini (Nano Banana)')], default='gemini', help_text='Gemini (Imagen 3) ist empfohlen für beste Text- und Bildqualität', max_length=20, verbose_name='KI-Anbieter'),
        ),
        migrations.AlterField(
            model_name='pinsettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash-exp', 'Gemini 2.0 Flash (Nano Banana)'), ('gemini-2.0-flash-preview-image-generation', 'Gemini 2.0 Flash Preview')], default='gemini-2.0-flash-exp', help_text='Nano Banana kann Produkte extrahieren und Text perfekt rendern', max_length=50, verbose_name='Gemini Modell'),
        ),
    ]
