# Generated by Django 5.2.1 on 2025-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0006_update_gemini_model_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinsettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash-preview-image-generation', 'Gemini 2.0 Flash (Nano Banana)'), ('gemini-2.5-flash-preview-image-generation', 'Gemini 2.5 Flash Preview')], default='gemini-2.0-flash-preview-image-generation', help_text='Nano Banana kann Produkte extrahieren und Text perfekt rendern', max_length=50, verbose_name='Gemini Modell'),
        ),
    ]
