# Generated by Django 5.2.1 on 2025-12-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0007_fix_gemini_model_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinsettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.5-flash-preview-09-2025', 'Gemini 2.5 Flash (Nano Banana)'), ('gemini-3-pro-image-preview', 'Gemini 3 Pro Image (Neueste)'), ('imagen-4.0-generate-001', 'Imagen 4 Standard'), ('imagen-4.0-fast-generate-001', 'Imagen 4 Fast'), ('imagen-4.0-ultra-generate-001', 'Imagen 4 Ultra (Beste Qualität)')], default='gemini-2.5-flash-preview-09-2025', help_text='Nano Banana kann Produkte extrahieren und Text perfekt rendern', max_length=50, verbose_name='Gemini Modell'),
        ),
    ]
