# Generated by Django 5.2.1 on 2025-12-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0008_update_gemini_models_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinsettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.5-flash-image', 'Gemini 2.5 Flash Image (Nano Banana)'), ('gemini-2.0-flash-exp-image-generation', 'Gemini 2.0 Flash Exp'), ('imagen-4.0-generate-001', 'Imagen 4 Standard'), ('imagen-4.0-fast-generate-001', 'Imagen 4 Fast'), ('imagen-4.0-ultra-generate-001', 'Imagen 4 Ultra (Beste Qualität)')], default='gemini-2.5-flash-image', help_text='Nano Banana kann Produkte extrahieren und Text perfekt rendern', max_length=50, verbose_name='Gemini Modell'),
        ),
    ]
