# Generated by Django 5.2.1 on 2025-12-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0009_fix_gemini_image_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinsettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-3-pro-image-preview', 'Gemini 3 Pro Image (Nano Banana Pro - Beste Qualität)'), ('gemini-2.5-flash-image', 'Gemini 2.5 Flash Image (Nano Banana - Schnell)'), ('imagen-4.0-ultra-generate-001', 'Imagen 4 Ultra'), ('imagen-4.0-generate-001', 'Imagen 4 Standard'), ('imagen-4.0-fast-generate-001', 'Imagen 4 Fast')], default='gemini-3-pro-image-preview', help_text='Nano Banana Pro: 4K, bestes Text-Rendering, bis zu 14 Referenzbilder', max_length=50, verbose_name='Gemini Modell'),
        ),
    ]
