# Generated by Django 5.2.1 on 2025-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0011_default_nano_banana'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinproject',
            name='auto_font_size',
            field=models.BooleanField(default=True, help_text='Schriftgröße automatisch an Textlänge anpassen', verbose_name='Automatische Schriftgröße'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='style_preset',
            field=models.CharField(choices=[('custom', 'Benutzerdefiniert'), ('modern_bold', 'Modern & Bold'), ('elegant_serif', 'Elegant & Klassisch'), ('playful_color', 'Verspielt & Bunt'), ('minimal_clean', 'Minimalistisch'), ('dark_contrast', 'Dunkel & Kontrastreich'), ('bright_fresh', 'Hell & Frisch'), ('vintage_retro', 'Vintage & Retro'), ('professional', 'Business & Professionell')], default='custom', help_text='Vordefinierte Styling-Kombination', max_length=30, verbose_name='Style-Preset'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='styling_ai_generated',
            field=models.BooleanField(default=False, verbose_name='KI-generiertes Styling'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='text_effect',
            field=models.CharField(choices=[('none', 'Kein Effekt'), ('shadow', 'Schatten'), ('outline', 'Kontur/Outline'), ('glow', 'Leuchteffekt'), ('frame', 'Rahmen'), ('banner', 'Banner/Ribbon'), ('badge', 'Badge/Stempel')], default='none', help_text='Visueller Effekt für bessere Lesbarkeit', max_length=20, verbose_name='Text-Effekt'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='text_line_height',
            field=models.FloatField(default=1.3, help_text='Multiplikator für Zeilenabstand', verbose_name='Zeilenhöhe'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='text_max_width_percent',
            field=models.IntegerField(default=80, help_text='Maximale Breite des Texts in Prozent der Bildbreite', verbose_name='Max. Textbreite (%)'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='text_padding',
            field=models.IntegerField(default=20, help_text='Abstand um den Text herum', verbose_name='Text-Padding'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='text_secondary_color',
            field=models.CharField(default='#000000', help_text='Für Outline, Schatten oder Akzente', max_length=7, verbose_name='Sekundärfarbe'),
        ),
        migrations.AddField(
            model_name='pinsettings',
            name='default_auto_font_size',
            field=models.BooleanField(default=True, verbose_name='Auto-Schriftgröße aktivieren'),
        ),
        migrations.AddField(
            model_name='pinsettings',
            name='default_style_preset',
            field=models.CharField(choices=[('custom', 'Benutzerdefiniert'), ('modern_bold', 'Modern & Bold'), ('elegant_serif', 'Elegant & Klassisch'), ('playful_color', 'Verspielt & Bunt'), ('minimal_clean', 'Minimalistisch'), ('dark_contrast', 'Dunkel & Kontrastreich'), ('bright_fresh', 'Hell & Frisch'), ('vintage_retro', 'Vintage & Retro'), ('professional', 'Business & Professionell')], default='modern_bold', max_length=30, verbose_name='Standard Style-Preset'),
        ),
        migrations.AddField(
            model_name='pinsettings',
            name='default_text_effect',
            field=models.CharField(choices=[('none', 'Kein Effekt'), ('shadow', 'Schatten'), ('outline', 'Kontur/Outline'), ('glow', 'Leuchteffekt'), ('frame', 'Rahmen'), ('banner', 'Banner/Ribbon'), ('badge', 'Badge/Stempel')], default='shadow', max_length=20, verbose_name='Standard Text-Effekt'),
        ),
        migrations.AddField(
            model_name='pinsettings',
            name='enable_auto_styling',
            field=models.BooleanField(default=True, help_text='KI schlägt automatisch passendes Styling vor', verbose_name='Auto-Styling aktivieren'),
        ),
    ]
