# Generated by Django 5.2.1 on 2025-12-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0012_auto_styling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinproject',
            name='pinterest_board_id',
            field=models.CharField(blank=True, help_text='ID des Boards auf das der Pin gepostet wurde', max_length=100, verbose_name='Pinterest Board ID'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='pinterest_board_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pinterest Board Name'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='pinterest_pin_id',
            field=models.CharField(blank=True, help_text='ID des geposteten Pins auf Pinterest', max_length=100, verbose_name='Pinterest Pin ID'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='pinterest_post_error',
            field=models.TextField(blank=True, help_text='Letzter Fehler beim Posten auf Pinterest', verbose_name='Posting-Fehler'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='pinterest_posted',
            field=models.BooleanField(default=False, verbose_name='Auf Pinterest gepostet'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='pinterest_posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gepostet am'),
        ),
        migrations.AlterField(
            model_name='pinproject',
            name='style_preset',
            field=models.CharField(choices=[('custom', 'Benutzerdefiniert'), ('modern_bold', 'Modern & Bold'), ('minimal_clean', 'Minimalistisch'), ('tech_futuristic', 'Tech & Futuristisch'), ('geometric', 'Geometrisch & Modern'), ('elegant_serif', 'Elegant & Klassisch'), ('luxury_gold', 'Luxuriös & Gold'), ('wedding_romantic', 'Romantisch & Hochzeit'), ('art_deco', 'Art Déco'), ('playful_color', 'Verspielt & Bunt'), ('neon_glow', 'Neon & Leuchtend'), ('pastel_soft', 'Pastell & Sanft'), ('gradient_vibrant', 'Gradient & Leuchtend'), ('rainbow', 'Regenbogen'), ('dark_contrast', 'Dunkel & Kontrastreich'), ('midnight_blue', 'Mitternachtsblau'), ('noir_dramatic', 'Film Noir'), ('bright_fresh', 'Hell & Frisch'), ('summer_beach', 'Sommer & Strand'), ('spring_floral', 'Frühling & Blumen'), ('vintage_retro', 'Vintage & Retro'), ('retro_70s', '70er Jahre'), ('polaroid', 'Polaroid'), ('professional', 'Business & Professionell'), ('corporate_blue', 'Corporate Blau'), ('startup', 'Startup Modern'), ('food_warm', 'Food & Warm'), ('nature_organic', 'Natur & Organisch'), ('fitness_energy', 'Fitness & Energie'), ('kids_playful', 'Kinder & Verspielt'), ('christmas', 'Weihnachten'), ('halloween', 'Halloween')], default='custom', help_text='Vordefinierte Styling-Kombination', max_length=30, verbose_name='Style-Preset'),
        ),
        migrations.AlterField(
            model_name='pinproject',
            name='text_effect',
            field=models.CharField(choices=[('none', 'Kein Effekt'), ('shadow', 'Schatten (Standard)'), ('shadow_soft', 'Weicher Schatten'), ('shadow_hard', 'Harter Schatten'), ('shadow_long', 'Langer Schatten'), ('shadow_3d', '3D-Schatten'), ('outline', 'Kontur (Standard)'), ('outline_thin', 'Dünne Kontur'), ('outline_thick', 'Dicke Kontur'), ('outline_double', 'Doppelte Kontur'), ('glow', 'Leuchteffekt'), ('glow_neon', 'Neon-Glow'), ('glow_soft', 'Sanftes Leuchten'), ('highlight', 'Textmarker'), ('underline', 'Unterstrichen'), ('box', 'Box/Kasten'), ('rounded_box', 'Abgerundeter Kasten'), ('pill', 'Pill-Form'), ('frame', 'Rahmen'), ('banner', 'Banner/Ribbon'), ('badge', 'Badge/Stempel'), ('stamp', 'Vintage Stempel'), ('torn_paper', 'Zerrissenes Papier'), ('gradient_text', 'Gradient-Text')], default='none', help_text='Visueller Effekt für bessere Lesbarkeit', max_length=20, verbose_name='Text-Effekt'),
        ),
        migrations.AlterField(
            model_name='pinsettings',
            name='default_style_preset',
            field=models.CharField(choices=[('custom', 'Benutzerdefiniert'), ('modern_bold', 'Modern & Bold'), ('minimal_clean', 'Minimalistisch'), ('tech_futuristic', 'Tech & Futuristisch'), ('geometric', 'Geometrisch & Modern'), ('elegant_serif', 'Elegant & Klassisch'), ('luxury_gold', 'Luxuriös & Gold'), ('wedding_romantic', 'Romantisch & Hochzeit'), ('art_deco', 'Art Déco'), ('playful_color', 'Verspielt & Bunt'), ('neon_glow', 'Neon & Leuchtend'), ('pastel_soft', 'Pastell & Sanft'), ('gradient_vibrant', 'Gradient & Leuchtend'), ('rainbow', 'Regenbogen'), ('dark_contrast', 'Dunkel & Kontrastreich'), ('midnight_blue', 'Mitternachtsblau'), ('noir_dramatic', 'Film Noir'), ('bright_fresh', 'Hell & Frisch'), ('summer_beach', 'Sommer & Strand'), ('spring_floral', 'Frühling & Blumen'), ('vintage_retro', 'Vintage & Retro'), ('retro_70s', '70er Jahre'), ('polaroid', 'Polaroid'), ('professional', 'Business & Professionell'), ('corporate_blue', 'Corporate Blau'), ('startup', 'Startup Modern'), ('food_warm', 'Food & Warm'), ('nature_organic', 'Natur & Organisch'), ('fitness_energy', 'Fitness & Energie'), ('kids_playful', 'Kinder & Verspielt'), ('christmas', 'Weihnachten'), ('halloween', 'Halloween')], default='modern_bold', max_length=30, verbose_name='Standard Style-Preset'),
        ),
        migrations.AlterField(
            model_name='pinsettings',
            name='default_text_effect',
            field=models.CharField(choices=[('none', 'Kein Effekt'), ('shadow', 'Schatten (Standard)'), ('shadow_soft', 'Weicher Schatten'), ('shadow_hard', 'Harter Schatten'), ('shadow_long', 'Langer Schatten'), ('shadow_3d', '3D-Schatten'), ('outline', 'Kontur (Standard)'), ('outline_thin', 'Dünne Kontur'), ('outline_thick', 'Dicke Kontur'), ('outline_double', 'Doppelte Kontur'), ('glow', 'Leuchteffekt'), ('glow_neon', 'Neon-Glow'), ('glow_soft', 'Sanftes Leuchten'), ('highlight', 'Textmarker'), ('underline', 'Unterstrichen'), ('box', 'Box/Kasten'), ('rounded_box', 'Abgerundeter Kasten'), ('pill', 'Pill-Form'), ('frame', 'Rahmen'), ('banner', 'Banner/Ribbon'), ('badge', 'Badge/Stempel'), ('stamp', 'Vintage Stempel'), ('torn_paper', 'Zerrissenes Papier'), ('gradient_text', 'Gradient-Text')], default='shadow', max_length=20, verbose_name='Standard Text-Effekt'),
        ),
    ]
