# Generated by Django 5.2.1 on 2025-12-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0013_pinproject_pinterest_board_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinproject',
            name='pin_title',
            field=models.CharField(blank=True, help_text='Pinterest Pin-Titel (max. 100 Zeichen)', max_length=100, verbose_name='Pin-Titel'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='pin_title_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
