# Generated by Django 5.2.1 on 2025-12-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0014_add_pin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinproject',
            name='text_background_creative',
            field=models.BooleanField(default=False, help_text='Hintergrund kann kreative Formen haben (Banner, Ribbon, etc.)', verbose_name='Kreative Formen'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='text_background_enabled',
            field=models.BooleanField(default=False, help_text='Text auf einem formpassenden Hintergrund platzieren', verbose_name='Text-Hintergrund'),
        ),
    ]
