# Generated by Django 5.2.1 on 2025-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0015_add_text_background_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinproject',
            name='upload_post_platforms',
            field=models.TextField(blank=True, help_text='Komma-getrennte Liste der Plattformen (instagram,facebook,x,linkedin,threads,bluesky)', verbose_name='Upload-Post Plattformen'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='upload_post_posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upload-Post gepostet am'),
        ),
        migrations.AlterField(
            model_name='pinproject',
            name='text_background_creative',
            field=models.BooleanField(default=True, help_text='Hintergrund kann kreative Formen haben (Banner, Ribbon, etc.)', verbose_name='Kreative Formen'),
        ),
        migrations.AlterField(
            model_name='pinproject',
            name='text_background_enabled',
            field=models.BooleanField(default=True, help_text='Text auf einem formpassenden Hintergrund platzieren', verbose_name='Text-Hintergrund'),
        ),
    ]
