# Generated by Django 5.2.1 on 2025-12-23 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0016_add_upload_post_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinproject',
            name='distribution_interval_days',
            field=models.PositiveIntegerField(default=2, help_text='Tage zwischen automatisch geplanten Pins', verbose_name='Verteilungs-Intervall (Tage)'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='distribution_mode',
            field=models.CharField(choices=[('manual', 'Manuell'), ('auto', 'Automatisch verteilen')], default='manual', help_text='Wie sollen die Pins zeitlich verteilt werden?', max_length=20, verbose_name='Verteilungs-Modus'),
        ),
        migrations.AddField(
            model_name='pinproject',
            name='pin_count',
            field=models.PositiveIntegerField(default=1, help_text='Anzahl der zu erstellenden Pins (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Anzahl Pins'),
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, help_text='Reihenfolge des Pins (1-7)', verbose_name='Position')),
                ('overlay_text', models.CharField(blank=True, help_text='Catchy Pin-Text für dieses Bild', max_length=200, verbose_name='Overlay-Text')),
                ('overlay_text_ai_generated', models.BooleanField(default=False)),
                ('background_description', models.TextField(blank=True, help_text='Individuelle Hintergrund-Beschreibung für diesen Pin', verbose_name='Hintergrund-Beschreibung')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='ideopin/pins/generated/', verbose_name='Generiertes Bild')),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='ideopin/pins/final/', verbose_name='Finales Bild mit Text')),
                ('pin_title', models.CharField(blank=True, help_text='Pinterest Pin-Titel (max. 100 Zeichen)', max_length=100, verbose_name='Pin-Titel')),
                ('pin_title_ai_generated', models.BooleanField(default=False)),
                ('seo_description', models.TextField(blank=True, help_text='Pinterest-optimierte Beschreibung (max. 500 Zeichen)', max_length=500, verbose_name='SEO Pin-Beschreibung')),
                ('seo_description_ai_generated', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Datum und Uhrzeit für automatisches Posten', null=True, verbose_name='Geplant für')),
                ('pinterest_posted', models.BooleanField(default=False, verbose_name='Auf Pinterest gepostet')),
                ('pinterest_pin_id', models.CharField(blank=True, max_length=100, verbose_name='Pinterest Pin ID')),
                ('pinterest_board_id', models.CharField(blank=True, max_length=100, verbose_name='Pinterest Board ID')),
                ('pinterest_board_name', models.CharField(blank=True, max_length=200, verbose_name='Pinterest Board Name')),
                ('pinterest_posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gepostet am')),
                ('pinterest_post_error', models.TextField(blank=True, verbose_name='Posting-Fehler')),
                ('upload_post_platforms', models.TextField(blank=True, verbose_name='Upload-Post Plattformen')),
                ('upload_post_posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Upload-Post gepostet am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='ideopin.pinproject')),
            ],
            options={
                'verbose_name': 'Pin',
                'verbose_name_plural': 'Pins',
                'ordering': ['position'],
                'unique_together': {('project', 'position')},
            },
        ),
    ]
