# Generated by Django 5.2.1 on 2025-12-23 21:35

from django.db import migrations


def migrate_projects_to_pins(apps, schema_editor):
    """
    Für jedes bestehende PinProject wird ein Pin mit position=1 erstellt
    und die relevanten Daten vom PinProject kopiert.
    """
    PinProject = apps.get_model('ideopin', 'PinProject')
    Pin = apps.get_model('ideopin', 'Pin')

    for project in PinProject.objects.all():
        # Prüfen ob bereits ein Pin existiert
        if not Pin.objects.filter(project=project).exists():
            Pin.objects.create(
                project=project,
                position=1,
                # Content
                overlay_text=project.overlay_text or '',
                overlay_text_ai_generated=project.overlay_text_ai_generated,
                background_description=project.background_description or '',
                # Bilder
                generated_image=project.generated_image.name if project.generated_image else '',
                final_image=project.final_image.name if project.final_image else '',
                # SEO
                pin_title=project.pin_title or '',
                pin_title_ai_generated=project.pin_title_ai_generated,
                seo_description=project.seo_description or '',
                seo_description_ai_generated=project.seo_description_ai_generated,
                # Publishing Status
                pinterest_posted=project.pinterest_posted,
                pinterest_pin_id=project.pinterest_pin_id or '',
                pinterest_board_id=project.pinterest_board_id or '',
                pinterest_board_name=project.pinterest_board_name or '',
                pinterest_posted_at=project.pinterest_posted_at,
                pinterest_post_error=project.pinterest_post_error or '',
                # Upload-Post
                upload_post_platforms=project.upload_post_platforms or '',
                upload_post_posted_at=project.upload_post_posted_at,
            )


def reverse_migration(apps, schema_editor):
    """
    Bei Rückwärts-Migration: Lösche alle erstellten Pins
    """
    Pin = apps.get_model('ideopin', 'Pin')
    Pin.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0017_add_multipin_feature'),
    ]

    operations = [
        migrations.RunPython(migrate_projects_to_pins, reverse_migration),
    ]
