# Generated by Django 5.2.1 on 2026-02-05 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideopin', '0018_migrate_existing_projects_to_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinproject',
            name='pin_count',
            field=models.PositiveIntegerField(default=1, help_text='Anzahl der zu erstellenden Pins (1-14)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)], verbose_name='Anzahl Pins'),
        ),
    ]
