# Generated by Django 5.2.1 on 2025-08-25 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamRecAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('successful_sessions', models.PositiveIntegerField(default=0)),
                ('failed_sessions', models.PositiveIntegerField(default=0)),
                ('camera_usage', models.PositiveIntegerField(default=0)),
                ('screen_usage', models.PositiveIntegerField(default=0)),
                ('multi_stream_usage', models.PositiveIntegerField(default=0)),
                ('avg_duration_seconds', models.FloatField(default=0)),
                ('avg_file_size_mb', models.FloatField(default=0)),
                ('most_used_layout', models.CharField(blank=True, max_length=100)),
                ('browser_stats', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Analytics Daten',
                'verbose_name_plural': 'Analytics Daten',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_video_quality', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=10)),
                ('default_audio_quality', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=10)),
                ('preferred_layout', models.CharField(default='pip-top-right', max_length=100)),
                ('show_notifications', models.BooleanField(default=True)),
                ('auto_save_settings', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('auto_start_composition', models.BooleanField(default=True)),
                ('include_system_audio', models.BooleanField(default=True)),
                ('preferred_format', models.CharField(default='webm', max_length=10)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streamrec_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzer-Einstellungen',
                'verbose_name_plural': 'Benutzer-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Gestartet'), ('recording', 'Aufnahme'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='started', max_length=20)),
                ('streams_used', models.JSONField(default=list)),
                ('layout_used', models.CharField(blank=True, max_length=100)),
                ('video_quality', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=10)),
                ('audio_quality', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('format_used', models.CharField(default='webm', max_length=10)),
                ('browser_info', models.CharField(blank=True, max_length=100)),
                ('performance_issues', models.JSONField(default=list)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aufnahme-Session',
                'verbose_name_plural': 'Aufnahme-Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='streamrec_r_user_id_bb84ff_idx'), models.Index(fields=['status'], name='streamrec_r_status_d8227c_idx')],
            },
        ),
    ]
