# Generated by Django 5.2.1 on 2025-10-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamrec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='dark_mode',
        ),
    ]
