# Generated by Django 5.2.1 on 2026-01-25 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageforge', '0003_add_motif_to_mockup'),
        ('shopify_manager', '0010_image_storage_to_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLoomFavoritePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis')),
                ('label', models.CharField(blank=True, help_text="z.B. 'Standard', 'Premium'", max_length=50, verbose_name='Bezeichnung')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Verwendungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploom_favorite_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favoriten-Preis',
                'verbose_name_plural': 'Favoriten-Preise',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PLoomProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='Hersteller')),
                ('product_type', models.CharField(blank=True, max_length=100, verbose_name='Produkttyp')),
                ('tags', models.TextField(blank=True, help_text='Komma-getrennte Liste', verbose_name='Tags')),
                ('seo_title', models.CharField(blank=True, help_text='Max 70 Zeichen', max_length=70, verbose_name='SEO-Titel')),
                ('seo_description', models.TextField(blank=True, help_text='Max 160 Zeichen', max_length=160, verbose_name='SEO-Beschreibung')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vergleichspreis')),
                ('product_metafields', models.JSONField(blank=True, default=dict, verbose_name='Produkt-Metafelder')),
                ('category_metafields', models.JSONField(blank=True, default=dict, verbose_name='Kategorie-Metafelder')),
                ('collection_id', models.CharField(blank=True, max_length=50, verbose_name='Collection ID')),
                ('collection_name', models.CharField(blank=True, max_length=200, verbose_name='Collection Name')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('ready', 'Bereit zum Upload'), ('uploaded', 'Hochgeladen'), ('error', 'Fehler')], default='draft', max_length=20, verbose_name='Status')),
                ('shopify_product_id', models.CharField(blank=True, max_length=50, verbose_name='Shopify Produkt-ID')),
                ('upload_error', models.TextField(blank=True, verbose_name='Upload-Fehler')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Hochgeladen am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_manager.shopifystore', verbose_name='Shopify Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploom_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P-Loom Produkt',
                'verbose_name_plural': 'P-Loom Produkte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PLoomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('title', 'Titel'), ('description', 'Beschreibung'), ('seo_title', 'SEO-Titel'), ('seo_description', 'SEO-Beschreibung'), ('tags', 'Tags')], max_length=20, verbose_name='Feldtyp')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('prompt_used', models.TextField(blank=True, verbose_name='Verwendeter Prompt')),
                ('ai_model_used', models.CharField(blank=True, max_length=50, verbose_name='Verwendetes KI-Modell')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Ausgewählt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploom_history', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ploom.ploomproduct')),
            ],
            options={
                'verbose_name': 'P-Loom Verlauf',
                'verbose_name_plural': 'P-Loom Verlauf',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PLoomProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('imageforge_generation', 'ImageForge Generierung'), ('imageforge_mockup', 'ImageForge Mockup'), ('upload', 'Eigener Upload')], default='upload', max_length=30, verbose_name='Quelle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ploom/images/%Y/%m/', verbose_name='Bild')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt-Text')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hauptbild')),
                ('variant_id', models.CharField(blank=True, help_text='Für Varianten-spezifische Bilder', max_length=50, verbose_name='Varianten-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imageforge_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imageforge.imagegeneration', verbose_name='ImageForge Generierung')),
                ('imageforge_mockup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imageforge.productmockup', verbose_name='ImageForge Mockup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ploom.ploomproduct')),
            ],
            options={
                'verbose_name': 'Produkt-Bild',
                'verbose_name_plural': 'Produkt-Bilder',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PLoomProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titel')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vergleichspreis')),
                ('option1_name', models.CharField(blank=True, max_length=50, verbose_name='Option 1 Name')),
                ('option1_value', models.CharField(blank=True, max_length=100, verbose_name='Option 1 Wert')),
                ('option2_name', models.CharField(blank=True, max_length=50, verbose_name='Option 2 Name')),
                ('option2_value', models.CharField(blank=True, max_length=100, verbose_name='Option 2 Wert')),
                ('option3_name', models.CharField(blank=True, max_length=50, verbose_name='Option 3 Name')),
                ('option3_value', models.CharField(blank=True, max_length=100, verbose_name='Option 3 Wert')),
                ('barcode', models.CharField(blank=True, help_text='EAN, UPC, etc.', max_length=100, verbose_name='Barcode')),
                ('inventory_quantity', models.IntegerField(default=0, verbose_name='Lagerbestand')),
                ('inventory_policy', models.CharField(choices=[('deny', 'Nicht verkaufen wenn ausverkauft'), ('continue', 'Weiter verkaufen wenn ausverkauft')], default='deny', max_length=10, verbose_name='Bestandsrichtlinie')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Gewicht')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilogramm'), ('g', 'Gramm'), ('lb', 'Pfund'), ('oz', 'Unzen')], default='kg', max_length=5, verbose_name='Gewichtseinheit')),
                ('requires_shipping', models.BooleanField(default=True, verbose_name='Versand erforderlich')),
                ('taxable', models.BooleanField(default=True, verbose_name='Steuerpflichtig')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ploom.ploomproduct')),
            ],
            options={
                'verbose_name': 'Produkt-Variante',
                'verbose_name_plural': 'Produkt-Varianten',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PLoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='KI-Anbieter')),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='KI-Modell')),
                ('writing_style', models.CharField(choices=[('du', 'Du-Anrede'), ('sie', 'Sie-Anrede'), ('neutral', 'Neutral')], default='du', max_length=10, verbose_name='Schreibstil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_manager.shopifystore', verbose_name='Standard-Store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ploom_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P-Loom Einstellung',
                'verbose_name_plural': 'P-Loom Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='ProductTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title_template', models.TextField(blank=True, help_text='Platzhalter: {product_name}, {brand}, {category}', verbose_name='Titel-Vorlage')),
                ('description_template', models.TextField(blank=True, verbose_name='Beschreibungs-Vorlage')),
                ('seo_title_template', models.CharField(blank=True, max_length=200, verbose_name='SEO-Titel-Vorlage')),
                ('seo_description_template', models.TextField(blank=True, verbose_name='SEO-Beschreibungs-Vorlage')),
                ('default_metafields', models.JSONField(blank=True, default=dict, verbose_name='Standard-Metafelder')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard-Theme')),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Standard-Preis')),
                ('default_compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Standard-Vergleichspreis')),
                ('default_vendor', models.CharField(blank=True, max_length=100, verbose_name='Standard-Hersteller')),
                ('default_product_type', models.CharField(blank=True, max_length=100, verbose_name='Standard-Produkttyp')),
                ('default_tags', models.TextField(blank=True, help_text='Komma-getrennte Liste', verbose_name='Standard-Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploom_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produkt-Theme',
                'verbose_name_plural': 'Produkt-Themes',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ploomproduct',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ploom.producttheme', verbose_name='Theme'),
        ),
    ]
