# Generated by Django 5.2.1 on 2026-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0002_add_image_history_and_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomhistory',
            name='metafield_key',
            field=models.CharField(blank=True, help_text='z.B. custom.material', max_length=100, verbose_name='Metafeld-Key'),
        ),
        migrations.AddField(
            model_name='ploomproduct',
            name='product_category',
            field=models.CharField(blank=True, help_text='Shopify Taxonomy Category ID', max_length=100, verbose_name='Produktkategorie ID'),
        ),
        migrations.AddField(
            model_name='ploomproduct',
            name='product_category_name',
            field=models.CharField(blank=True, help_text="z.B. 'Haus & Garten > Pflanztöpfe'", max_length=255, verbose_name='Produktkategorie'),
        ),
        migrations.AddField(
            model_name='ploomproductvariant',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Einkaufspreis für Gewinnberechnung', max_digits=10, null=True, verbose_name='Kosten pro Einheit'),
        ),
        migrations.AlterField(
            model_name='ploomhistory',
            name='field_type',
            field=models.CharField(choices=[('title', 'Titel'), ('description', 'Beschreibung'), ('seo_title', 'SEO-Titel'), ('seo_description', 'SEO-Beschreibung'), ('tags', 'Tags'), ('metafield', 'Metafeld')], max_length=20, verbose_name='Feldtyp'),
        ),
    ]
