# Generated by Django 5.2.1 on 2026-03-14 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0003_ploomhistory_metafield_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomsettings',
            name='default_compare_price_komplett',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vergleichspreis Komplett'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_compare_price_topf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vergleichspreis Topf'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_metafields_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Standard-Metafelder'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_price_komplett',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis Komplettset'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_price_topf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis Nur Topf'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_product_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Standard-Produkttyp'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_tags',
            field=models.TextField(blank=True, verbose_name='Standard-Tags'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_template_suffix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Shopify Template Suffix'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_vendor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Standard-Hersteller'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Standard-Gewicht'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='kg', max_length=5, verbose_name='Gewichtseinheit'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='engraving_style',
            field=models.CharField(blank=True, default='elegante Schreibschrift', max_length=200, verbose_name='Gravur-Stil'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='example_engraving_image',
            field=models.ImageField(blank=True, null=True, upload_to='ploom/settings/engraving/', verbose_name='Beispiel-Gravur Foto'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='image_generation_model',
            field=models.CharField(default='gemini-2.5-flash-image', max_length=50, verbose_name='Bildgenerierungs-Modell'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='komplettset_description',
            field=models.TextField(blank=True, help_text='Was ist im Komplettset enthalten?', verbose_name='Komplettset-Beschreibung'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='ploom/settings/reference/', verbose_name='Referenz-Blumentopf Foto'),
        ),
        migrations.AlterField(
            model_name='ploomproductimage',
            name='source',
            field=models.CharField(choices=[('imageforge_generation', 'ImageForge Generierung'), ('imageforge_mockup', 'ImageForge Mockup'), ('upload', 'Eigener Upload'), ('external_url', 'Externe URL (Shopify/CDN)'), ('gemini_workflow', 'Gravur-Workflow Generierung')], default='upload', max_length=30, verbose_name='Quelle'),
        ),
        migrations.CreateModel(
            name='PLoomReusableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ploom/reusable/', verbose_name='Bild')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beschreibung')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploom_reusable_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiederverwendbares Bild',
                'verbose_name_plural': 'Wiederverwendbare Bilder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PLoomWorkflowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200, verbose_name='Theme/Keyword')),
                ('current_step', models.CharField(choices=[('step1', 'Gravur-Text'), ('step2', 'Szenen-Auswahl'), ('step3', 'Bildgenerierung'), ('step4', 'Inhalte & SEO'), ('step5', 'Review'), ('completed', 'Abgeschlossen')], default='step1', max_length=20, verbose_name='Aktueller Schritt')),
                ('suggested_texts', models.JSONField(blank=True, default=list, verbose_name='Vorgeschlagene Texte')),
                ('selected_text', models.CharField(blank=True, max_length=300, verbose_name='Ausgewählter Text')),
                ('suggested_scenes', models.JSONField(blank=True, default=list, verbose_name='Vorgeschlagene Szenen')),
                ('selected_scenes', models.JSONField(blank=True, default=list, verbose_name='Ausgewählte Szenen')),
                ('generated_images', models.JSONField(blank=True, default=list, help_text='[{scene, image_path, is_variant, variant_type, selected}]', verbose_name='Generierte Bilder')),
                ('auto_title', models.CharField(blank=True, max_length=255, verbose_name='Auto-Titel')),
                ('auto_description', models.TextField(blank=True, verbose_name='Auto-Beschreibung')),
                ('auto_seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO-Titel')),
                ('auto_seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO-Beschreibung')),
                ('auto_tags', models.TextField(blank=True, verbose_name='Tags')),
                ('auto_alt_texts', models.JSONField(blank=True, default=list, verbose_name='Alt-Texte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_sessions', to='ploom.ploomproduct', verbose_name='Erstelltes Produkt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploom_workflow_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow-Session',
                'verbose_name_plural': 'Workflow-Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
