# Generated by Django 5.2.1 on 2026-03-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0004_ploomsettings_default_compare_price_komplett_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomsettings',
            name='default_collection_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Standard-Collection ID'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_collection_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standard-Collection Name'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_product_category',
            field=models.CharField(blank=True, help_text='Shopify Taxonomy Category ID', max_length=100, verbose_name='Standard-Produktkategorie ID'),
        ),
        migrations.AddField(
            model_name='ploomsettings',
            name='default_product_category_name',
            field=models.CharField(blank=True, help_text="z.B. 'Haus & Garten > Pflanztöpfe'", max_length=255, verbose_name='Standard-Produktkategorie'),
        ),
    ]
