# Generated by Django 5.2.1 on 2026-03-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0005_ploomsettings_default_collection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomsettings',
            name='product_description_context',
            field=models.TextField(blank=True, help_text='Informationen über das Produkt, Material, Herstellung, USPs etc. — wird als Basis für KI-generierte Beschreibungen verwendet', verbose_name='Produktbeschreibungs-Kontext'),
        ),
    ]
