# Generated by Django 5.2.1 on 2026-03-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0006_ploomsettings_product_description_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomsettings',
            name='pot_description',
            field=models.TextField(blank=True, help_text="Detaillierte Beschreibung des Blumentopfs (Größe, Form, Farbe, Material). Z.B.: 'Runder Keramik-Blumentopf, Durchmesser 14cm, Höhe 12cm, cremeweiß, matte Oberfläche, handgetöpfert, mit Drainageloch'", verbose_name='Topf-Beschreibung für Bildgenerierung'),
        ),
    ]
