# Generated by Django 5.2.1 on 2026-03-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0007_add_pot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomsettings',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link zu einem Produktvideo (z.B. YouTube, Vimeo). Wird bei Produkterstellung übernommen.', max_length=500, verbose_name='Video-Link'),
        ),
    ]
