# Generated by Django 5.2.1 on 2026-03-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0008_add_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomworkflowsession',
            name='base_pot_image_path',
            field=models.CharField(blank=True, help_text='Pfad zum generierten Basis-Topf-Bild (wird als Referenz für alle Szenen verwendet)', max_length=500, verbose_name='Basis-Topf Bildpfad'),
        ),
    ]
