# Generated by Django 5.2.1 on 2026-03-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0009_add_base_pot_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ploomproduct',
            name='inventory_quantity',
            field=models.IntegerField(default=100, verbose_name='Bestand'),
        ),
        migrations.AlterField(
            model_name='ploomproductvariant',
            name='inventory_quantity',
            field=models.IntegerField(default=100, verbose_name='Lagerbestand'),
        ),
    ]
