# Generated by Django 5.2.1 on 2026-03-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0010_default_inventory_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomsettings',
            name='default_category_metafields',
            field=models.JSONField(blank=True, default=dict, help_text='Metafelder die zur Shopify-Produktkategorie gehören (z.B. Farbe, Material)', verbose_name='Standard Kategorie-Metafelder'),
        ),
    ]
