# Generated by Django 5.2.1 on 2026-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploom', '0011_add_default_category_metafields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploomsettings',
            name='default_sales_channels',
            field=models.JSONField(blank=True, default=list, help_text='Vertriebskanäle die standardmäßig bei neuen Produkten aktiviert werden', verbose_name='Standard-Vertriebskanäle'),
        ),
    ]
