# Generated by Django 5.2.1 on 2026-02-19 17:39

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClawdbotConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z.B. 'Mein Laptop', 'Server'",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "gateway_url",
                    models.URLField(
                        help_text="WebSocket URL des Clawdbot Gateway",
                        verbose_name="Gateway URL",
                    ),
                ),
                (
                    "gateway_token",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Gateway Token"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt gesehen"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Fehler"),
                            ("unknown", "Unbekannt"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cpu_percent",
                    models.FloatField(blank=True, null=True, verbose_name="CPU %"),
                ),
                (
                    "ram_used_mb",
                    models.IntegerField(blank=True, null=True, verbose_name="RAM (MB)"),
                ),
                (
                    "ram_total_mb",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="RAM Total (MB)"
                    ),
                ),
                (
                    "disk_used_gb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Disk Used (GB)"
                    ),
                ),
                (
                    "disk_total_gb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Disk Total (GB)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clawdbot_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clawdbot Verbindung",
                "verbose_name_plural": "Clawdbot Verbindungen",
                "ordering": ["-is_active", "-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("api", "API Key"),
                            ("oauth", "OAuth"),
                            ("cli", "CLI Tool"),
                            ("ssh", "SSH"),
                            ("email", "Email"),
                            ("database", "Database"),
                            ("storage", "Cloud Storage"),
                            ("messaging", "Messaging"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z.B. 'GitHub', 'Zoho Mail'",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("inactive", "Inaktiv"),
                            ("error", "Fehler"),
                            ("pending", "Ausstehend"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Konfiguration"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "last_verified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt geprüft"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="clawboard.clawdbotconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrationen",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Projektname")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("planned", "Geplant"),
                            ("completed", "Abgeschlossen"),
                            ("archived", "Archiviert"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niedrig"),
                            ("medium", "Mittel"),
                            ("high", "Hoch"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="Farbe"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji oder Bootstrap Icon",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "memory_path",
                    models.CharField(
                        blank=True,
                        help_text="Pfad zur .md Datei (relativ zum Workspace)",
                        max_length=500,
                        verbose_name="Memory-Pfad",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="clawboard.clawdbotconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekte",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=255, verbose_name="Session Key"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=500, verbose_name="Titel"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="Zusammenfassung"),
                ),
                (
                    "messages",
                    models.JSONField(default=list, verbose_name="Nachrichten"),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="Anzahl Nachrichten"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="Tokens gesamt"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Kosten ($)",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="telegram, webchat, etc.",
                        max_length=50,
                        verbose_name="Kanal",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Gestartet")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Beendet"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="clawboard.clawdbotconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="clawboard.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konversation",
                "verbose_name_plural": "Konversationen",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Inhalt")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="z.B. memory/2026-02-09.md",
                        max_length=255,
                        verbose_name="Quelle",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("note", "Notiz"),
                            ("decision", "Entscheidung"),
                            ("task", "Aufgabe"),
                            ("idea", "Idee"),
                            ("issue", "Problem"),
                            ("solution", "Lösung"),
                        ],
                        default="note",
                        max_length=50,
                        verbose_name="Typ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="clawboard.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt-Memory",
                "verbose_name_plural": "Projekt-Memories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cron_job_id",
                    models.CharField(
                        help_text="ID vom Clawdbot",
                        max_length=100,
                        verbose_name="Cron Job ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "schedule",
                    models.CharField(
                        help_text="Cron-Expression oder Beschreibung",
                        max_length=100,
                        verbose_name="Schedule",
                    ),
                ),
                ("text", models.TextField(verbose_name="Aufgabentext")),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Aktiviert"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt ausgeführt"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Nächste Ausführung"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to="clawboard.clawdbotconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_tasks",
                        to="clawboard.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geplante Aufgabe",
                "verbose_name_plural": "Geplante Aufgaben",
                "ordering": ["next_run"],
            },
        ),
        migrations.CreateModel(
            name="MemoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="Dateipfad")),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Dateiname"),
                ),
                ("content", models.TextField(verbose_name="Inhalt")),
                (
                    "file_type",
                    models.CharField(
                        default="markdown", max_length=50, verbose_name="Dateityp"
                    ),
                ),
                (
                    "size_bytes",
                    models.IntegerField(default=0, verbose_name="Größe (Bytes)"),
                ),
                (
                    "last_synced",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt synchronisiert"
                    ),
                ),
                (
                    "remote_modified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Remote geändert"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_files",
                        to="clawboard.clawdbotconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory-Datei",
                "verbose_name_plural": "Memory-Dateien",
                "ordering": ["-last_synced"],
                "unique_together": {("connection", "path")},
            },
        ),
    ]
