# Generated by Django 5.2.1 on 2026-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clawboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clawdbotconnection",
            name="gateway_version",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Gateway Version"
            ),
        ),
        migrations.AddField(
            model_name="clawdbotconnection",
            name="hostname",
            field=models.CharField(blank=True, max_length=200, verbose_name="Hostname"),
        ),
    ]
