# Generated by Django 5.2.1 on 2026-02-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clawboard', '0002_clawdbotconnection_gateway_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(choices=[('language', 'Programmiersprache'), ('tool', 'Tool'), ('framework', 'Framework'), ('runtime', 'Runtime')], default='tool', max_length=20, verbose_name='Kategorie')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Version')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('detected_at', models.DateTimeField(auto_now=True, verbose_name='Erkannt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='clawboard.clawdbotconnection')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
                'unique_together': {('connection', 'name')},
            },
        ),
    ]
