# Generated by Django 5.2.1 on 2026-02-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clawboard', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='clawdbotconnection',
            name='pending_command',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ausstehender Befehl'),
        ),
    ]
