# Generated by Django 5.2.1 on 2026-02-24 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clawboard', '0004_clawdbotconnection_pending_command'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClawboardChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='Provider')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modell')),
                ('messages', models.JSONField(default=list, verbose_name='Nachrichten')),
                ('message_count', models.IntegerField(default=0, verbose_name='Anzahl Nachrichten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clawboard_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KI-Chat',
                'verbose_name_plural': 'KI-Chats',
                'ordering': ['-updated_at'],
            },
        ),
    ]
