# Generated by Django 5.2.1 on 2026-02-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clawboard', '0005_clawboardchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='clawboardchat',
            name='chat_mode',
            field=models.CharField(choices=[('gateway', 'Gateway (OpenClaw)'), ('direct', 'Direkt (API Key)')], default='gateway', max_length=10, verbose_name='Chat-Modus'),
        ),
        migrations.AddField(
            model_name='clawdbotconnection',
            name='push_interval_override',
            field=models.IntegerField(blank=True, null=True, verbose_name='Push-Intervall Override (s)'),
        ),
        migrations.AlterField(
            model_name='clawboardchat',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('gemini', 'Google Gemini'), ('gateway', 'Gateway')], default='gateway', max_length=20, verbose_name='Provider'),
        ),
        migrations.CreateModel(
            name='ChatMessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'In Warteschlange'), ('processing', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('error', 'Fehler'), ('timeout', 'Timeout')], default='queued', max_length=20, verbose_name='Status')),
                ('request_messages', models.JSONField(verbose_name='Request Messages')),
                ('model_identifier', models.CharField(max_length=200, verbose_name='Modell-Identifier')),
                ('response_content', models.TextField(blank=True, verbose_name='Antwort')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('timeout_seconds', models.IntegerField(default=120, verbose_name='Timeout (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeholt am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_requests', to='clawboard.clawboardchat')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='clawboard.clawdbotconnection')),
            ],
            options={
                'verbose_name': 'Chat-Request',
                'verbose_name_plural': 'Chat-Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatewayModelCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200, verbose_name='Modell-ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Anzeigename')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='Provider')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_available', models.BooleanField(default=True, verbose_name='Verfuegbar')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Zuletzt gesehen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_models', to='clawboard.clawdbotconnection')),
            ],
            options={
                'verbose_name': 'Gateway-Modell',
                'verbose_name_plural': 'Gateway-Modelle',
                'ordering': ['provider', 'model_name'],
                'unique_together': {('connection', 'model_id')},
            },
        ),
    ]
