# Generated by Django 5.2.1 on 2026-02-25 15:49

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clawboard', '0006_clawboardchat_chat_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clawdbotconnection',
            name='openclaw_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Token fuer die OpenClaw HTTP API (openclaw config get gateway.auth.token)', verbose_name='OpenClaw API Token'),
        ),
    ]
