# Generated by Django 5.2.1 on 2025-08-25 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, help_text='Name für anonyme Meldungen', max_length=100)),
                ('sender_email', models.EmailField(blank=True, help_text='E-Mail für anonyme Meldungen', max_length=254)),
                ('category_type', models.CharField(choices=[('bug', 'Bug melden'), ('idea', 'Idee melden'), ('cooperation', 'Kooperation anfragen'), ('heart', 'Etwas auf dem Herzen'), ('other', 'Sonstiges')], default='bug', help_text='Art der Meldung', max_length=20)),
                ('subject', models.CharField(default='Meldung', max_length=200)),
                ('message', models.TextField(help_text='Beschreibung der Meldung')),
                ('browser_info', models.TextField(blank=True, help_text='Browser und System-Informationen')),
                ('url', models.URLField(blank=True, help_text='URL wo der Bug aufgetreten ist')),
                ('console_log', models.TextField(blank=True, help_text='Console Log der letzten 100 Zeilen')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('resolved', 'Gelöst'), ('closed', 'Geschlossen')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(blank=True, help_text='Verknüpfter Chat-Raum für diese Bug-Meldung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom')),
                ('sender', models.ForeignKey(blank=True, help_text='Angemeldeter User (null bei anonymen Meldungen)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bug-Meldung',
                'verbose_name_plural': 'Bug-Meldungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bug_reports/attachments/%Y/%m/%d/')),
                ('filename', models.CharField(help_text='Originaler Dateiname', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Dateigröße in Bytes')),
                ('content_type', models.CharField(help_text='MIME-Type der Datei', max_length=100)),
                ('is_screenshot', models.BooleanField(default=False, help_text='Ist ein automatisch erstellter Screenshot')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bug_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bug_report.bugreport')),
            ],
            options={
                'verbose_name': 'Bug-Meldung Anhang',
                'verbose_name_plural': 'Bug-Meldung Anhänge',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
