# Generated by Django 5.2.1 on 2025-07-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='console_log',
            field=models.TextField(blank=True, help_text='Console Log der letzten 100 Zeilen'),
        ),
    ]
