# Generated by Django 5.2.1 on 2025-07-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0002_bugreport_console_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='category_type',
            field=models.CharField(choices=[('bug', 'Bug melden'), ('idea', 'Idee melden'), ('cooperation', 'Kooperation anfragen'), ('heart', 'Etwas auf dem Herzen'), ('other', 'Sonstiges')], default='bug', help_text='Art der Meldung', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='message',
            field=models.TextField(help_text='Beschreibung der Meldung'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='subject',
            field=models.CharField(default='Meldung', max_length=200),
        ),
    ]
