# Generated by Django 5.2.1 on 2026-02-16 12:52

import desktop_app_manager.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='App-Name')),
                ('app_identifier', models.CharField(help_text='z.B. pdf-marker', max_length=200, unique=True, verbose_name='App-Identifier')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=desktop_app_manager.models.upload_to_app_icon, verbose_name='App-Icon')),
                ('is_public', models.BooleanField(default=False, help_text='App fuer alle sichtbar machen', verbose_name='Oeffentlich')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_apps', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
            ],
            options={
                'verbose_name': 'Desktop App',
                'verbose_name_plural': 'Desktop Apps',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(help_text='z.B. 1.2.0', max_length=50, verbose_name='Versionsname')),
                ('version_code', models.IntegerField(help_text='Interne Versionsnummer (Integer)', verbose_name='Versionscode')),
                ('exe_file', models.FileField(max_length=500, upload_to=desktop_app_manager.models.upload_exe_to, verbose_name='EXE-Datei')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigroesse (Bytes)')),
                ('file_hash', models.CharField(blank=True, help_text='Wird automatisch beim Upload berechnet', max_length=64, verbose_name='SHA256 Hash')),
                ('release_notes', models.TextField(blank=True, verbose_name='Release Notes / Changelog')),
                ('channel', models.CharField(choices=[('alpha', 'Alpha (Interne Tests)'), ('beta', 'Beta (Oeffentliche Tests)'), ('production', 'Production (Stabile Version)')], db_index=True, default='production', max_length=20, verbose_name='Release Channel')),
                ('min_windows_version', models.CharField(default='10', help_text='z.B. 7, 10, 11', max_length=10, verbose_name='Min. Windows Version')),
                ('is_active', models.BooleanField(default=True, help_text='Nur aktive Versionen werden fuer Updates angeboten', verbose_name='Aktiv')),
                ('is_current_for_channel', models.BooleanField(default=False, help_text='Markiert als aktuelle/empfohlene Version fuer diesen Channel', verbose_name='Aktuelle Version fuer Channel')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download-Zaehler')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='desktop_app_manager.desktopapp', verbose_name='App')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versionen',
                'ordering': ['-version_code'],
            },
        ),
        migrations.CreateModel(
            name='AppScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=desktop_app_manager.models.upload_to_app_screenshot, verbose_name='Screenshot')),
                ('caption', models.CharField(blank=True, help_text='Optionale Beschreibung des Screenshots', max_length=200, verbose_name='Bildunterschrift')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kleinere Zahlen werden zuerst angezeigt', verbose_name='Reihenfolge')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='desktop_app_manager.desktopapp', verbose_name='App')),
            ],
            options={
                'verbose_name': 'App Screenshot',
                'verbose_name_plural': 'App Screenshots',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('windows_version', models.CharField(blank=True, max_length=50, verbose_name='Windows Version')),
                ('download_completed', models.BooleanField(default=False)),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='desktop_app_manager.appversion', verbose_name='App Version')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exe_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download-Log',
                'verbose_name_plural': 'Download-Logs',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='desktopapp',
            index=models.Index(fields=['-updated_at'], name='desktop_app_updated_9bd9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopapp',
            index=models.Index(fields=['app_identifier'], name='desktop_app_app_ide_6032d2_idx'),
        ),
        migrations.AddIndex(
            model_name='desktopapp',
            index=models.Index(fields=['is_public'], name='desktop_app_is_publ_b04920_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['app', 'channel', '-version_code'], name='desktop_app_app_id_13eef3_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['app', 'is_current_for_channel'], name='desktop_app_app_id_daac90_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['-uploaded_at'], name='desktop_app_uploade_576077_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together={('app', 'version_code')},
        ),
        migrations.AddIndex(
            model_name='appscreenshot',
            index=models.Index(fields=['app', 'order'], name='desktop_app_app_id_58bd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['-downloaded_at'], name='desktop_app_downloa_a950d5_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['app_version', '-downloaded_at'], name='desktop_app_app_ver_7697a7_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['ip_address'], name='desktop_app_ip_addr_7e028c_idx'),
        ),
    ]
