# Generated by Django 5.2.1 on 2026-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_app_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='channel',
            field=models.CharField(choices=[('alpha', 'Alpha (Interne Tests)'), ('beta', 'Beta (Öffentliche Tests)'), ('production', 'Production (Stabile Version)')], db_index=True, default='production', max_length=20, verbose_name='Release Channel'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='Download-Zähler'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Dateigröße (Bytes)'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Nur aktive Versionen werden für Updates angeboten', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='is_current_for_channel',
            field=models.BooleanField(default=False, help_text='Markiert als aktuelle/empfohlene Version für diesen Channel', verbose_name='Aktuelle Version für Channel'),
        ),
        migrations.AlterField(
            model_name='desktopapp',
            name='is_public',
            field=models.BooleanField(default=False, help_text='App für alle sichtbar machen', verbose_name='Öffentlich'),
        ),
    ]
