from django.urls import path
from . import views
from .views_stats import render_stats
from .thunder_views import ServerStatusView, ServerStartView, ServerStopView, SetAutoShutdownView

app_name = 'video'

urlpatterns = [
    path('stats/', render_stats, name='render_stats'),
    path('', views.project_list, name='project_list'),
    path('new/', views.project_create, name='project_create'),
    path('<uuid:pk>/', views.project_detail, name='project_detail'),
    path('<uuid:pk>/delete/', views.project_delete, name='project_delete'),
    path('<uuid:pk>/character/add/', views.character_add, name='character_add'),
    path('character/<uuid:char_id>/delete/', views.character_delete, name='character_delete'),
    path('character/<uuid:char_id>/image-add/', views.character_image_add, name='character_image_add'),
    path('character-image/<uuid:image_id>/delete/', views.character_image_delete, name='character_image_delete'),
    path('<uuid:pk>/product/add/', views.product_add, name='product_add'),
    path('<uuid:pk>/product/delete/', views.product_delete, name='product_delete'),
    path('<uuid:pk>/still/add/', views.still_add, name='still_add'),
    path('<uuid:pk>/still/delete/', views.still_delete, name='still_delete'),
    path('<uuid:pk>/frame/generate/', views.frame_generate, name='frame_generate'),
    path('<uuid:pk>/frame/generate-flux/', views.frame_generate_flux, name='frame_generate_flux'),
    path("<uuid:pk>/frame/upload/", views.frame_upload, name="frame_upload"),
    path('frame/<uuid:frame_id>/update-type/', views.frame_update_type, name='frame_update_type'),
    path('frame/<uuid:frame_id>/delete/', views.frame_delete, name='frame_delete'),
    path('<uuid:pk>/scene/add/', views.scene_add, name='scene_add'),
    path('scene/<uuid:scene_id>/update-frames/', views.scene_update_frames, name='scene_update_frames'),
    path('scene/<uuid:scene_id>/update/', views.scene_update, name='scene_update'),
    path('scene/<uuid:scene_id>/frame-generate/', views.scene_frame_generate, name='scene_frame_generate'),
    path('scene/<uuid:scene_id>/pipeline/', views.scene_pipeline, name='scene_pipeline'),
    path('<uuid:pk>/pipeline-all/', views.project_pipeline_all, name='project_pipeline_all'),
    path('<uuid:pk>/update-music/', views.project_update_music, name='project_update_music'),
    path('<uuid:pk>/generate-music/', views.project_generate_music, name='project_generate_music'),
    path('<uuid:pk>/import-script/', views.project_import_script, name='project_import_script'),
    path('scene/<uuid:scene_id>/generate/', views.scene_generate, name='scene_generate'),
    path('<uuid:pk>/generate-all/', views.scene_generate_all, name='scene_generate_all'),
    path('scene/<uuid:pk>/thumb/<str:frame_type>/', views.thumbnail, name='thumbnail'),
    path('<uuid:pk>/status/', views.scene_status_api, name='scene_status'),
    path('server/status/', ServerStatusView.as_view(), name='thunder_status'),
    path('<uuid:pk>/download/', views.scene_download_all, name='scene_download_all'),
    path('scene/<uuid:scene_id>/cancel/', views.cancel_scene, name='cancel_scene'),
    path('scene/<uuid:scene_id>/voiceover/', views.scene_voiceover, name='scene_voiceover'),
    path('scene/<uuid:scene_id>/voiceover-preview/', views.scene_voiceover_preview, name='scene_voiceover_preview'),
    path('scene/<uuid:scene_id>/generate-music/', views.scene_generate_music, name='scene_generate_music'),
    path('scene/<uuid:scene_id>/upload-voice-ref/', views.scene_upload_voice_ref, name='scene_upload_voice_ref'),
    path('voice-clones/', views.voice_clones_list, name='voice_clones_list'),
    path('voice-clones/create/', views.voice_clones_create, name='voice_clones_create'),
    path('voice-clones/<uuid:clone_id>/delete/', views.voice_clones_delete, name='voice_clones_delete'),
    path('scene/<uuid:scene_id>/apply-voice-clone/', views.scene_apply_voice_clone, name='scene_apply_voice_clone'),
    path('scene/<uuid:scene_id>/apply-overlay/', views.scene_apply_overlay, name='scene_apply_overlay'),
    path('scene/<uuid:scene_id>/delete/', views.scene_delete, name='scene_delete'),
    path("thumb/video/generatedframe/<uuid:frame_id>/", views.frame_thumbnail, name="frame_thumbnail"),
    path("thumb/video/character/<uuid:char_id>/", views.character_thumbnail, name="character_thumbnail"),
    path("thumb/video/product/<uuid:prod_id>/", views.product_thumbnail, name="product_thumbnail"),
    path("thumb/video/stillimage/<uuid:still_id>/", views.stillimage_thumbnail, name="stillimage_thumbnail"),

    path("server/start/", ServerStartView.as_view(), name="thunder_start"),
    path("server/stop/", ServerStopView.as_view(), name="thunder_stop"),
    path("server/set-auto-shutdown/", SetAutoShutdownView.as_view(), name="set_auto_shutdown"),
    path('scene/<uuid:scene_id>/select-video/<uuid:video_id>/', views.select_scene_video, name='select_scene_video'),
    path('scene/<uuid:scene_id>/videos/', views.scene_videos, name='scene_videos'),
    path('video/<uuid:video_id>/delete/', views.delete_scene_video, name='delete_scene_video'),
    path('model-info/', views.model_info, name='model_info'),
]
