# Generated by Django 5.2.1 on 2025-12-11 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Beschreibung des Charakters für bessere KI-Prompts', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageforge_characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Charakter',
                'verbose_name_plural': 'Charaktere',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imageforge/characters/%Y/%m/', verbose_name='Bild')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptbild')),
                ('upload_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imageforge.character')),
            ],
            options={
                'verbose_name': 'Charakter-Bild',
                'verbose_name_plural': 'Charakter-Bilder',
                'ordering': ['upload_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_mode', models.CharField(choices=[('background', 'Nur Hintergrund'), ('product', 'Produkt auf Hintergrund'), ('character', 'Charakter in Szene'), ('character_product', 'Charakter + Produkt')], default='background', max_length=20, verbose_name='Modus')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='imageforge/products/%Y/%m/', verbose_name='Produktbild')),
                ('background_prompt', models.TextField(help_text='Beschreiben Sie den gewünschten Hintergrund oder die Szene', verbose_name='Szenen-Beschreibung')),
                ('aspect_ratio', models.CharField(choices=[('1:1', 'Square (1:1)'), ('4:3', 'Standard (4:3)'), ('16:9', 'Widescreen (16:9)'), ('9:16', 'Portrait (9:16)'), ('3:4', 'Portrait (3:4)')], default='1:1', max_length=10, verbose_name='Format')),
                ('lighting_style', models.CharField(choices=[('studio', 'Studio'), ('natural', 'Natürlich'), ('dramatic', 'Dramatisch'), ('soft', 'Soft Light'), ('golden_hour', 'Golden Hour'), ('high_key', 'High Key')], default='natural', max_length=20, verbose_name='Lichtstil')),
                ('perspective', models.CharField(choices=[('frontal', 'Frontal'), ('angle_45', '45° Winkel'), ('flat_lay', 'Flat Lay'), ('floating', 'Schwebend'), ('hero', 'Hero Shot'), ('macro', 'Makro')], default='frontal', max_length=20, verbose_name='Perspektive')),
                ('style_preset', models.CharField(choices=[('ecommerce', 'E-Commerce'), ('lifestyle', 'Lifestyle'), ('minimal', 'Minimalistisch'), ('luxury', 'Luxus'), ('nature', 'Natur'), ('tech', 'Tech')], default='lifestyle', max_length=20, verbose_name='Stil-Preset')),
                ('shadow_type', models.CharField(choices=[('none', 'Keiner'), ('soft', 'Weich'), ('hard', 'Hart'), ('reflection', 'Reflektion')], default='soft', max_length=20, verbose_name='Schatten')),
                ('color_mood', models.CharField(choices=[('warm', 'Warm'), ('neutral', 'Neutral'), ('cool', 'Kühl'), ('vibrant', 'Lebhaft')], default='neutral', max_length=20, verbose_name='Farbstimmung')),
                ('quality', models.CharField(choices=[('standard', 'Standard'), ('hd', 'HD')], default='standard', max_length=20, verbose_name='Qualität')),
                ('ai_model', models.CharField(choices=[('gemini-2.0-flash-preview-image-generation', 'Gemini 2.0 Flash'), ('imagen-3.0-generate-002', 'Imagen 3'), ('dall-e-3', 'DALL-E 3'), ('dall-e-2', 'DALL-E 2')], default='gemini-2.0-flash-preview-image-generation', max_length=50, verbose_name='KI-Modell')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='imageforge/generated/%Y/%m/', verbose_name='Generiertes Bild')),
                ('generation_prompt', models.TextField(blank=True, help_text='Der vollständige Prompt der an die KI gesendet wurde', verbose_name='Finaler Prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Generierungszeit (Sekunden)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorit')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='imageforge.character', verbose_name='Charakter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageforge_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildgenerierung',
                'verbose_name_plural': 'Bildgenerierungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Preset-Name')),
                ('settings', models.JSONField(default=dict, help_text='Alle Einstellungen als JSON gespeichert', verbose_name='Einstellungen')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard-Preset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageforge_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stil-Preset',
                'verbose_name_plural': 'Stil-Presets',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
