# Generated by Django 5.2.1 on 2025-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageforge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='overlay_text',
            field=models.CharField(blank=True, help_text='Optionaler Text der ins Bild eingebettet wird', max_length=200, verbose_name='Text im Bild'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='text_background_creative',
            field=models.BooleanField(default=False, help_text='Hintergrund kann kreative Formen haben (Banner, Ribbon, Splash, etc.)', verbose_name='Kreative Formen'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='text_background_enabled',
            field=models.BooleanField(default=False, help_text='Text wird auf einem farblich passenden Hintergrund-Element platziert', verbose_name='Text auf Hintergrund'),
        ),
    ]
