# Generated by Django 5.2.1 on 2025-12-15 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageforge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegeneration',
            name='generation_mode',
            field=models.CharField(choices=[('background', 'Nur Hintergrund'), ('product', 'Produkt auf Hintergrund'), ('character', 'Charakter in Szene'), ('character_product', 'Charakter + Produkt'), ('mockup_text', 'Produkt-Mockup mit Text')], default='background', max_length=20, verbose_name='Modus'),
        ),
        migrations.CreateModel(
            name='ProductMockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Mockup-Name')),
                ('product_image', models.ImageField(upload_to='imageforge/mockups/products/%Y/%m/', verbose_name='Original-Produktbild')),
                ('style_reference_image', models.ImageField(blank=True, help_text='Beispielbild das zeigt wie die Beschriftung aussehen soll', null=True, upload_to='imageforge/mockups/style_refs/%Y/%m/', verbose_name='Stil-Referenzbild')),
                ('text_content', models.CharField(max_length=200, verbose_name='Text/Beschriftung')),
                ('text_application_type', models.CharField(choices=[('gravur', 'Gravur (Eingraviert)'), ('druck', 'Druck'), ('praegung', 'Prägung'), ('relief', 'Relief')], default='druck', max_length=20, verbose_name='Beschriftungsart')),
                ('text_position', models.CharField(choices=[('center', 'Mitte'), ('top', 'Oben'), ('bottom', 'Unten'), ('custom', 'Automatisch')], default='center', max_length=20, verbose_name='Text-Position')),
                ('font_style', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Klassisch'), ('script', 'Schreibschrift'), ('bold', 'Fett'), ('minimal', 'Minimalistisch')], default='modern', max_length=20, verbose_name='Schriftstil')),
                ('text_color_hint', models.CharField(blank=True, help_text='z.B. gold, silber, schwarz, weiß', max_length=50, verbose_name='Farbhinweis')),
                ('text_size_hint', models.CharField(choices=[('small', 'Klein'), ('medium', 'Mittel'), ('large', 'Groß')], default='medium', max_length=20, verbose_name='Textgröße')),
                ('mockup_image', models.ImageField(blank=True, null=True, upload_to='imageforge/mockups/generated/%Y/%m/', verbose_name='Generiertes Mockup')),
                ('ai_model', models.CharField(default='gemini-3-pro-image-preview', max_length=50, verbose_name='KI-Modell')),
                ('generation_prompt', models.TextField(blank=True, verbose_name='Generierungs-Prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Generierungszeit (Sekunden)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageforge_mockups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produkt-Mockup',
                'verbose_name_plural': 'Produkt-Mockups',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='mockup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_generations', to='imageforge.productmockup', verbose_name='Produkt-Mockup'),
        ),
    ]
