# Generated by Django 5.2.1 on 2026-01-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageforge', '0002_add_product_mockup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmockup',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text/Beschriftung'), ('motif', 'Motiv/Bild')], default='text', help_text='Text/Beschriftung oder Motiv/Bild', max_length=10, verbose_name='Inhalt-Typ'),
        ),
        migrations.AddField(
            model_name='productmockup',
            name='motif_image',
            field=models.ImageField(blank=True, help_text='Das Motiv/Bild das auf das Produkt soll', null=True, upload_to='imageforge/mockups/motifs/%Y/%m/', verbose_name='Motiv-Bild'),
        ),
        migrations.AlterField(
            model_name='productmockup',
            name='text_content',
            field=models.CharField(blank=True, max_length=200, verbose_name='Text/Beschriftung'),
        ),
    ]
