# Generated by Django 5.2.1 on 2026-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageforge', '0004_add_design_mode_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegeneration',
            name='generation_mode',
            field=models.CharField(choices=[('background', 'Nur Hintergrund'), ('product', 'Produkt auf Hintergrund'), ('character', 'Charakter in Szene'), ('character_product', 'Charakter + Produkt'), ('mockup_text', 'Produkt-Mockup mit Text'), ('design', 'Kreatives Design')], default='background', max_length=20, verbose_name='Modus'),
        ),
    ]
