# Generated by Django 5.2.1 on 2026-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0046_radio_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationconfig',
            name='news_enabled',
            field=models.BooleanField(default=True, help_text='Tagesnews automatisch erzeugen und einplanen'),
        ),
        migrations.AddField(
            model_name='stationconfig',
            name='news_from_hour',
            field=models.PositiveSmallIntegerField(default=0, help_text='Erste Stunde (0-23)'),
        ),
        migrations.AddField(
            model_name='stationconfig',
            name='news_interval_h',
            field=models.PositiveSmallIntegerField(default=1, help_text='Abstand in Stunden (1 = jede Stunde)'),
        ),
        migrations.AddField(
            model_name='stationconfig',
            name='news_minute',
            field=models.PositiveSmallIntegerField(default=50, help_text='Minute der Stunde, zu der die News laufen (z.B. 50 = 10 vor voll)'),
        ),
        migrations.AddField(
            model_name='stationconfig',
            name='news_to_hour',
            field=models.PositiveSmallIntegerField(default=23, help_text='Letzte Stunde (0-23)'),
        ),
    ]
