# Generated by Django 5.2.1 on 2026-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0047_stationconfig_news_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationconfig',
            name='news_intro_enabled',
            field=models.BooleanField(default=True, help_text='Festes Intro vor jede Tagesnews mischen'),
        ),
    ]
