# Generated by Django 5.2.1 on 2026-06-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0048_stationconfig_news_intro_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleditem',
            name='topic',
            field=models.TextField(blank=True, default='', help_text='Themenhinweis(e) für GLM; mehrere kommagetrennt (News-Termine)'),
        ),
    ]
