# Generated by Django 5.2.1 on 2026-06-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0049_alter_scheduleditem_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listeners', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
