# Generated by Django 5.2.1 on 2025-09-22 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='DIN-Code (z.B. A1, B2, C1)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Bezeichnung des Straßentyps', max_length=100)),
                ('description', models.TextField(help_text='Detaillierte Beschreibung')),
                ('category', models.CharField(choices=[('motorway', 'Autobahnen und Kraftfahrstraßen'), ('main_road', 'Hauptverkehrsstraßen'), ('collector', 'Sammelstraßen'), ('residential', 'Erschließungsstraßen'), ('pedestrian', 'Fußgängerwege'), ('cycle', 'Radwege'), ('conflict', 'Konfliktbereiche')], max_length=20)),
                ('lighting_type', models.CharField(choices=[('M', 'M-Klassen (Kraftfahrzeugverkehr)'), ('P', 'P-Klassen (Fußgänger/Radfahrer)'), ('A', 'A-Klassen (Konfliktbereiche)'), ('Mixed', 'Gemischte Klassen')], max_length=20)),
                ('icon', models.CharField(default='road', help_text='Font Awesome Icon Name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Straßentyp',
                'verbose_name_plural': 'Straßentypen',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LightingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name des Projekts', max_length=200)),
                ('traffic_volume', models.CharField(blank=True, choices=[('low', 'Niedrig (<500 Kfz/h)'), ('medium', 'Mittel (500-1500 Kfz/h)'), ('high', 'Hoch (>1500 Kfz/h)')], max_length=20, null=True)),
                ('speed_limit', models.CharField(blank=True, choices=[('30', '≤30 km/h'), ('50', '31-50 km/h'), ('80', '51-80 km/h'), ('unlimited', '>80 km/h')], max_length=20, null=True)),
                ('ambient_brightness', models.CharField(choices=[('E0', 'E0 - Niedrig'), ('E1', 'E1 - Mittel'), ('E2', 'E2 - Hoch')], default='E0', max_length=20)),
                ('usage_intensity', models.CharField(blank=True, choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], help_text='Für Fußgänger-/Radwege', max_length=20, null=True)),
                ('safety_requirements', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Erhöht'), ('high', 'Hoch')], default='normal', max_length=20)),
                ('special_conditions', models.TextField(blank=True, help_text='Besondere örtliche Gegebenheiten')),
                ('recommended_class', models.CharField(blank=True, help_text='Empfohlene Beleuchtungsklasse', max_length=10)),
                ('luminance_value', models.DecimalField(blank=True, decimal_places=2, help_text='Leuchtdichte in cd/m²', max_digits=5, null=True)),
                ('illuminance_value', models.DecimalField(blank=True, decimal_places=2, help_text='Beleuchtungsstärke in lx', max_digits=5, null=True)),
                ('uniformity_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Gleichmäßigkeitsverhältnis', max_digits=4, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Zusätzliche Notizen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_classifications', to=settings.AUTH_USER_MODEL)),
                ('road_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting_classification.roadtype')),
            ],
            options={
                'verbose_name': 'Beleuchtungsklassifizierung',
                'verbose_name_plural': 'Beleuchtungsklassifizierungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
