# Generated by Django 5.2.1 on 2025-09-22 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting_classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_type', models.CharField(choices=[('traffic_volume', 'Verkehrsstärke'), ('speed', 'Geschwindigkeit'), ('complexity', 'Komplexität der Verkehrssituation'), ('ambient_light', 'Umgebungshelligkeit'), ('user_category', 'Nutzer-Kategorie'), ('conflict_frequency', 'Konflikthäufigkeit'), ('parking', 'Parken am Fahrbahnrand'), ('intersection', 'Kreuzungen und Einmündungen')], max_length=50)),
                ('name', models.CharField(help_text='Bezeichnung des Kriteriums', max_length=200)),
                ('description', models.TextField(help_text='Beschreibung gemäß Norm')),
                ('points', models.IntegerField(help_text='Punktwert nach DIN EN 13201')),
                ('order', models.PositiveIntegerField(default=0, help_text='Reihenfolge in der Tabelle')),
                ('is_active', models.BooleanField(default=True)),
                ('road_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='lighting_classification.roadtype')),
            ],
            options={
                'verbose_name': 'Klassifizierungskriterium',
                'verbose_name_plural': 'Klassifizierungskriterien',
                'ordering': ['road_type', 'criteria_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, help_text='Gesamtpunktzahl')),
                ('calculated_class', models.CharField(blank=True, help_text='Berechnete Beleuchtungsklasse', max_length=10)),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring', to='lighting_classification.lightingclassification')),
                ('selected_criteria', models.ManyToManyField(blank=True, to='lighting_classification.classificationcriteria')),
            ],
            options={
                'verbose_name': 'Klassifizierungsbewertung',
                'verbose_name_plural': 'Klassifizierungsbewertungen',
            },
        ),
    ]
