# Generated by Django 5.2.1 on 2025-09-23 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting_classification', '0002_classificationcriteria_classificationscoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DINClassificationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('speed_limit', 'Zulässige Geschwindigkeit'), ('junction_density', 'Knotenpunktdichte'), ('junction_count', 'Anzahl Knotenpunkte'), ('lanes_per_direction', 'Anzahl Fahrstreifen je Richtung'), ('direction_separation', 'Trennung der Richtungsfahrbahnen'), ('traffic_volume', 'Verkehrsaufkommen'), ('traffic_composition', 'Verkehrsart/Zusammensetzung'), ('operation_type', 'Betriebsart'), ('cycle_traffic_flow', 'Radverkehrsfluss'), ('pedestrian_traffic_flow', 'Verkehrsfluss Fußgänger'), ('ambient_luminance', 'Leuchtdichte der Umgebung'), ('parking_allowed', 'Parkende Fahrzeuge'), ('adjacent_areas_relation', 'Lagebezug zu angrenzenden Verkehrsflächen'), ('walking_directions', 'Gehrichtungen'), ('stay_function', 'Aufenthaltsfunktion'), ('face_recognition', 'Gesichtserkennung'), ('elevated_requirements', 'Erhöhte Anforderungen')], max_length=50)),
                ('name', models.CharField(help_text='Parametername gemäß DIN', max_length=200)),
                ('is_variable', models.BooleanField(choices=[(False, 'Auswahlparameter (fest)'), (True, 'Variable Parameter (adaptive Beleuchtung)')], help_text='Variable Parameter können zeitabhängig verändert werden')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DIN Klassifizierungsparameter',
                'verbose_name_plural': 'DIN Klassifizierungsparameter',
                'ordering': ['road_category', 'is_variable', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DINRoadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('AS', 'Autobahnen'), ('LS', 'Landstraßen (außerorts)'), ('HS', 'Hauptverkehrsstraßen'), ('ES', 'Erschließungsstraßen'), ('RADWEG', 'Radwege'), ('GEHWEG', 'Gehwege'), ('PLATZ', 'Sonstige Verkehrsflächen/Plätze')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lighting_class_type', models.CharField(choices=[('M', 'M-Klassen (Motorisierter Verkehr)'), ('C', 'C-Klassen (Konfliktbereiche)'), ('P', 'P-Klassen (Fußgänger/Radfahrer)')], max_length=1)),
                ('table_number', models.IntegerField(help_text='Tabellennummer in DIN 13201-1')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DIN Straßenkategorie',
                'verbose_name_plural': 'DIN Straßenkategorien',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='DINLightingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('time_period', models.CharField(choices=[('dt0', 'Δt₀ (Bemessungsbeleuchtungsklasse)'), ('dt1', 'Δt₁ (Adaptive Beleuchtung 1)'), ('dt2', 'Δt₂ (Adaptive Beleuchtung 2)')], default='dt0', max_length=10)),
                ('time_period_description', models.CharField(blank=True, help_text="z.B. '05:00-20:00 Uhr'", max_length=200)),
                ('total_weighting_value', models.IntegerField(default=0, help_text='Summe VWS')),
                ('calculated_lighting_class', models.CharField(blank=True, help_text='Berechnete Klasse (M/C/P)', max_length=10)),
                ('maintenance_luminance', models.DecimalField(blank=True, decimal_places=2, help_text='Wartungswert Leuchtdichte [cd/m²]', max_digits=5, null=True)),
                ('maintenance_illuminance', models.DecimalField(blank=True, decimal_places=2, help_text='Wartungswert Beleuchtungsstärke [lx]', max_digits=5, null=True)),
                ('overall_uniformity_uo', models.DecimalField(blank=True, decimal_places=3, help_text='Gesamtgleichmäßigkeit Uo', max_digits=4, null=True)),
                ('longitudinal_uniformity_ul', models.DecimalField(blank=True, decimal_places=3, help_text='Längsgleichmäßigkeit Ul', max_digits=4, null=True)),
                ('threshold_increment_ti', models.DecimalField(blank=True, decimal_places=1, help_text='Schwellenwerterhöhung TI [%]', max_digits=4, null=True)),
                ('edge_illuminance_ratio_rei', models.DecimalField(blank=True, decimal_places=2, help_text='Randbeleuchtungsstärkeverhältnis REI', max_digits=4, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('calculation_pending', 'Berechnung ausstehend'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('road_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting_classification.dinroadcategory')),
            ],
            options={
                'verbose_name': 'DIN Beleuchtungsklassifizierung',
                'verbose_name_plural': 'DIN Beleuchtungsklassifizierungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DINLightingClassStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('M', 'M-Klassen'), ('C', 'C-Klassen'), ('P', 'P-Klassen')], max_length=1)),
                ('class_number', models.IntegerField()),
                ('maintenance_luminance', models.DecimalField(blank=True, decimal_places=2, help_text='Wartungswert Leuchtdichte [cd/m²]', max_digits=5, null=True)),
                ('maintenance_illuminance', models.DecimalField(blank=True, decimal_places=2, help_text='Wartungswert Beleuchtungsstärke [lx]', max_digits=5, null=True)),
                ('overall_uniformity_uo', models.DecimalField(decimal_places=3, help_text='Gesamtgleichmäßigkeit Uo', max_digits=4)),
                ('longitudinal_uniformity_ul', models.DecimalField(blank=True, decimal_places=3, help_text='Längsgleichmäßigkeit Ul (nur M-Klassen)', max_digits=4, null=True)),
                ('threshold_increment_ti', models.DecimalField(blank=True, decimal_places=1, help_text='Schwellenwerterhöhung TI [%] (nur M-Klassen)', max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'DIN Beleuchtungsklassen-Standard',
                'verbose_name_plural': 'DIN Beleuchtungsklassen-Standards',
                'ordering': ['class_type', 'class_number'],
                'unique_together': {('class_type', 'class_number')},
            },
        ),
        migrations.CreateModel(
            name='DINParameterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='Auswahltext gemäß DIN', max_length=200)),
                ('weighting_value', models.IntegerField(help_text='Wichtungswert (VW) gemäß DIN')),
                ('choice_code', models.CharField(help_text='Eindeutiger Code für die Auswahl', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lighting_classification.dinclassificationparameter')),
            ],
            options={
                'verbose_name': 'DIN Parameter Auswahlmöglichkeit',
                'verbose_name_plural': 'DIN Parameter Auswahlmöglichkeiten',
                'ordering': ['parameter', 'order'],
                'unique_together': {('parameter', 'choice_code')},
            },
        ),
        migrations.AddField(
            model_name='dinclassificationparameter',
            name='road_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lighting_classification.dinroadcategory'),
        ),
        migrations.CreateModel(
            name='DINAdaptiveLightingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('adaptive_dt1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_set_as_dt1', to='lighting_classification.dinlightingclassification')),
                ('adaptive_dt2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_set_as_dt2', to='lighting_classification.dinlightingclassification')),
                ('base_classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_set_as_base', to='lighting_classification.dinlightingclassification')),
                ('road_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting_classification.dinroadcategory')),
            ],
            options={
                'verbose_name': 'DIN Adaptive Beleuchtungsgruppe',
                'verbose_name_plural': 'DIN Adaptive Beleuchtungsgruppen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dinclassificationparameter',
            unique_together={('road_category', 'parameter_type')},
        ),
        migrations.CreateModel(
            name='DINSelectedParameterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting_classification.dinparameterchoice')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='lighting_classification.dinlightingclassification')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting_classification.dinclassificationparameter')),
            ],
            options={
                'verbose_name': 'DIN Ausgewählter Parameter',
                'verbose_name_plural': 'DIN Ausgewählte Parameter',
                'unique_together': {('classification', 'parameter')},
            },
        ),
    ]
