# Generated by Django 5.2.1 on 2025-09-25 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting_classification', '0003_dinclassificationparameter_dinroadcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationcriteria',
            name='points',
            field=models.IntegerField(help_text='Punktwert nach DIN 13201-1:2021-09'),
        ),
        migrations.AlterField(
            model_name='dinlightingclassification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
