# Generated by Django 5.2.1 on 2025-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektname', models.CharField(default='My Project', max_length=200)),
                ('strompreis', models.FloatField(default=0.3)),
                ('neue_anlage_exists', models.BooleanField(default=True)),
                ('alt_hersteller', models.CharField(blank=True, max_length=100)),
                ('alt_leistung', models.FloatField(default=0)),
                ('alt_anzahl', models.IntegerField(default=0)),
                ('alt_h_pro_t', models.FloatField(default=0)),
                ('alt_t_pro_j', models.IntegerField(default=0)),
                ('neu_hersteller', models.CharField(default='taras_yuzkiv', max_length=100)),
                ('neu_leistung', models.FloatField(default=0)),
                ('neu_anzahl', models.IntegerField(default=0)),
                ('neu_h_pro_t', models.FloatField(default=0)),
                ('neu_t_pro_j', models.IntegerField(default=0)),
                ('neu_anschaffungskosten', models.FloatField(default=0)),
                ('bewegungsmelder', models.BooleanField(default=False)),
                ('abwesenheitswert', models.IntegerField(default=20)),
                ('anwesenheitswert', models.IntegerField(default=100)),
                ('frequentierung_stunden', models.FloatField(default=4.0)),
                ('tageslicht', models.BooleanField(default=False)),
                ('reduzierungs_niveau', models.FloatField(default=40)),
                ('amortisationszeitraum_in_jahren', models.FloatField(blank=True, null=True)),
                ('ersparnis_alt_neu', models.FloatField(blank=True, null=True)),
                ('gesamtkosten_mit_lms', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
