# Generated by Django 5.2.1 on 2025-09-25 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortization_calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firmenname', models.CharField(max_length=200, verbose_name='Firmenname')),
                ('projektname', models.CharField(max_length=200, verbose_name='Projektname')),
                ('strompreis', models.FloatField(default=0.3, verbose_name='Strompreis (€/kWh)')),
                ('kontakt_name', models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner')),
                ('kontakt_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('kontakt_telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('anlagen_typ', models.IntegerField(choices=[(1, 'Industriebeleuchtung'), (2, 'Straßenbeleuchtung'), (3, 'Kundenspezifisch')], default=1, verbose_name='Anlagentyp')),
                ('neue_anlage_vorhanden', models.BooleanField(default=True, verbose_name='Bestandsanlage vorhanden?')),
                ('alt_hersteller', models.CharField(blank=True, max_length=200, verbose_name='Hersteller (Bestand)')),
                ('alt_modell', models.CharField(blank=True, max_length=200, verbose_name='Modell (Bestand)')),
                ('alt_leistung', models.FloatField(default=0, verbose_name='Leistung pro Leuchte in W (Bestand)')),
                ('alt_anzahl', models.IntegerField(default=0, verbose_name='Anzahl Leuchten (Bestand)')),
                ('alt_stunden_pro_tag', models.FloatField(default=0, verbose_name='Betriebsstunden pro Tag (Bestand)')),
                ('alt_tage_pro_jahr', models.IntegerField(default=250, verbose_name='Betriebstage pro Jahr (Bestand)')),
                ('alt_wartungskosten', models.FloatField(default=0, verbose_name='Wartungskosten pro Jahr in € (Bestand)')),
                ('alt_laufende_kosten', models.FloatField(default=0, verbose_name='Weitere laufende Kosten pro Jahr in € (Bestand)')),
                ('neu_hersteller', models.CharField(default='SCHUCH', max_length=200, verbose_name='Hersteller (Neu)')),
                ('neu_modell', models.CharField(blank=True, max_length=200, verbose_name='Modell (Neu)')),
                ('neu_leistung', models.FloatField(default=0, verbose_name='Leistung pro Leuchte in W (Neu)')),
                ('neu_anzahl', models.IntegerField(default=0, verbose_name='Anzahl Leuchten (Neu)')),
                ('neu_stunden_pro_tag', models.FloatField(default=0, verbose_name='Betriebsstunden pro Tag (Neu)')),
                ('neu_tage_pro_jahr', models.IntegerField(default=250, verbose_name='Betriebstage pro Jahr (Neu)')),
                ('neu_anschaffungskosten_pro_stueck', models.FloatField(default=0, verbose_name='Anschaffungskosten pro Leuchte in €')),
                ('neu_installationskosten', models.FloatField(default=0, verbose_name='Installationskosten gesamt in €')),
                ('neu_wartungskosten', models.FloatField(default=0, verbose_name='Wartungskosten pro Jahr in € (Neu)')),
                ('neu_laufende_kosten', models.FloatField(default=0, verbose_name='Weitere laufende Kosten pro Jahr in € (Neu)')),
                ('limas_aktiviert', models.BooleanField(default=False, verbose_name='Lichtmanagementsystem verwenden')),
                ('limas_grundkosten', models.FloatField(default=0, verbose_name='LIMAS Grundkosten in €')),
                ('limas_aufpreis_pro_leuchte', models.FloatField(default=0, verbose_name='LIMAS Aufpreis pro Leuchte in €')),
                ('bewegungsmelder_aktiviert', models.BooleanField(default=False, verbose_name='Bewegungsmelder verwenden')),
                ('bewegungsmelder_anzahl', models.IntegerField(default=0, verbose_name='Anzahl Leuchten mit Bewegungsmelder')),
                ('bewegungsmelder_abwesenheit_niveau', models.IntegerField(default=20, verbose_name='Beleuchtungsniveau bei Abwesenheit (%)')),
                ('bewegungsmelder_anwesenheit_niveau', models.IntegerField(default=100, verbose_name='Beleuchtungsniveau bei Anwesenheit (%)')),
                ('bewegungsmelder_frequentierung_stunden', models.FloatField(default=4, verbose_name='Frequentierung in Stunden')),
                ('bewegungsmelder_frequentierung_minuten', models.FloatField(default=0, verbose_name='Frequentierung zusätzliche Minuten')),
                ('bewegungsmelder_mehrkosten', models.FloatField(default=0, verbose_name='Mehrkosten Bewegungsmelder in €')),
                ('bewegungsmelder_fadein', models.IntegerField(default=5, verbose_name='Fade-In Zeit in Sekunden')),
                ('bewegungsmelder_fadeout', models.IntegerField(default=5, verbose_name='Fade-Out Zeit in Sekunden')),
                ('tageslicht_aktiviert', models.BooleanField(default=False, verbose_name='Tageslichtabhängige Regelung verwenden')),
                ('tageslicht_anzahl', models.IntegerField(default=0, verbose_name='Anzahl Leuchten mit Tageslichtregelung')),
                ('tageslicht_reduzierung_niveau', models.FloatField(default=40, verbose_name='Reduzierungsniveau bei Tageslicht (%)')),
                ('tageslicht_nutzung_stunden', models.FloatField(default=4, verbose_name='Tageslichtnutzung in Stunden')),
                ('tageslicht_nutzung_minuten', models.FloatField(default=0, verbose_name='Tageslichtnutzung zusätzliche Minuten')),
                ('tageslicht_mehrkosten', models.FloatField(default=0, verbose_name='Mehrkosten Tageslichtregelung in €')),
                ('kalender_aktiviert', models.BooleanField(default=False, verbose_name='Kalendersteuerung verwenden')),
                ('kalender_anzahl_ausschalttage', models.IntegerField(default=0, verbose_name='Anzahl Tage Ausschaltung (Feiertage etc.)')),
                ('verbrauch_alt_kwh_jahr', models.FloatField(blank=True, null=True, verbose_name='Verbrauch Bestand (kWh/Jahr)')),
                ('kosten_alt_jahr', models.FloatField(blank=True, null=True, verbose_name='Gesamtkosten Bestand (€/Jahr)')),
                ('verbrauch_neu_ohne_limas_kwh_jahr', models.FloatField(blank=True, null=True, verbose_name='Verbrauch Neu ohne LIMAS (kWh/Jahr)')),
                ('kosten_neu_ohne_limas_jahr', models.FloatField(blank=True, null=True, verbose_name='Kosten Neu ohne LIMAS (€/Jahr)')),
                ('verbrauch_neu_mit_limas_kwh_jahr', models.FloatField(blank=True, null=True, verbose_name='Verbrauch Neu mit LIMAS (kWh/Jahr)')),
                ('kosten_neu_mit_limas_jahr', models.FloatField(blank=True, null=True, verbose_name='Kosten Neu mit LIMAS (€/Jahr)')),
                ('ersparnis_neu_zu_alt_jahr', models.FloatField(blank=True, null=True, verbose_name='Ersparnis Neu zu Alt (€/Jahr)')),
                ('ersparnis_limas_jahr', models.FloatField(blank=True, null=True, verbose_name='Ersparnis durch LIMAS (€/Jahr)')),
                ('investitionskosten_gesamt', models.FloatField(blank=True, null=True, verbose_name='Gesamte Investitionskosten (€)')),
                ('investitionskosten_limas', models.FloatField(blank=True, null=True, verbose_name='Investitionskosten LIMAS (€)')),
                ('amortisation_neu_jahre', models.FloatField(blank=True, null=True, verbose_name='Amortisation Neue Anlage (Jahre)')),
                ('amortisation_neu_monate', models.FloatField(blank=True, null=True, verbose_name='Amortisation Neue Anlage (Monate)')),
                ('amortisation_limas_jahre', models.FloatField(blank=True, null=True, verbose_name='Amortisation LIMAS (Jahre)')),
                ('amortisation_limas_monate', models.FloatField(blank=True, null=True, verbose_name='Amortisation LIMAS (Monate)')),
                ('co2_emission_alt_kg_jahr', models.FloatField(blank=True, null=True, verbose_name='CO2 Emission Bestand (kg/Jahr)')),
                ('co2_emission_neu_ohne_limas_kg_jahr', models.FloatField(blank=True, null=True, verbose_name='CO2 Emission Neu ohne LIMAS (kg/Jahr)')),
                ('co2_emission_neu_mit_limas_kg_jahr', models.FloatField(blank=True, null=True, verbose_name='CO2 Emission Neu mit LIMAS (kg/Jahr)')),
                ('co2_ersparnis_kg_jahr', models.FloatField(blank=True, null=True, verbose_name='CO2 Ersparnis (kg/Jahr)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beleuchtungsberechnung',
                'verbose_name_plural': 'Beleuchtungsberechnungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
