# Generated by Django 5.2.1 on 2025-09-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortization_calculator', '0002_lighting_calculation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingcalculation',
            name='amortisation_gesamt_jahre',
            field=models.FloatField(blank=True, null=True, verbose_name='Amortisation Gesamt (Jahre)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='amortisation_gesamt_monate',
            field=models.FloatField(blank=True, null=True, verbose_name='Amortisation Gesamt (Monate)'),
        ),
    ]
