# Generated by Django 5.2.1 on 2025-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortization_calculator', '0003_lightingcalculation_amortisation_gesamt_jahre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingcalculation',
            name='neu_hersteller',
            field=models.CharField(default='', max_length=200, verbose_name='Hersteller (Neu)'),
        ),
    ]
