# Generated by Django 5.2.1 on 2025-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortization_calculator', '0004_remove_schuch_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightingcalculation',
            old_name='limas_aktiviert',
            new_name='lms_aktiviert',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='amortisation_limas_jahre',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='amortisation_limas_monate',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='co2_emission_neu_mit_limas_kg_jahr',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='co2_emission_neu_ohne_limas_kg_jahr',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='ersparnis_limas_jahr',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='investitionskosten_limas',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='kosten_neu_mit_limas_jahr',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='kosten_neu_ohne_limas_jahr',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='limas_aufpreis_pro_leuchte',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='limas_grundkosten',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='verbrauch_neu_mit_limas_kwh_jahr',
        ),
        migrations.RemoveField(
            model_name='lightingcalculation',
            name='verbrauch_neu_ohne_limas_kwh_jahr',
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='amortisation_lms_jahre',
            field=models.FloatField(blank=True, null=True, verbose_name='Amortisation LMS (Jahre)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='amortisation_lms_monate',
            field=models.FloatField(blank=True, null=True, verbose_name='Amortisation LMS (Monate)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='co2_emission_neu_mit_lms_kg_jahr',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 Emission Neu mit LMS (kg/Jahr)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='co2_emission_neu_ohne_lms_kg_jahr',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 Emission Neu ohne LMS (kg/Jahr)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='ersparnis_lms_jahr',
            field=models.FloatField(blank=True, null=True, verbose_name='Ersparnis durch LMS (€/Jahr)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='investitionskosten_lms',
            field=models.FloatField(blank=True, null=True, verbose_name='Investitionskosten LMS (€)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='kosten_neu_mit_lms_jahr',
            field=models.FloatField(blank=True, null=True, verbose_name='Kosten Neu mit LMS (€/Jahr)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='kosten_neu_ohne_lms_jahr',
            field=models.FloatField(blank=True, null=True, verbose_name='Kosten Neu ohne LMS (€/Jahr)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='lms_aufpreis_pro_leuchte',
            field=models.FloatField(default=0, verbose_name='LMS Aufpreis pro Leuchte in €'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='lms_grundkosten',
            field=models.FloatField(default=0, verbose_name='LMS Grundkosten in €'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='verbrauch_neu_mit_lms_kwh_jahr',
            field=models.FloatField(blank=True, null=True, verbose_name='Verbrauch Neu mit LMS (kWh/Jahr)'),
        ),
        migrations.AddField(
            model_name='lightingcalculation',
            name='verbrauch_neu_ohne_lms_kwh_jahr',
            field=models.FloatField(blank=True, null=True, verbose_name='Verbrauch Neu ohne LMS (kWh/Jahr)'),
        ),
    ]
