# Generated by Django 5.2.1 on 2025-12-14 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopify_manager', '0005_convert_additional_tables_to_utf8mb4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPrepProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Projekttitel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('step1', 'Keywords eingegeben'), ('step2', 'Recherche abgeschlossen'), ('step3', 'Content erstellt'), ('step4', 'Bilder erstellt'), ('step5', 'Diagramm erstellt'), ('step6', 'Video-Skript erstellt'), ('step7', 'Bereit zum Export'), ('completed', 'Exportiert'), ('published', 'Veröffentlicht')], default='draft', max_length=20)),
                ('main_keyword', models.CharField(blank=True, max_length=255, verbose_name='Hauptkeyword')),
                ('secondary_keywords', models.JSONField(blank=True, default=list, verbose_name='Sekundäre Keywords')),
                ('research_data', models.JSONField(blank=True, default=dict, help_text='Top-Themen, verwandte Keywords, Leserfragen', verbose_name='Recherche-Daten')),
                ('outline', models.JSONField(blank=True, default=list, help_text='H2-Überschriften und Struktur', verbose_name='Gliederung')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO-Titel')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta-Beschreibung')),
                ('summary', models.TextField(blank=True, verbose_name='Zusammenfassung')),
                ('content_intro', models.TextField(blank=True, verbose_name='Einleitung (~800 Wörter)')),
                ('content_main', models.TextField(blank=True, verbose_name='Hauptteil (~800 Wörter)')),
                ('content_tips', models.TextField(blank=True, verbose_name="Tipps & Do's/Don'ts (~800 Wörter)")),
                ('faqs', models.JSONField(blank=True, default=list, help_text='Liste von {question, answer} Objekten', verbose_name='FAQs')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='blogprep/images/', verbose_name='Titelbild')),
                ('title_image_prompt', models.TextField(blank=True, verbose_name='Titelbild-Prompt')),
                ('section_images', models.JSONField(blank=True, default=list, help_text='Liste von {section, image_path, prompt} Objekten', verbose_name='Abschnittsbilder')),
                ('skip_diagram', models.BooleanField(default=False, verbose_name='Diagramm überspringen')),
                ('diagram_type', models.CharField(blank=True, choices=[('bar', 'Balkendiagramm'), ('pie', 'Tortendiagramm'), ('line', 'Liniendiagramm'), ('comparison', 'Vergleichstabelle'), ('flow', 'Flussdiagramm'), ('timeline', 'Zeitstrahl')], max_length=20, verbose_name='Diagrammtyp')),
                ('diagram_data', models.JSONField(blank=True, default=dict, verbose_name='Diagramm-Daten')),
                ('diagram_image', models.ImageField(blank=True, null=True, upload_to='blogprep/diagrams/', verbose_name='Diagramm-Bild')),
                ('skip_video', models.BooleanField(default=False, verbose_name='Video-Skript überspringen')),
                ('video_duration', models.IntegerField(default=5, verbose_name='Video-Länge (Minuten)')),
                ('video_script', models.TextField(blank=True, verbose_name='Video-Skript')),
                ('shopify_article_id', models.CharField(blank=True, max_length=50, verbose_name='Shopify Article ID')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='Exportiert am')),
                ('full_html_content', models.TextField(blank=True, verbose_name='Vollständiger HTML-Content')),
                ('shopify_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogprep_projects', to='shopify_manager.shopifyblog', verbose_name='Shopify Blog')),
                ('shopify_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogprep_projects', to='shopify_manager.shopifystore', verbose_name='Shopify Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogprep_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BlogPrep Projekt',
                'verbose_name_plural': 'BlogPrep Projekte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPrepGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('research', 'Web-Recherche'), ('outline', 'Gliederung'), ('content_intro', 'Einleitung'), ('content_main', 'Hauptteil'), ('content_tips', 'Tipps'), ('faqs', 'FAQs'), ('seo', 'SEO-Meta'), ('image_title', 'Titelbild'), ('image_section', 'Abschnittsbild'), ('diagram', 'Diagramm'), ('video_script', 'Video-Skript')], max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='blogprep.blogprepproject')),
            ],
            options={
                'verbose_name': 'Generierungs-Log',
                'verbose_name_plural': 'Generierungs-Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPrepSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Unternehmensname')),
                ('company_description', models.TextField(blank=True, help_text='Beschreibe dein Unternehmen, seine Geschichte und Werte', verbose_name='Unternehmensbeschreibung')),
                ('company_expertise', models.TextField(blank=True, help_text='In welchen Bereichen bist du/ist dein Unternehmen Experte?', verbose_name='Fachgebiete & Expertise')),
                ('writing_style', models.CharField(choices=[('du', 'Du-Form (persönlich, nahbar)'), ('sie', 'Sie-Form (formell, professionell)'), ('neutral', 'Neutral (ohne direkte Anrede)')], default='du', max_length=20, verbose_name='Schreibstil')),
                ('product_info', models.TextField(blank=True, help_text='Beschreibe deine Hauptprodukte oder Dienstleistungen', verbose_name='Produktinformationen')),
                ('product_links', models.JSONField(blank=True, default=list, help_text='URLs zu deinen Produktseiten (werden automatisch analysiert)', verbose_name='Produktlinks')),
                ('scraped_product_data', models.JSONField(blank=True, default=dict, verbose_name='Extrahierte Produktdaten')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude')], default='openai', max_length=20, verbose_name='KI-Anbieter (Text)')),
                ('ai_model', models.CharField(default='gpt-4o', max_length=50, verbose_name='KI-Modell')),
                ('image_provider', models.CharField(choices=[('gemini', 'Google Gemini/Imagen'), ('dalle', 'OpenAI DALL-E'), ('ideogram', 'Ideogram')], default='gemini', max_length=20, verbose_name='KI-Anbieter (Bilder)')),
                ('image_model', models.CharField(default='imagen-3.0-generate-002', max_length=50, verbose_name='Bild-Modell')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogprep_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BlogPrep Einstellung',
                'verbose_name_plural': 'BlogPrep Einstellungen',
            },
        ),
    ]
