# Generated by Django 5.2.1 on 2025-12-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogprep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogprepproject',
            name='video_duration',
            field=models.FloatField(default=5, help_text='0.25 = 15 Sek, 0.5 = 30 Sek, 1 = 1 Min', verbose_name='Video-Länge (Minuten)'),
        ),
        migrations.AlterField(
            model_name='blogprepsettings',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='KI-Anbieter (Text)'),
        ),
        migrations.AlterField(
            model_name='blogprepsettings',
            name='image_model',
            field=models.CharField(default='gemini-2.5-flash-image', max_length=50, verbose_name='Bild-Modell'),
        ),
        migrations.AlterField(
            model_name='blogprepsettings',
            name='image_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('dalle', 'OpenAI DALL-E')], default='gemini', max_length=20, verbose_name='KI-Anbieter (Bilder)'),
        ),
    ]
