# Generated by Django 5.2.1 on 2025-12-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogprep', '0002_video_duration_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogprepproject',
            name='content_intro',
            field=models.TextField(blank=True, verbose_name='Einleitung (~400 Wörter)'),
        ),
        migrations.AlterField(
            model_name='blogprepproject',
            name='content_main',
            field=models.TextField(blank=True, verbose_name='Hauptteil (~600 Wörter)'),
        ),
        migrations.AlterField(
            model_name='blogprepproject',
            name='content_tips',
            field=models.TextField(blank=True, verbose_name="Tipps & Do's/Don'ts (~600 Wörter)"),
        ),
    ]
