# Generated by Django 5.2.1 on 2025-12-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogprep', '0003_alter_blogprepproject_content_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogprepproject',
            name='seo_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Ergebnisse der SEO-Analyse (Keyword-Dichte, Bild-SEO, etc.)', verbose_name='SEO-Analyse'),
        ),
        migrations.AlterField(
            model_name='blogprepgenerationlog',
            name='step',
            field=models.CharField(choices=[('research', 'Web-Recherche'), ('internal_links', 'Interne Verlinkung'), ('outline', 'Gliederung'), ('content_intro', 'Einleitung'), ('content_main', 'Hauptteil'), ('content_tips', 'Tipps'), ('faqs', 'FAQs'), ('seo', 'SEO-Meta'), ('image_title', 'Titelbild'), ('image_section', 'Abschnittsbild'), ('diagram', 'Diagramm'), ('video_script', 'Video-Skript')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blogprepproject',
            name='content_intro',
            field=models.TextField(blank=True, verbose_name='Einleitung (~300 Wörter)'),
        ),
        migrations.AlterField(
            model_name='blogprepproject',
            name='content_main',
            field=models.TextField(blank=True, verbose_name='Hauptteil (~800 Wörter)'),
        ),
        migrations.AlterField(
            model_name='blogprepproject',
            name='content_tips',
            field=models.TextField(blank=True, verbose_name="Do's & Don'ts (~300 Wörter)"),
        ),
    ]
