# Generated by Django 5.2.1 on 2025-12-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogprep', '0004_add_seo_analysis_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogprepsettings',
            name='update_reminder_critical_days',
            field=models.PositiveIntegerField(default=365, help_text='Ab diesem Alter ist eine Aktualisierung dringend empfohlen', verbose_name='Kritisch (Tage)'),
        ),
        migrations.AddField(
            model_name='blogprepsettings',
            name='update_reminder_keyword_days',
            field=models.PositiveIntegerField(default=180, help_text='Kürzere Frist für Artikel mit zeitkritischen Keywords', verbose_name='Zeitkritisch (Tage)'),
        ),
        migrations.AddField(
            model_name='blogprepsettings',
            name='update_reminder_keywords',
            field=models.TextField(blank=True, default='2024,2025,aktuell,neu,jetzt,heute,dieses jahr', help_text='Komma-getrennte Liste von Keywords, die kürzere Fristen auslösen', verbose_name='Zeitkritische Keywords'),
        ),
        migrations.AddField(
            model_name='blogprepsettings',
            name='update_reminder_warning_days',
            field=models.PositiveIntegerField(default=270, help_text='Ab diesem Alter wird eine Warnung angezeigt', verbose_name='Warnung (Tage)'),
        ),
    ]
