# Generated by Django 5.2.1 on 2025-12-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogprep', '0005_add_update_reminder_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogprepproject',
            name='custom_update_days',
            field=models.PositiveIntegerField(blank=True, help_text='Leer = globale Einstellungen verwenden. Sonst: nach X Tagen als aktualisierungsbedürftig markieren', null=True, verbose_name='Update-Erinnerung (Tage)'),
        ),
    ]
