# Generated by Django 5.2.1 on 2026-04-21 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('mode', models.CharField(choices=[('rag', 'RAG (aus eigener Bibliothek)'), ('council', 'Council (mehrere Modelle)'), ('hybrid', 'Hybrid (RAG + Council)')], default='rag', max_length=16)),
                ('models_used', models.JSONField(blank=True, default=list, help_text='Liste der genutzten Modell-Namen')),
                ('answer', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list, help_text='Liste von {title, authors, year, filename, score, text, reference_id?}')),
                ('raw_responses', models.JSONField(blank=True, default=dict, help_text='Für Council-Mode: Rohantworten pro Modell')),
                ('error', models.TextField(blank=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forschungs-Anfrage',
                'verbose_name_plural': 'Forschungs-Anfragen',
                'ordering': ['-created_at'],
            },
        ),
    ]
