# Generated by Django 5.2.1 on 2026-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquery',
            name='total_cost_usd',
            field=models.FloatField(blank=True, help_text='Summe der API-Kosten in USD', null=True),
        ),
    ]
