# Generated by Django 5.2.1 on 2026-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchquery_total_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquery',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Wartet'), ('running', 'Läuft'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='done', help_text='Job-Status für asynchrone Verarbeitung', max_length=16),
        ),
    ]
