# Generated by Django 5.2.1 on 2026-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchquery_finished_at_researchquery_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquery',
            name='mode',
            field=models.CharField(choices=[('rag', 'RAG (aus eigener Bibliothek)'), ('council', 'Council (mehrere Modelle)'), ('council_edited', 'Council + Redakteur (Primär-Modell strukturiert)'), ('hybrid', 'Hybrid (RAG + Council)')], default='rag', max_length=16),
        ),
    ]
