# Generated by Django 5.2.1 on 2026-05-08 07:00

import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_researchquery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquery',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Wenn True, kann jeder mit dem share_token die Anfrage lesen.'),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='share_token',
            field=models.CharField(db_index=True, default=research.models._gen_share_token, max_length=32),
        ),
    ]
