# Generated by Django 5.2.1 on 2025-07-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('bild', models.ImageField(blank=True, null=True, upload_to='naturmacher/themen/')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': 'Themen',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('schwierigkeit', models.CharField(choices=[('anfaenger', 'Anfänger'), ('fortgeschritten', 'Fortgeschritten'), ('experte', 'Experte')], default='anfaenger', max_length=20)),
                ('dauer_minuten', models.PositiveIntegerField()),
                ('bild', models.ImageField(blank=True, null=True, upload_to='naturmacher/trainings/')),
                ('inhalt', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='naturmacher.thema')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
