# Generated by Django 5.2.1 on 2025-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturmacher', '0003_usertrainingnotizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='youtube_links',
            field=models.TextField(blank=True, help_text='YouTube-Links (einer pro Zeile)'),
        ),
    ]
