# Generated by Django 5.2.1 on 2025-07-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturmacher', '0004_training_youtube_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainingnotizen',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('handwriting', 'Handschrift')], default='text', max_length=20),
        ),
    ]
