# Generated by Django 5.2.1 on 2025-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturmacher', '0008_create_missing_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibalance',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('youtube', 'YouTube Data API')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('youtube', 'YouTube Data API')], max_length=20),
        ),
    ]
