# Generated by Django 5.2.1 on 2025-07-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturmacher', '0009_alter_apibalance_provider_alter_apiusagelog_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='ai_model_used',
            field=models.CharField(blank=True, help_text='KI-Modell, das zum Erstellen dieses Trainings verwendet wurde', max_length=100, null=True),
        ),
    ]
