# Generated by Django 5.2.1 on 2025-07-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturmacher', '0010_training_ai_model_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apibalance',
            name='api_key',
        ),
    ]
