# Generated by Django 5.2.1 on 2025-07-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturmacher', '0011_remove_apibalance_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibalance',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('youtube', 'YouTube Data API'), ('canva', 'Canva')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('youtube', 'YouTube Data API'), ('canva', 'Canva')], max_length=20),
        ),
        migrations.CreateModel(
            name='CanvaAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='Canva Client ID', max_length=100)),
                ('client_secret', models.CharField(blank=True, help_text='Canva Client Secret', max_length=200)),
                ('access_token', models.TextField(blank=True, help_text='OAuth Access Token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token Ablaufzeit', null=True)),
                ('brand_template_id', models.CharField(blank=True, help_text='Standard Brand Template ID', max_length=100)),
                ('folder_id', models.CharField(blank=True, help_text='Standard Ordner ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canva_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canva API Settings',
                'verbose_name_plural': 'Canva API Settings',
            },
        ),
    ]
