# Generated by Django 5.2.1 on 2025-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturmacher', '0013_thema_ersteller_thema_oeffentlich_themafreigabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='thema',
            name='sichtbarkeit',
            field=models.CharField(choices=[('public', 'Öffentlich - Alle Benutzer'), ('private', 'Privat - Nur Ersteller'), ('shared', 'Privat mit Freigaben - Ersteller + freigegebene Benutzer')], default='private', help_text='Bestimmt wer dieses Thema sehen kann', max_length=10),
        ),
    ]
