# Generated by Django 5.2.1 on 2026-01-13 19:30

import android_apk_manager.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='App-Name')),
                ('package_name', models.CharField(help_text='z.B. com.workloom.app', max_length=200, unique=True, verbose_name='Package-Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=android_apk_manager.models.upload_to_app_icon, verbose_name='App-Icon')),
                ('is_public', models.BooleanField(default=False, help_text='App für alle sichtbar machen', verbose_name='Öffentlich')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='android_apps', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
            ],
            options={
                'verbose_name': 'Android App',
                'verbose_name_plural': 'Android Apps',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(help_text='z.B. 1.2.0', max_length=50, verbose_name='Versionsname')),
                ('version_code', models.IntegerField(help_text='Interne Versionsnummer (Integer)', verbose_name='Versionscode')),
                ('apk_file', models.FileField(max_length=500, upload_to=android_apk_manager.models.upload_apk_to, verbose_name='APK-Datei')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('release_notes', models.TextField(blank=True, verbose_name='Release Notes / Changelog')),
                ('channel', models.CharField(choices=[('alpha', 'Alpha (Interne Tests)'), ('beta', 'Beta (Öffentliche Tests)'), ('production', 'Production (Stabile Version)')], db_index=True, default='production', max_length=20, verbose_name='Release Channel')),
                ('min_android_version', models.CharField(default='5.0', help_text='z.B. 5.0, 8.0, 10.0', max_length=10, verbose_name='Min. Android Version')),
                ('is_active', models.BooleanField(default=True, help_text='Nur aktive Versionen werden für Updates angeboten', verbose_name='Aktiv')),
                ('is_current_for_channel', models.BooleanField(default=False, help_text='Markiert als aktuelle/empfohlene Version für diesen Channel', verbose_name='Aktuelle Version für Channel')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download-Zähler')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='android_apk_manager.androidapp', verbose_name='App')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versionen',
                'ordering': ['-version_code'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('android_version', models.CharField(blank=True, max_length=50, verbose_name='Android Version')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='Gerätemodell')),
                ('download_completed', models.BooleanField(default=False)),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='android_apk_manager.appversion', verbose_name='App Version')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apk_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download-Log',
                'verbose_name_plural': 'Download-Logs',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='androidapp',
            index=models.Index(fields=['-updated_at'], name='android_apk_updated_e37231_idx'),
        ),
        migrations.AddIndex(
            model_name='androidapp',
            index=models.Index(fields=['package_name'], name='android_apk_package_59e84a_idx'),
        ),
        migrations.AddIndex(
            model_name='androidapp',
            index=models.Index(fields=['is_public'], name='android_apk_is_publ_80c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['app', 'channel', '-version_code'], name='android_apk_app_id_fa3972_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['app', 'is_current_for_channel'], name='android_apk_app_id_300d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['-uploaded_at'], name='android_apk_uploade_96c509_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together={('app', 'version_code')},
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['-downloaded_at'], name='android_apk_downloa_45cc31_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['app_version', '-downloaded_at'], name='android_apk_app_ver_916902_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['ip_address'], name='android_apk_ip_addr_8d785d_idx'),
        ),
    ]
