# Generated by Django 5.2.1 on 2026-02-03 09:11

import android_apk_manager.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_apk_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=android_apk_manager.models.upload_to_app_screenshot, verbose_name='Screenshot')),
                ('caption', models.CharField(blank=True, help_text='Optionale Beschreibung des Screenshots', max_length=200, verbose_name='Bildunterschrift')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kleinere Zahlen werden zuerst angezeigt', verbose_name='Reihenfolge')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='android_apk_manager.androidapp', verbose_name='App')),
            ],
            options={
                'verbose_name': 'App Screenshot',
                'verbose_name_plural': 'App Screenshots',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['app', 'order'], name='android_apk_app_id_fdc278_idx')],
            },
        ),
    ]
