# Generated by Django 5.2.1 on 2025-10-20 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrompterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bezeichnung für diesen Teleprompter-Text', max_length=200, verbose_name='Titel')),
                ('content', models.TextField(help_text='Der Text für den Teleprompter', verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_favorite', models.BooleanField(default=False, help_text='Als Favorit markieren', verbose_name='Favorit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompter_texts', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Teleprompter-Text',
                'verbose_name_plural': 'Teleprompter-Texte',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='myprompter__user_id_3c72e3_idx')],
            },
        ),
    ]
