# Generated by Django 5.2.1 on 2025-10-21 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('intent_type', models.CharField(blank=True, help_text='Search Intent (z.B. informational, commercial)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Beschreibung des Keywords')),
                ('priority', models.CharField(choices=[('high', 'Hoch'), ('medium', 'Mittel'), ('low', 'Niedrig')], default='medium', max_length=10)),
                ('is_done', models.BooleanField(default=False, help_text='Wurde das Keyword bereits bearbeitet?')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_done'], name='keyengine_s_user_id_3ef0e5_idx'), models.Index(fields=['user', 'priority'], name='keyengine_s_user_id_566496_idx'), models.Index(fields=['keyword'], name='keyengine_s_keyword_5c025b_idx')],
                'unique_together': {('user', 'keyword')},
            },
        ),
    ]
