# Generated by Django 5.2.1 on 2025-10-22 05:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyengine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('#10b981', 'Grün'), ('#3b82f6', 'Blau'), ('#8b5cf6', 'Lila'), ('#f59e0b', 'Orange'), ('#ef4444', 'Rot'), ('#ec4899', 'Pink'), ('#fbbf24', 'Gelb'), ('#06b6d4', 'Türkis')], default='#10b981', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archivierte Listen werden ausgeblendet')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='savedkeyword',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedkeyword',
            name='keyword_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='keyengine.keywordlist'),
        ),
        migrations.AlterUniqueTogether(
            name='savedkeyword',
            unique_together={('keyword_list', 'keyword')},
        ),
        migrations.AddIndex(
            model_name='savedkeyword',
            index=models.Index(fields=['keyword_list', 'is_done'], name='keyengine_s_keyword_9bd19a_idx'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_used_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='keyengine.keywordlist'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyengine_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='keywordlist',
            index=models.Index(fields=['user', 'is_archived'], name='keyengine_k_user_id_d0b75d_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordlist',
            index=models.Index(fields=['position'], name='keyengine_k_positio_a1ff54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordlist',
            unique_together={('user', 'name')},
        ),
    ]
