# Generated by Django 5.2.1 on 2025-10-22 05:29

from django.db import migrations


def migrate_keywords_to_default_lists(apps, schema_editor):
    """
    Erstellt für jeden User eine Standard-Liste und verschiebt alle Keywords dorthin
    """
    KeywordList = apps.get_model('keyengine', 'KeywordList')
    SavedKeyword = apps.get_model('keyengine', 'SavedKeyword')
    User = apps.get_model('accounts', 'CustomUser')

    # Hole alle User die Keywords haben
    users_with_keywords = SavedKeyword.objects.values_list('user_id', flat=True).distinct()

    for user_id in users_with_keywords:
        # Erstelle Default-Liste für diesen User
        default_list, created = KeywordList.objects.get_or_create(
            user_id=user_id,
            name='Meine Keywords',
            defaults={
                'color': '#10b981',  # Grün
                'description': 'Standard-Liste',
                'position': 0
            }
        )

        # Verschiebe alle Keywords dieses Users in die Default-Liste
        SavedKeyword.objects.filter(
            user_id=user_id,
            keyword_list__isnull=True
        ).update(keyword_list=default_list)


def reverse_migration(apps, schema_editor):
    """
    Reverse: Setze keyword_list auf NULL zurück
    """
    SavedKeyword = apps.get_model('keyengine', 'SavedKeyword')
    SavedKeyword.objects.all().update(keyword_list=None)


class Migration(migrations.Migration):

    dependencies = [
        ('keyengine', '0002_userpreference_keywordlist_and_more'),
        ('accounts', '__latest__'),  # Dependency auf CustomUser
    ]

    operations = [
        migrations.RunPython(migrate_keywords_to_default_lists, reverse_migration),
    ]
