# Generated by Django 5.2.1 on 2025-10-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyengine', '0003_migrate_keywords_to_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedkeyword',
            name='keyword_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='keyengine.keywordlist'),
        ),
    ]
