# Generated by Django 5.2.1 on 2026-02-04 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original-Dateiname')),
                ('file', models.FileField(upload_to='learnloom/pdfs/', verbose_name='PDF-Datei')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='learnloom/thumbnails/', verbose_name='Vorschaubild')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Seitenanzahl')),
                ('category', models.CharField(choices=[('book', 'Buch'), ('paper', 'Wissenschaftliches Paper'), ('article', 'Artikel'), ('other', 'Sonstiges')], default='book', max_length=20, verbose_name='Kategorie')),
                ('tags', models.CharField(blank=True, help_text='Kommagetrennte Tags', max_length=500, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt geöffnet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnloom_books', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'PDF-Buch',
                'verbose_name_plural': 'PDF-Bücher',
                'ordering': ['-last_opened_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Notizinhalt')),
                ('page_reference', models.PositiveIntegerField(blank=True, help_text='Optional: Bezug zu einer bestimmten Seite', null=True, verbose_name='Seitenbezug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learnloom.pdfbook', verbose_name='PDF-Buch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Notiz',
                'verbose_name_plural': 'Notizen',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=1, verbose_name='Aktuelle Seite')),
                ('last_scroll_position', models.FloatField(default=0, help_text='Scroll-Position in Prozent (0-100)', verbose_name='Scroll-Position')),
                ('zoom_level', models.FloatField(default=1.0, verbose_name='Zoom-Stufe')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learnloom.pdfbook', verbose_name='PDF-Buch')),
            ],
            options={
                'verbose_name': 'Lesefortschritt',
                'verbose_name_plural': 'Lesefortschritte',
            },
        ),
        migrations.CreateModel(
            name='TranslationHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.CharField(max_length=500, verbose_name='Originaltext (EN)')),
                ('translated_text', models.CharField(max_length=500, verbose_name='Übersetzung (DE)')),
                ('page_number', models.PositiveIntegerField(verbose_name='Seitennummer')),
                ('position_data', models.JSONField(blank=True, default=dict, help_text='JSON mit Positionsdaten für die Markierung im PDF', verbose_name='Positionsdaten')),
                ('source_language', models.CharField(default='en', max_length=10, verbose_name='Quellsprache')),
                ('target_language', models.CharField(default='de', max_length=10, verbose_name='Zielsprache')),
                ('translation_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='openai', max_length=20, verbose_name='Übersetzungs-Provider')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='learnloom.pdfbook', verbose_name='PDF-Buch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Übersetzungs-Markierung',
                'verbose_name_plural': 'Übersetzungs-Markierungen',
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_word', models.CharField(max_length=255, verbose_name='Englisch')),
                ('german_translation', models.CharField(max_length=255, verbose_name='Deutsch')),
                ('times_reviewed', models.PositiveIntegerField(default=0, verbose_name='Wiederholungen')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt wiederholt')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Gelernt')),
                ('page_reference', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seitenbezug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='learnloom.pdfbook', verbose_name='PDF-Buch')),
                ('from_highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_entries', to='learnloom.translationhighlight', verbose_name='Aus Markierung')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Vokabel',
                'verbose_name_plural': 'Vokabeln',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pdfbook',
            index=models.Index(fields=['user', '-created_at'], name='learnloom_p_user_id_2b629c_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfbook',
            index=models.Index(fields=['user', 'category'], name='learnloom_p_user_id_117570_idx'),
        ),
        migrations.AddIndex(
            model_name='translationhighlight',
            index=models.Index(fields=['book', 'page_number'], name='learnloom_t_book_id_684075_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('book', 'english_word')},
        ),
    ]
