# Generated by Django 5.2.1 on 2026-02-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnloom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbook',
            name='reading_status',
            field=models.CharField(choices=[('unread', 'Noch nicht gelesen'), ('reading', 'Gerade dabei'), ('completed', 'Bereits gelesen')], default='unread', max_length=20, verbose_name='Lesestatus'),
        ),
    ]
