# Generated by Django 5.2.1 on 2026-02-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnloom', '0002_add_reading_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfnote',
            name='marker_position',
            field=models.JSONField(blank=True, help_text='Position des Markers auf der Seite {x, y, page}', null=True, verbose_name='Marker-Position'),
        ),
    ]
