# Generated by Django 5.2.1 on 2026-02-04 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnloom', '0003_add_marker_position_to_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_text', models.TextField(verbose_name='Ausgewählter Text')),
                ('context_before', models.TextField(blank=True, verbose_name='Kontext davor')),
                ('context_after', models.TextField(blank=True, verbose_name='Kontext danach')),
                ('explanation', models.TextField(verbose_name='Erklärung')),
                ('page_number', models.PositiveIntegerField(verbose_name='Seitennummer')),
                ('position_data', models.JSONField(blank=True, default=dict, help_text='JSON mit Positionsdaten für die Markierung im PDF', verbose_name='Positionsdaten')),
                ('explanation_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='openai', max_length=20, verbose_name='Erklärungs-Provider')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='learnloom.pdfbook', verbose_name='PDF-Buch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Text-Erklärung',
                'verbose_name_plural': 'Text-Erklärungen',
                'ordering': ['page_number', 'created_at'],
                'indexes': [models.Index(fields=['book', 'page_number'], name='learnloom_t_book_id_074d8d_idx')],
            },
        ),
    ]
