# Generated by Django 5.2.1 on 2026-02-26 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnloom', '0005_add_reading_list_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAudioSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_type', models.CharField(choices=[('short', 'Kurzzusammenfassung'), ('section', 'Abschnitt')], max_length=10, verbose_name='Audio-Typ')),
                ('section_index', models.PositiveIntegerField(blank=True, help_text='Index des Abschnitts (null für short)', null=True, verbose_name='Abschnitts-Index')),
                ('audio_file', models.FileField(upload_to='learnloom/audio/', verbose_name='Audio-Datei')),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='alloy', max_length=20, verbose_name='TTS-Stimme')),
                ('text_length', models.PositiveIntegerField(default=0, verbose_name='Textlänge (Zeichen)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Audio-Zusammenfassung',
                'verbose_name_plural': 'Audio-Zusammenfassungen',
                'ordering': ['audio_type', 'section_index'],
            },
        ),
        migrations.CreateModel(
            name='PDFSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_summary', models.TextField(blank=True, default='', help_text='Kurze Zusammenfassung für das PDF-Viewer Panel (2-3 Sätze)', verbose_name='Kurze Zusammenfassung')),
                ('full_summary', models.TextField(verbose_name='Vollständige Zusammenfassung')),
                ('sections', models.JSONField(default=list, help_text='Strukturierte Abschnitte mit Seitenreferenzen', verbose_name='Abschnitte')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='KI-Provider')),
                ('language', models.CharField(default='de', max_length=10, verbose_name='Sprache')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'PDF-Zusammenfassung',
                'verbose_name_plural': 'PDF-Zusammenfassungen',
            },
        ),
        migrations.RenameIndex(
            model_name='readinglistitem',
            new_name='learnloom_r_user_id_2af697_idx',
            old_name='learnloom_r_user_id_5a7c7d_idx',
        ),
        migrations.AddField(
            model_name='pdfbook',
            name='url',
            field=models.URLField(blank=True, help_text='URL für Online-Artikel', max_length=2000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pdfbook',
            name='category',
            field=models.CharField(choices=[('book', 'Buch'), ('paper', 'Paper'), ('article', 'Artikel'), ('online', 'Online-Artikel'), ('other', 'Sonstiges')], default='book', max_length=20, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='zoom_level',
            field=models.FloatField(default=1.75, verbose_name='Zoom-Stufe'),
        ),
        migrations.AddField(
            model_name='pdfsummary',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='learnloom.pdfbook', verbose_name='PDF-Buch'),
        ),
        migrations.AddField(
            model_name='pdfaudiosummary',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='learnloom.pdfsummary', verbose_name='Zusammenfassung'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfaudiosummary',
            unique_together={('summary', 'audio_type', 'section_index')},
        ),
    ]
