# Generated by Django 5.2.1 on 2026-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnloom', '0006_pdfaudiosummary_pdfsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbook',
            name='relevance',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = nicht bewertet, 1-10 = Bewertung', verbose_name='Relevanz'),
        ),
    ]
