# Generated by Django 5.2.1 on 2025-08-29 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoomAdsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_tracking', models.BooleanField(default=True, verbose_name='Tracking aktivieren')),
                ('enable_targeting', models.BooleanField(default=True, verbose_name='Targeting aktivieren')),
                ('enable_scheduling', models.BooleanField(default=True, verbose_name='Zeitplanung aktivieren')),
                ('default_daily_limit', models.IntegerField(blank=True, null=True, verbose_name='Standard tägliches Limit')),
                ('default_weight', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('enable_header_zones', models.JSONField(default=dict, verbose_name='Header-Zonen pro App')),
                ('enable_footer_zones', models.JSONField(default=dict, verbose_name='Footer-Zonen pro App')),
                ('enable_sidebar_zones', models.JSONField(default=dict, verbose_name='Sidebar-Zonen pro App')),
                ('enable_infeed_zones', models.JSONField(default=dict, verbose_name='In-Feed-Zonen pro App')),
                ('enable_modal_zones', models.JSONField(default=dict, verbose_name='Modal-Zonen pro App')),
                ('global_header_enabled', models.BooleanField(default=True, verbose_name='Header-Zonen global')),
                ('global_footer_enabled', models.BooleanField(default=True, verbose_name='Footer-Zonen global')),
                ('global_sidebar_enabled', models.BooleanField(default=True, verbose_name='Sidebar-Zonen global')),
                ('global_infeed_enabled', models.BooleanField(default=True, verbose_name='In-Feed-Zonen global')),
                ('global_modal_enabled', models.BooleanField(default=True, verbose_name='Modal-Zonen global')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LoomAds Einstellungen',
                'verbose_name_plural': 'LoomAds Einstellungen',
            },
        ),
    ]
