# Generated by Django 5.2.1 on 2025-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0002_loomadssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video_with_audio',
            field=models.BooleanField(default=True, help_text='Soll das Video mit oder ohne Ton abgespielt werden?', verbose_name='Video mit Ton'),
        ),
        migrations.AddField(
            model_name='adzone',
            name='popup_delay',
            field=models.IntegerField(default=5, help_text='Nach wie vielen Sekunden soll das Video-Popup erscheinen?', verbose_name='Popup Verzögerung (Sekunden)'),
        ),
        migrations.AlterField(
            model_name='adzone',
            name='zone_type',
            field=models.CharField(choices=[('header', 'Header Banner'), ('footer', 'Footer Banner'), ('sidebar', 'Seitenleiste'), ('in_feed', 'In-Feed'), ('modal', 'Modal/Pop-up'), ('video_preroll', 'Video Pre-Roll'), ('video_overlay', 'Video Overlay'), ('video_popup', 'Video Pop-up (unten rechts)'), ('content_card', 'Content Card'), ('notification', 'Benachrichtigung')], max_length=30),
        ),
    ]
