# Generated by Django 5.2.1 on 2025-08-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0003_advertisement_video_with_audio_adzone_popup_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loomadssettings',
            name='enable_content_card_zones',
            field=models.JSONField(default=dict, verbose_name='Content Card-Zonen pro App'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='enable_notification_zones',
            field=models.JSONField(default=dict, verbose_name='Benachrichtigungs-Zonen pro App'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='enable_video_overlay_zones',
            field=models.JSONField(default=dict, verbose_name='Video Overlay-Zonen pro App'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='enable_video_popup_zones',
            field=models.JSONField(default=dict, verbose_name='Video Pop-up-Zonen pro App'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='enable_video_preroll_zones',
            field=models.JSONField(default=dict, verbose_name='Video Pre-Roll-Zonen pro App'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='global_content_card_enabled',
            field=models.BooleanField(default=True, verbose_name='Content Card-Zonen global'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='global_notification_enabled',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigungs-Zonen global'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='global_video_overlay_enabled',
            field=models.BooleanField(default=True, verbose_name='Video Overlay-Zonen global'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='global_video_popup_enabled',
            field=models.BooleanField(default=True, verbose_name='Video Pop-up-Zonen global'),
        ),
        migrations.AddField(
            model_name='loomadssettings',
            name='global_video_preroll_enabled',
            field=models.BooleanField(default=True, verbose_name='Video Pre-Roll-Zonen global'),
        ),
    ]
