# Generated by Django 5.2.1 on 2025-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0004_loomadssettings_enable_content_card_zones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=100, verbose_name='Zone Code')),
                ('template_path', models.CharField(max_length=200, verbose_name='Template-Pfad')),
                ('visibility', models.CharField(choices=[('all', 'Alle Benutzer'), ('authenticated', 'Eingeloggte User'), ('anonymous', 'Anonyme Besucher'), ('superuser', 'Nur Superuser'), ('premium', 'Premium-Benutzer')], default='all', max_length=20, verbose_name='Sichtbar für')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('planned', 'Geplant'), ('deprecated', 'Veraltet')], default='active', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen zur Integration', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone Integration',
                'verbose_name_plural': 'Zone Integrationen',
                'ordering': ['template_path', 'zone_code'],
                'unique_together': {('zone_code', 'template_path')},
            },
        ),
    ]
