# Generated by Django 5.2.1 on 2025-08-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0005_zoneintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtargeting',
            name='exclude_browsers',
            field=models.JSONField(blank=True, default=list, help_text='Browser die ausgeschlossen werden sollen', verbose_name='Ausgeschlossene Browser'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='exclude_cities',
            field=models.JSONField(blank=True, default=list, help_text='Städte oder Regionen die ausgeschlossen werden sollen', verbose_name='Ausgeschlossene Städte/Regionen'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='exclude_os',
            field=models.JSONField(blank=True, default=list, help_text='Betriebssysteme die ausgeschlossen werden sollen', verbose_name='Ausgeschlossene Betriebssysteme'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='exclude_referrers',
            field=models.TextField(blank=True, help_text='Referrer die ausgeschlossen werden sollen', verbose_name='Ausgeschlossene Referrer'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_browsers',
            field=models.JSONField(blank=True, default=list, help_text='Liste der Browser (chrome, firefox, safari, edge, opera, andere)', verbose_name='Browser'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_cities',
            field=models.JSONField(blank=True, default=list, help_text='Liste der Städte oder Regionen', verbose_name='Städte/Regionen'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_date_end',
            field=models.DateField(blank=True, help_text='Bis welchem Datum soll die Anzeige erscheinen', null=True, verbose_name='Enddatum'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_date_start',
            field=models.DateField(blank=True, help_text='Ab welchem Datum soll die Anzeige erscheinen', null=True, verbose_name='Startdatum'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_hours_end',
            field=models.TimeField(blank=True, help_text='Bis welcher Uhrzeit soll die Anzeige erscheinen', null=True, verbose_name='Endzeit'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_hours_start',
            field=models.TimeField(blank=True, help_text='Ab welcher Uhrzeit soll die Anzeige erscheinen', null=True, verbose_name='Startzeit'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_os',
            field=models.JSONField(blank=True, default=list, help_text='Liste der Betriebssysteme (windows, macos, linux, ios, android, andere)', verbose_name='Betriebssysteme'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_referrers',
            field=models.TextField(blank=True, help_text='Referrer-URLs oder Muster (eine pro Zeile), z.B. google.com, facebook.com, direkt', verbose_name='Referrer-Muster'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='target_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Liste der Wochentage (0=Montag, 6=Sonntag)', verbose_name='Wochentage'),
        ),
    ]
