# Generated by Django 5.2.1 on 2025-08-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0006_extended_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='daily_click_limit',
            field=models.IntegerField(blank=True, help_text='Maximale Anzahl der Klicks pro Tag (leer = unbegrenzt)', null=True, verbose_name='Tägliches Klick-Limit'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_click_limit',
            field=models.IntegerField(blank=True, help_text='Maximale Anzahl der Klicks insgesamt (leer = unbegrenzt)', null=True, verbose_name='Gesamt Klick-Limit'),
        ),
    ]
