# Generated by Django 5.2.1 on 2025-09-11 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0007_campaign_daily_click_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCampaignFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Format-Name')),
                ('format_type', models.CharField(choices=[('banner_728x90', 'Banner 728x90 (Header/Footer)'), ('sidebar_300x250', 'Sidebar 300x250'), ('content_card_350x200', 'Content Card 350x200'), ('content_card_350x250', 'Content Card 350x250'), ('video_overlay_300x100', 'Video Overlay 300x100'), ('video_preroll_640x360', 'Video Pre-Roll 640x360'), ('modal_400x300', 'Modal 400x300'), ('notification_300x80', 'Benachrichtigung 300x80'), ('custom', 'Benutzerdefiniert')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('target_zone_types', models.JSONField(default=list, help_text='Liste der Zone-Typen, z.B. ["header", "footer"]', verbose_name='Ziel-Zone-Typen')),
                ('target_dimensions', models.JSONField(default=list, help_text='Liste der Dimensionen, z.B. ["728x90", "320x50"]', verbose_name='Ziel-Dimensionen')),
                ('excluded_zones', models.JSONField(default=list, help_text='Zone-Codes die ausgeschlossen werden sollen', verbose_name='Ausgeschlossene Zonen')),
                ('grouping_strategy', models.CharField(choices=[('by_type', 'Nach Zone-Typ gruppieren'), ('by_dimensions', 'Nach Dimensionen gruppieren'), ('by_type_and_dimensions', 'Nach Typ UND Dimensionen gruppieren'), ('by_app', 'Nach App gruppieren'), ('mixed', 'Gemischte Strategie')], default='by_type_and_dimensions', max_length=30)),
                ('auto_assign_similar_zones', models.BooleanField(default=True, verbose_name='Ähnliche Zonen automatisch zuweisen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.IntegerField(default=1, help_text='Höhere Priorität = bevorzugte Verwendung', verbose_name='Priorität')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto-Kampagnenformat',
                'verbose_name_plural': 'Auto-Kampagnenformate',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutoCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Kampagnen-Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('content_strategy', models.CharField(choices=[('single_creative', 'Ein Kreativ für alle Zonen'), ('format_optimized', 'Pro Format optimiert'), ('zone_specific', 'Zonenspezifisch angepasst'), ('a_b_testing', 'A/B Testing')], default='format_optimized', max_length=30)),
                ('auto_optimize_performance', models.BooleanField(default=True, verbose_name='Performance automatisch optimieren')),
                ('auto_pause_low_performers', models.BooleanField(default=False, verbose_name='Schwache Performer automatisch pausieren')),
                ('performance_threshold_ctr', models.FloatField(default=0.5, help_text='Unter diesem CTR werden Ads automatisch pausiert', verbose_name='CTR-Schwellenwert (%)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen'), ('auto_paused', 'Automatisch pausiert')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(verbose_name='Enddatum')),
                ('daily_impression_limit', models.IntegerField(blank=True, null=True, verbose_name='Tägliches Impression-Limit pro Zone')),
                ('total_impression_limit', models.IntegerField(blank=True, null=True, verbose_name='Gesamt Impression-Limit')),
                ('last_optimization_run', models.DateTimeField(blank=True, null=True)),
                ('auto_created_ads_count', models.IntegerField(default=0)),
                ('performance_score', models.FloatField(default=0.0, help_text='Automatisch berechneter Performance-Score (0-100)', verbose_name='Performance-Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_campaigns', to=settings.AUTH_USER_MODEL)),
                ('target_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='loomads.autocampaignformat', verbose_name='Ziel-Format')),
            ],
            options={
                'verbose_name': 'Automatische Kampagne',
                'verbose_name_plural': 'Automatische Kampagnen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_creative', models.TextField(help_text='JSON mit Creative-Daten (Bild-URL, Text, etc.)', verbose_name='Basis-Creative')),
                ('generation_strategy', models.CharField(choices=[('direct_copy', 'Direkte Kopie'), ('dimension_adapted', 'An Dimensionen angepasst'), ('format_optimized', 'Format-optimiert'), ('ai_generated', 'KI-generiert')], default='format_optimized', max_length=30)),
                ('generation_metadata', models.JSONField(default=dict, verbose_name='Generierungs-Metadaten')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('performance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertisement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_generated_from', to='loomads.advertisement')),
                ('target_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loomads.adzone', verbose_name='Ziel-Zone')),
                ('auto_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_advertisements', to='loomads.autocampaign')),
            ],
            options={
                'verbose_name': 'Automatische Anzeige',
                'verbose_name_plural': 'Automatische Anzeigen',
                'ordering': ['-created_at'],
                'unique_together': {('auto_campaign', 'target_zone')},
            },
        ),
    ]
