# Generated by Django 5.2.1 on 2025-09-27 22:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0008_autocampaignformat_autocampaign_autoadvertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='App-Kampagnenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('app_target', models.CharField(choices=[('loomline', 'LoomLine'), ('fileshare', 'FileShara'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('blog', 'Blog'), ('videos', 'Video-Management'), ('chat', 'Chat-System'), ('global', 'Global Bereiche'), ('shopify', 'Shopify Integration'), ('dashboard', 'Dashboard')], help_text='App für die diese Kampagne geschaltet wird', max_length=20, verbose_name='Ziel-App')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen')], default='draft', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Sehr niedrig'), (2, 'Niedrig'), (3, 'Normal'), (4, 'Hoch'), (5, 'Sehr hoch')], default=3, help_text='Höhere Priorität = häufigere Anzeige in App-Zonen', verbose_name='Priorität')),
                ('start_date', models.DateTimeField(verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(verbose_name='Enddatum')),
                ('auto_include_new_zones', models.BooleanField(default=True, help_text='Neue Zonen der App automatisch zu dieser Kampagne hinzufügen', verbose_name='Neue Zonen automatisch einbeziehen')),
                ('exclude_zone_types', models.JSONField(blank=True, default=list, help_text='Zone-Typen die von dieser App-Kampagne ausgeschlossen werden sollen', verbose_name='Ausgeschlossene Zone-Typen')),
                ('daily_impression_limit', models.IntegerField(blank=True, help_text='Maximale Anzahl der Impressions pro Tag für alle App-Zonen (leer = unbegrenzt)', null=True, verbose_name='Tägliches Impression-Limit (pro App)')),
                ('total_impression_limit', models.IntegerField(blank=True, help_text='Maximale Anzahl der Impressions insgesamt für alle App-Zonen (leer = unbegrenzt)', null=True, verbose_name='Gesamt Impression-Limit (pro App)')),
                ('daily_click_limit', models.IntegerField(blank=True, help_text='Maximale Anzahl der Klicks pro Tag für alle App-Zonen (leer = unbegrenzt)', null=True, verbose_name='Tägliches Klick-Limit (pro App)')),
                ('total_click_limit', models.IntegerField(blank=True, help_text='Maximale Anzahl der Klicks insgesamt für alle App-Zonen (leer = unbegrenzt)', null=True, verbose_name='Gesamt Klick-Limit (pro App)')),
                ('weight_multiplier', models.FloatField(default=1.0, help_text='Multiplikator für die Anzeigengewichtung in App-Zonen (0.1 - 5.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)], verbose_name='Gewichtungs-Multiplikator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App-Kampagne',
                'verbose_name_plural': 'App-Kampagnen',
                'ordering': ['-priority', '-created_at'],
                'unique_together': {('name', 'app_target')},
            },
        ),
        migrations.CreateModel(
            name='AppAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Anzeigenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('text', 'Text-Anzeige'), ('image', 'Bild-Anzeige'), ('video', 'Video-Anzeige'), ('html', 'HTML/Rich Content'), ('native', 'Native Content')], default='html', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('description_text', models.TextField(blank=True, verbose_name='Beschreibungstext')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML-Inhalt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='loomads/images/')),
                ('video_url', models.URLField(blank=True, verbose_name='Video-URL')),
                ('link_url', models.URLField(verbose_name='Ziel-URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Link-Text')),
                ('weight', models.IntegerField(default=5, help_text='Anzeigengewichtung (1-10) - wird mit App-Kampagne Multiplikator kombiniert', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Gewichtung')),
                ('device_targeting', models.CharField(choices=[('all', 'Alle Geräte'), ('desktop', 'Desktop'), ('mobile', 'Mobil'), ('tablet', 'Tablet')], default='all', max_length=20, verbose_name='Geräte-Targeting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('impressions_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(blank=True, help_text='Wird automatisch mit allen App-Zonen synchronisiert', related_name='app_advertisements', to='loomads.adzone')),
                ('app_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_advertisements', to='loomads.appcampaign')),
            ],
            options={
                'verbose_name': 'App-Anzeige',
                'verbose_name_plural': 'App-Anzeigen',
                'ordering': ['-created_at'],
            },
        ),
    ]
