# Generated by Django 5.2.1 on 2025-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0009_appcampaign_appadvertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcampaign',
            name='app_target',
            field=models.CharField(choices=[('loomline', 'LoomLine'), ('loomconnect', 'LoomConnect'), ('keyengine', 'KeyEngine'), ('fileshare', 'FileShara'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('blog', 'Blog'), ('videos', 'Video-Management'), ('chat', 'Chat-System'), ('todos', 'Todos'), ('core', 'Dashboard/Startseite'), ('image_editor', 'Image Editor'), ('amortization_calculator', 'Amortisationsrechner'), ('pdf_sucher', 'PDF Sucher'), ('naturmacher', 'Naturmacher'), ('lighting_tools', 'Lighting Tools'), ('shopify_manager', 'Shopify Manager'), ('global', 'Global Bereiche'), ('dashboard', 'Dashboard (Legacy)')], help_text='App für die diese Kampagne geschaltet wird', max_length=30, verbose_name='Ziel-App'),
        ),
    ]
