# Generated by Django 5.2.1 on 2025-10-24 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0010_alter_appcampaign_app_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdWizardDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.CharField(choices=[('app_selection', 'App-Auswahl'), ('campaign_details', 'Kampagnen-Details'), ('format_selection', 'Format-Auswahl'), ('creative_upload', 'Creative-Upload'), ('review', 'Überprüfung')], default='app_selection', max_length=30, verbose_name='Aktueller Schritt')),
                ('completed_steps', models.JSONField(default=list, help_text='Liste der bereits abgeschlossenen Schritte', verbose_name='Abgeschlossene Schritte')),
                ('wizard_data', models.JSONField(default=dict, help_text='Alle gesammelten Daten aus den Wizard-Schritten', verbose_name='Wizard-Daten')),
                ('selected_app', models.CharField(blank=True, max_length=30, verbose_name='Ausgewählte App')),
                ('campaign_name', models.CharField(blank=True, max_length=200, verbose_name='Kampagnenname')),
                ('campaign_description', models.TextField(blank=True, verbose_name='Kampagnen-Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Entwurf wird nach diesem Datum automatisch gelöscht', verbose_name='Verfällt am')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Entwürfe werden nicht mehr angezeigt', verbose_name='Aktiv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_wizard_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Ad-Wizard Entwurf',
                'verbose_name_plural': 'Ad-Wizard Entwürfe',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='loomads_adw_user_id_5a51b0_idx'), models.Index(fields=['expires_at'], name='loomads_adw_expires_9ccb7d_idx')],
            },
        ),
    ]
