# Generated by Django 5.2.1 on 2025-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0011_adwizarddraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcampaign',
            name='exclude_zone_types',
            field=models.JSONField(blank=True, default=list, help_text='Zone-Typen die von dieser App-Kampagne ausgeschlossen werden sollen', null=True, verbose_name='Ausgeschlossene Zone-Typen'),
        ),
    ]
