# Generated by Django 5.2.1 on 2025-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0012_alter_appcampaign_exclude_zone_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Leer lassen für "Unbegrenzt"', null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='appcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Leer lassen für "Ab sofort"', null=True, verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='autocampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Leer lassen für "Unbegrenzt"', null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='autocampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Leer lassen für "Ab sofort"', null=True, verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Leer lassen für "Unbegrenzt"', null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Leer lassen für "Ab sofort"', null=True, verbose_name='Startdatum'),
        ),
    ]
