# Generated by Django 5.2.1 on 2025-12-22 10:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0013_alter_appcampaign_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Kurzer, aussagekräftiger Titel (max. 100 Zeichen)', max_length=100, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Optionale Beschreibung (max. 300 Zeichen)', max_length=300, verbose_name='Beschreibung')),
                ('image', models.ImageField(blank=True, help_text='Optionales Bild (wird automatisch skaliert)', null=True, upload_to='loomads/simple/', verbose_name='Bild')),
                ('button_text', models.CharField(default='Mehr erfahren', help_text='Text auf dem Aktions-Button (max. 30 Zeichen)', max_length=30, verbose_name='Button-Text')),
                ('target_url', models.URLField(help_text='Wohin soll die Anzeige verlinken?', verbose_name='Ziel-URL')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='In neuem Tab öffnen')),
                ('template_style', models.CharField(choices=[('minimal', 'Minimal - Nur Text'), ('card', 'Card - Mit Rahmen und Schatten'), ('gradient', 'Gradient - Farbverlauf-Hintergrund'), ('banner', 'Banner - Breites Format'), ('highlight', 'Highlight - Auffällig mit Akzentfarbe'), ('dark', 'Dark - Dunkler Hintergrund')], default='card', help_text='Wähle einen Stil für die Anzeige', max_length=20, verbose_name='Design-Vorlage')),
                ('color_scheme', models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('purple', 'Lila'), ('orange', 'Orange'), ('red', 'Rot'), ('teal', 'Türkis'), ('pink', 'Pink'), ('gray', 'Grau'), ('custom', 'Eigene Farbe')], default='blue', max_length=20, verbose_name='Farbschema')),
                ('custom_color', models.CharField(blank=True, help_text='Hex-Farbe z.B. #FF5733 (nur bei "Eigene Farbe")', max_length=7, verbose_name='Eigene Farbe')),
                ('is_active', models.BooleanField(default=True, help_text='Nur aktive Anzeigen werden angezeigt', verbose_name='Aktiv')),
                ('weight', models.IntegerField(default=5, help_text='1-10: Höhere Werte = häufigere Anzeige', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Gewichtung')),
                ('exclude_zones', models.JSONField(blank=True, default=list, help_text='Liste von Zone-Codes die ausgeschlossen werden sollen', verbose_name='Ausgeschlossene Zonen')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impressionen')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Klicks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Einfache Anzeige',
                'verbose_name_plural': 'Einfache Anzeigen',
                'ordering': ['-created_at'],
            },
        ),
    ]
