# Generated by Django 5.2.1 on 2025-12-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0014_simple_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplead',
            name='ab_test_group',
            field=models.CharField(blank=True, help_text='Anzeigen mit gleichem Gruppennamen werden getestet', max_length=50, verbose_name='A/B-Test Gruppe'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='animation',
            field=models.CharField(choices=[('none', 'Keine Animation'), ('fade', 'Fade-In'), ('slide', 'Slide-In'), ('pulse', 'Pulse beim Hover'), ('bounce', 'Bounce'), ('shake', 'Shake beim Hover')], default='none', help_text='Animations-Effekt für die Anzeige', max_length=20, verbose_name='Animation'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='app_filter',
            field=models.JSONField(blank=True, default=list, help_text='Nur in diesen Apps anzeigen (leer = alle)', verbose_name='App-Filter'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'Kein Badge'), ('neu', 'NEU'), ('sale', 'SALE'), ('hot', 'HOT'), ('top', 'TOP'), ('tipp', 'TIPP'), ('limited', 'LIMITIERT'), ('custom', 'Eigener Text')], default='', help_text='Optionales Badge/Label', max_length=20, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='badge_custom_text',
            field=models.CharField(blank=True, help_text='Nur bei "Eigener Text"', max_length=20, verbose_name='Eigener Badge-Text'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='countdown_enabled',
            field=models.BooleanField(default=False, help_text='Zeigt einen Countdown bis zum Enddatum', verbose_name='Countdown anzeigen'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='countdown_text',
            field=models.CharField(blank=True, default='Nur noch:', help_text='Text vor dem Countdown', max_length=50, verbose_name='Countdown-Text'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Bis wann soll die Anzeige erscheinen? (leer = unbegrenzt)', null=True, verbose_name='Enddatum'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='exclude_apps',
            field=models.JSONField(blank=True, default=list, help_text='In diesen Apps nicht anzeigen', verbose_name='Apps ausschließen'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Kein Icon'), ('bi-star-fill', 'Stern'), ('bi-heart-fill', 'Herz'), ('bi-lightning-fill', 'Blitz'), ('bi-fire', 'Feuer'), ('bi-gift', 'Geschenk'), ('bi-trophy', 'Pokal'), ('bi-rocket', 'Rakete'), ('bi-megaphone', 'Megaphone'), ('bi-percent', 'Prozent'), ('bi-tag-fill', 'Tag'), ('bi-cart-fill', 'Warenkorb'), ('bi-cash-coin', 'Geld'), ('bi-bell-fill', 'Glocke'), ('bi-chat-heart-fill', 'Chat-Herz'), ('bi-emoji-smile', 'Smiley')], default='', help_text='Bootstrap Icon (Alternative zu Bild)', max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Ab wann soll die Anzeige erscheinen? (leer = sofort)', null=True, verbose_name='Startdatum'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Alle Nutzer'), ('logged_in', 'Nur eingeloggte Nutzer'), ('anonymous', 'Nur anonyme Besucher')], default='all', help_text='Für welche Nutzer soll die Anzeige sichtbar sein?', max_length=20, verbose_name='Zielgruppe'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Name für A/B-Test (z.B. "Variante A")', max_length=50, verbose_name='Varianten-Name'),
        ),
        migrations.AddField(
            model_name='simplead',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL zu einem kurzen Loop-Video (MP4)', verbose_name='Video-URL'),
        ),
        migrations.AlterField(
            model_name='simplead',
            name='template_style',
            field=models.CharField(choices=[('minimal', 'Minimal - Nur Text'), ('card', 'Card - Mit Rahmen und Schatten'), ('gradient', 'Gradient - Farbverlauf-Hintergrund'), ('banner', 'Banner - Breites Format'), ('highlight', 'Highlight - Auffällig mit Akzentfarbe'), ('dark', 'Dark - Dunkler Hintergrund'), ('glass', 'Glass - Glasmorphismus-Effekt'), ('neon', 'Neon - Leuchtende Rahmen'), ('retro', 'Retro - Vintage-Look'), ('threed', '3D - Mit Tiefeneffekt')], default='card', help_text='Wähle einen Stil für die Anzeige', max_length=20, verbose_name='Design-Vorlage'),
        ),
    ]
