# Generated by Django 5.2.1 on 2026-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loomads', '0015_simple_ads_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcampaign',
            name='app_target',
            field=models.CharField(choices=[('loomline', 'LoomLine'), ('loomconnect', 'LoomConnect'), ('keyengine', 'KeyEngine'), ('fileshare', 'FileShare'), ('streamrec', 'StreamRec'), ('promptpro', 'PromptPro'), ('blog', 'Blog'), ('videos', 'Video-Management'), ('chat', 'Chat-System'), ('todos', 'Todos'), ('core', 'Dashboard/Startseite'), ('image_editor', 'Image Editor'), ('amortization_calculator', 'Amortisationsrechner'), ('pdf_sucher', 'PDF Sucher'), ('naturmacher', 'Naturmacher'), ('lighting_tools', 'Lighting Tools'), ('shopify_manager', 'Shopify Manager'), ('global', 'Global Bereiche'), ('dashboard', 'Dashboard (Legacy)'), ('android_apk_manager', 'Android APK Manager'), ('backloom', 'BackLoom'), ('linkloom', 'LinkLoom'), ('loommarket', 'LoomMarket'), ('ploom', 'P-Loom')], help_text='App für die diese Kampagne geschaltet wird', max_length=30, verbose_name='Ziel-App'),
        ),
    ]
