# Generated by Django 5.2.1 on 2025-06-06 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name der Komponente')),
                ('kategorie', models.CharField(choices=[('LEUCHTE', 'Leuchte'), ('TRAVERSE', 'Traverse'), ('EVG', 'Externes EVG'), ('VERTEILERBOX', 'Verteilerbox'), ('STEUERBOX', 'Steuerbox'), ('STEUERBAUSTEIN', 'Steuerbaustein'), ('SONSTIGES', 'Sonstiges')], max_length=100, verbose_name='Kategorie')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name der Variante')),
                ('beschreibung', models.CharField(max_length=300, verbose_name='Beschreibung')),
                ('preis_leuchten', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis für alle Leuchten')),
                ('preis_traversen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis für alle Traversen')),
                ('preis_externe_evgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis für alle externen EVGs')),
                ('preis_verteilerboxen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis für alle Verteilerboxen')),
                ('preis_steuerboxen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis für alle Steuerboxen')),
                ('preis_steuerbausteine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis für alle Steuerbausteine')),
                ('preis_gesamt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis für die gesamte Variante')),
                ('anzahl_leuchten', models.IntegerField(default=16)),
                ('anzahl_traversen', models.IntegerField(default=6)),
                ('anzahl_externe_evgs', models.IntegerField(default=0)),
                ('anzahl_verteilerboxen', models.IntegerField(default=0)),
                ('anzahl_steuerboxen', models.IntegerField(default=0)),
                ('anzahl_steuerbausteine', models.IntegerField(default=0)),
                ('bemerkung_konfiguration', models.TextField(blank=True)),
                ('externes_evg', models.ForeignKey(blank=True, limit_choices_to={'kategorie': 'EVG'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evg_in_varianten', to='sportplatzApp.komponente')),
                ('leuchte', models.ForeignKey(limit_choices_to={'kategorie': 'LEUCHTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='leuchte_in_varianten', to='sportplatzApp.komponente')),
                ('steuerbaustein', models.ForeignKey(blank=True, limit_choices_to={'kategorie': 'STEUERBAUSTEIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steuerbaustein_in_varianten', to='sportplatzApp.komponente')),
                ('steuerbox', models.ForeignKey(blank=True, limit_choices_to={'kategorie': 'STEUERBOX'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steuerbox_in_varianten', to='sportplatzApp.komponente')),
                ('traverse', models.ForeignKey(limit_choices_to={'kategorie': 'TRAVERSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='traverse_in_varianten', to='sportplatzApp.komponente')),
                ('verteilerbox', models.ForeignKey(blank=True, limit_choices_to={'kategorie': 'VERTEILERBOX'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verteilerbox_in_varianten', to='sportplatzApp.komponente')),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_name', models.CharField(max_length=200, verbose_name='Projektname')),
                ('projektort', models.CharField(max_length=200, verbose_name='Projektort')),
                ('kunde', models.CharField(max_length=200, verbose_name='Kunde')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('ansprechpartner_email', models.EmailField(max_length=254, verbose_name='E-Mail des Ansprechpartners')),
                ('laenge', models.FloatField(default=105, verbose_name='Länge in Metern')),
                ('breite', models.FloatField(default=68, verbose_name='Breite in Metern')),
                ('erstellungsdatum', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ausgewaehlte_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportplatzApp.variante', verbose_name='Gewählte Konfigurations-Variante')),
            ],
        ),
    ]
