# Generated by Django 5.2.1 on 2026-01-30 17:33

import django.db.models.deletion
import loommarket.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_username', models.CharField(max_length=100, verbose_name='Instagram Username')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firmenname')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Website')),
                ('follower_count', models.PositiveIntegerField(default=0, verbose_name='Follower')),
                ('profile_picture_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Profilbild URL')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('searching', 'Suche läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loommarket_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unternehmen',
                'verbose_name_plural': 'Unternehmen',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'instagram_username')},
            },
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=loommarket.models.business_image_path, verbose_name='Bild')),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Quell-URL')),
                ('source', models.CharField(choices=[('search', 'Bildersuche'), ('manual', 'Manuell hochgeladen'), ('instagram', 'Instagram')], default='search', max_length=20)),
                ('is_logo', models.BooleanField(default=False, verbose_name='Ist Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Dateigröße in Bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loommarket.business')),
            ],
            options={
                'verbose_name': 'Unternehmensbild',
                'verbose_name_plural': 'Unternehmensbilder',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vorlagen-Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('product_image_blank', models.ImageField(help_text='Produktbild ohne Gravur', upload_to=loommarket.models.mockup_template_path, verbose_name='Produkt (blank)')),
                ('product_image_engraved', models.ImageField(help_text='Produktbild mit Beispiel-Gravur', upload_to=loommarket.models.mockup_template_path, verbose_name='Produkt (graviert)')),
                ('default_background_prompt', models.TextField(blank=True, help_text='Beschreibung des Hintergrunds für die KI-Generierung', null=True, verbose_name='Standard Hintergrund-Prompt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loommarket_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mockup-Vorlage',
                'verbose_name_plural': 'Mockup-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mockup_image', models.ImageField(blank=True, null=True, upload_to=loommarket.models.campaign_image_path, verbose_name='Generiertes Mockup')),
                ('mockup_image_story', models.ImageField(blank=True, null=True, upload_to=loommarket.models.campaign_image_path, verbose_name='Mockup (Story-Format 9:16)')),
                ('background_prompt', models.TextField(blank=True, null=True, verbose_name='Hintergrund-Prompt')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('mockup_pending', 'Mockup ausstehend'), ('mockup_generating', 'Mockup wird generiert'), ('mockup_ready', 'Mockup fertig'), ('captions_pending', 'Captions ausstehend'), ('ready', 'Bereit zum Posten'), ('posted', 'Gepostet'), ('failed', 'Fehlgeschlagen')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='loommarket.business')),
                ('design_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_as_design', to='loommarket.businessimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loommarket_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='loommarket.mockuptemplate')),
            ],
            options={
                'verbose_name': 'Marketing-Kampagne',
                'verbose_name_plural': 'Marketing-Kampagnen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter/X'), ('bluesky', 'Bluesky')], max_length=20)),
                ('post_type', models.CharField(choices=[('feed', 'Feed-Post'), ('story', 'Story'), ('reel', 'Reel')], default='feed', max_length=10)),
                ('post_text', models.TextField(verbose_name='Post-Text')),
                ('image_used', models.CharField(choices=[('feed', 'Feed-Bild'), ('story', 'Story-Bild')], default='feed', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('scheduled', 'Geplant'), ('publishing', 'Wird veröffentlicht'), ('published', 'Veröffentlicht'), ('failed', 'Fehlgeschlagen')], default='draft', max_length=20)),
                ('external_post_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Externe Post-ID')),
                ('external_post_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Post-URL')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Geplant für')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='loommarket.marketingcampaign')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter/X'), ('bluesky', 'Bluesky')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titel')),
                ('caption_text', models.TextField(verbose_name='Caption-Text')),
                ('hashtags', models.TextField(blank=True, null=True, verbose_name='Hashtags')),
                ('mention_username', models.CharField(blank=True, help_text='Instagram/Twitter Username für Erwähnung', max_length=100, null=True, verbose_name='@-Mention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='loommarket.marketingcampaign')),
            ],
            options={
                'verbose_name': 'Social Media Caption',
                'verbose_name_plural': 'Social Media Captions',
                'unique_together': {('campaign', 'platform')},
            },
        ),
    ]
