# Generated by Django 5.2.1 on 2026-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loommarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kampagnenname'),
        ),
    ]
