# Generated by Django 5.2.1 on 2026-02-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loommarket', '0002_add_impressum_fields'),
        ('loommarket', '0002_marketingcampaign_name'),
    ]

    operations = [
    ]
