# Generated by Django 5.2.1 on 2026-01-05 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0006_chunkedupload_uploadchunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Projektname')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('processing', 'Wird verarbeitet'), ('exporting', 'Wird exportiert'), ('completed', 'Abgeschlossen'), ('error', 'Fehler')], default='draft', max_length=20, verbose_name='Status')),
                ('project_data', models.JSONField(blank=True, default=dict, help_text='Vollständiger Timeline-Zustand als JSON', verbose_name='Projekt-Daten')),
                ('ai_transcription', models.JSONField(blank=True, default=dict, help_text='Whisper-Ergebnis mit Word-Timestamps', verbose_name='AI-Transkription')),
                ('waveform_data', models.JSONField(blank=True, default=list, verbose_name='Waveform-Daten')),
                ('export_quality', models.CharField(choices=[('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4k', '4K Ultra HD')], default='1080p', max_length=10, verbose_name='Export-Qualität')),
                ('export_format', models.CharField(choices=[('mp4', 'MP4 (H.264)'), ('webm', 'WebM (VP9)')], default='mp4', max_length=10, verbose_name='Export-Format')),
                ('processing_progress', models.IntegerField(default=0, verbose_name='Fortschritt (%)')),
                ('processing_message', models.CharField(blank=True, default='', max_length=255, verbose_name='Status-Nachricht')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='mycut/thumbnails/', verbose_name='Vorschaubild')),
                ('estimated_duration', models.FloatField(default=0, verbose_name='Geschätzte Dauer (Sekunden)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mycut_outputs', to='videos.video', verbose_name='Exportiertes Video')),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycut_projects', to='videos.video', verbose_name='Quell-Video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycut_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyCut Projekt',
                'verbose_name_plural': 'MyCut Projekte',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('filler_word', 'Filler-Wort'), ('silence', 'Stille/Pause'), ('speed_up', 'Beschleunigen'), ('speed_down', 'Verlangsamen'), ('zoom_in', 'Heranzoomen'), ('zoom_out', 'Herauszoomen'), ('cut', 'Schneiden')], max_length=20, verbose_name='Typ')),
                ('start_time', models.FloatField(verbose_name='Start (ms)')),
                ('end_time', models.FloatField(verbose_name='Ende (ms)')),
                ('confidence', models.FloatField(default=0.8, help_text='AI-Konfidenz (0.0 - 1.0)', verbose_name='Konfidenz')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Angewendet')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Abgelehnt')),
                ('suggestion_data', models.JSONField(blank=True, default=dict, help_text='Typ-spezifische Parameter', verbose_name='Vorschlags-Daten')),
                ('text', models.CharField(blank=True, default='', max_length=100, verbose_name='Erkannter Text')),
                ('suggested_value', models.FloatField(blank=True, null=True, verbose_name='Vorgeschlagener Wert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='mycut.editproject')),
            ],
            options={
                'verbose_name': 'AI-Vorschlag',
                'verbose_name_plural': 'AI-Vorschläge',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery Task ID')),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('processing', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20, verbose_name='Status')),
                ('progress', models.IntegerField(default=0, verbose_name='Fortschritt (%)')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='mycut/exports/', verbose_name='Ausgabedatei')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehlermeldung')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('export_settings', models.JSONField(blank=True, default=dict, verbose_name='Export-Einstellungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='mycut.editproject')),
            ],
            options={
                'verbose_name': 'Export-Auftrag',
                'verbose_name_plural': 'Export-Aufträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('start_time', models.FloatField(verbose_name='Start (ms)')),
                ('end_time', models.FloatField(verbose_name='Ende (ms)')),
                ('word_timestamps', models.JSONField(blank=True, default=list, help_text='[{"word": "Hallo", "start": 0.0, "end": 0.5}, ...]', verbose_name='Wort-Timestamps')),
                ('style', models.JSONField(blank=True, default=dict, help_text='{"font": "Arial", "size": 24, "color": "#FFFFFF", "position": "bottom"}', verbose_name='Stil')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Automatisch generiert')),
                ('confidence', models.FloatField(default=1.0, help_text='AI-Konfidenz (0.0 - 1.0)', verbose_name='Konfidenz')),
                ('language', models.CharField(default='de', max_length=10, verbose_name='Sprache')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='mycut.editproject')),
            ],
            options={
                'verbose_name': 'Untertitel',
                'verbose_name_plural': 'Untertitel',
                'ordering': ['start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TextOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('start_time', models.FloatField(verbose_name='Start (ms)')),
                ('end_time', models.FloatField(verbose_name='Ende (ms)')),
                ('position_x', models.FloatField(default=50, verbose_name='X-Position (%)')),
                ('position_y', models.FloatField(default=50, verbose_name='Y-Position (%)')),
                ('style', models.JSONField(blank=True, default=dict, help_text='{"font": "Arial", "size": 48, "color": "#FFFFFF", "bold": true}', verbose_name='Stil')),
                ('animation_in', models.CharField(choices=[('none', 'Keine'), ('fade_in', 'Einblenden'), ('fade_out', 'Ausblenden'), ('fade_in_out', 'Ein- und Ausblenden'), ('slide_left', 'Von links einschieben'), ('slide_right', 'Von rechts einschieben'), ('slide_up', 'Von unten einschieben'), ('slide_down', 'Von oben einschieben'), ('typewriter', 'Schreibmaschine'), ('zoom_in', 'Heranzoomen')], default='fade_in', max_length=20, verbose_name='Eingangs-Animation')),
                ('animation_out', models.CharField(choices=[('none', 'Keine'), ('fade_in', 'Einblenden'), ('fade_out', 'Ausblenden'), ('fade_in_out', 'Ein- und Ausblenden'), ('slide_left', 'Von links einschieben'), ('slide_right', 'Von rechts einschieben'), ('slide_up', 'Von unten einschieben'), ('slide_down', 'Von oben einschieben'), ('typewriter', 'Schreibmaschine'), ('zoom_in', 'Heranzoomen')], default='fade_out', max_length=20, verbose_name='Ausgangs-Animation')),
                ('animation_duration', models.FloatField(default=500, verbose_name='Animations-Dauer (ms)')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_overlays', to='mycut.editproject')),
            ],
            options={
                'verbose_name': 'Text-Overlay',
                'verbose_name_plural': 'Text-Overlays',
                'ordering': ['start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('subtitle', 'Untertitel'), ('text_overlay', 'Text-Overlay'), ('image', 'Bild')], default='video', max_length=20)),
                ('track_index', models.IntegerField(default=0, verbose_name='Track-Index')),
                ('start_time', models.FloatField(default=0, verbose_name='Start (ms)')),
                ('duration', models.FloatField(default=0, verbose_name='Dauer (ms)')),
                ('source_start', models.FloatField(default=0, verbose_name='Quell-Start (ms)')),
                ('source_end', models.FloatField(default=0, verbose_name='Quell-Ende (ms)')),
                ('clip_data', models.JSONField(blank=True, default=dict, help_text='Filter, Effekte, Transformationen als JSON', verbose_name='Clip-Daten')),
                ('order', models.IntegerField(default=0)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('volume', models.FloatField(default=1.0)),
                ('speed', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='mycut.editproject')),
            ],
            options={
                'verbose_name': 'Timeline-Clip',
                'verbose_name_plural': 'Timeline-Clips',
                'ordering': ['track_index', 'start_time', 'order'],
            },
        ),
    ]
