# Generated by Django 5.2.1 on 2025-07-29 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_rename_email_templ_created_4c0a02_idx_email_templ_created_bff515_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_key', models.CharField(help_text="Eindeutiger Schlüssel für diesen Trigger (z.B. 'user_registration')", max_length=100, unique=True, verbose_name='Trigger-Schlüssel')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(help_text='Beschreibung wann dieser Trigger ausgelöst wird', verbose_name='Beschreibung')),
                ('category', models.CharField(choices=[('authentication', 'Authentifizierung'), ('storage', 'Speicher-Management'), ('payments', 'Zahlungen & Abonnements'), ('system', 'System-Benachrichtigungen'), ('organization', 'Organisation & Termine'), ('ecommerce', 'E-Commerce'), ('custom', 'Benutzerdefiniert')], default='custom', max_length=50, verbose_name='Kategorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_system_trigger', models.BooleanField(default=True, help_text='System-Trigger können nicht gelöscht werden', verbose_name='System-Trigger')),
                ('available_variables', models.JSONField(blank=True, default=dict, help_text='JSON-Definition der verfügbaren Template-Variablen', verbose_name='Verfügbare Variablen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Trigger',
                'verbose_name_plural': 'E-Mail-Trigger',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Erweiterte Bedingungen für die Versendung (JSON)', verbose_name='Bedingungen'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_auto_send',
            field=models.BooleanField(default=True, help_text='Template automatisch bei Trigger-Ereignis senden', verbose_name='Automatisch senden'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='send_delay_minutes',
            field=models.IntegerField(default=0, help_text='Verzögerung in Minuten bevor die E-Mail gesendet wird', verbose_name='Versendungs-Verzögerung (Minuten)'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='trigger',
            field=models.ForeignKey(blank=True, help_text='Trigger der diese Vorlage automatisch auslöst', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='email_templates.emailtrigger', verbose_name='E-Mail-Trigger'),
        ),
    ]
