# Generated by Django 5.2.1 on 2025-09-29 20:40

from django.db import migrations


def update_welcome_email_template(apps, schema_editor):
    """
    Update the welcome email template with improved content and remove duplicate template
    """
    EmailTemplate = apps.get_model('email_templates', 'EmailTemplate')

    # Define the improved HTML content
    improved_html_content = '''<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Willkommen bei Workloom - E-Mail bestätigen</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .container {
            background-color: #ffffff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #4a90e2;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .logo {
            font-size: 28px;
            font-weight: bold;
            color: #4a90e2;
            margin-bottom: 10px;
        }
        .welcome-title {
            color: #2c3e50;
            font-size: 24px;
            margin: 20px 0;
            text-align: center;
        }
        .highlight {
            background-color: #e8f4fd;
            padding: 20px;
            border-left: 4px solid #4a90e2;
            margin: 20px 0;
            border-radius: 5px;
        }
        .btn {
            display: inline-block;
            background-color: #4a90e2;
            color: white;
            padding: 15px 30px;
            text-decoration: none;
            border-radius: 25px;
            font-weight: bold;
            margin: 20px 0;
            text-align: center;
        }
        .btn:hover {
            background-color: #357abd;
        }
        .features {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .features h3 {
            color: #4a90e2;
            margin-bottom: 15px;
        }
        .features ul {
            list-style-type: none;
            padding: 0;
        }
        .features li {
            padding: 8px 0;
            border-bottom: 1px solid #e9ecef;
        }
        .features li:before {
            content: "✓ ";
            color: #28a745;
            font-weight: bold;
            margin-right: 10px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #666;
            font-size: 14px;
        }
        .social-links {
            margin: 20px 0;
        }
        .social-links a {
            color: #4a90e2;
            text-decoration: none;
            margin: 0 10px;
        }
        @media (max-width: 600px) {
            .container {
                padding: 20px;
            }
            .welcome-title {
                font-size: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">Workloom</div>
            <p>Ihre moderne Arbeitsplattform</p>
        </div>

        <h1 class="welcome-title">Willkommen bei Workloom, {{ user_name }}!</h1>

        <div class="highlight">
            <p><strong>Vielen Dank für Ihre Registrierung!</strong></p>
            <p>Wir freuen uns sehr, Sie als neues Mitglied in unserer Workloom-Community begrüßen zu dürfen. Ihre Registrierung am {{ registration_date }} war erfolgreich!</p>
        </div>

        <div style="text-align: center; margin: 30px 0;">
            <a href="{{ verification_url }}" class="btn">Jetzt Dashboard öffnen</a>
        </div>

        <div class="features">
            <h3>🚀 Entdecken Sie Ihre neuen Möglichkeiten:</h3>
            <ul>
                <li><strong>Chat-System:</strong> Direkte Kommunikation mit Kollegen und Kunden</li>
                <li><strong>Shopify-Integration:</strong> Nahtlose E-Commerce-Lösungen</li>
                <li><strong>PDF-Suche & KI:</strong> Intelligente Dokumentenanalyse und Zusammenfassungen</li>
                <li><strong>Video-Hosting:</strong> Professionelle Präsentation Ihrer Projekte</li>
                <li><strong>Organisationstools:</strong> Notizen, Boards und Terminplanung</li>
                <li><strong>Amortisationsrechner:</strong> Finanzanalysen und Kalkulationen</li>
                <li><strong>Statistiken & Analytics:</strong> Datengetriebene Entscheidungen</li>
                <li><strong>Sichere Dateifreigabe:</strong> Verschlüsselter Transfer und Sharing</li>
            </ul>
        </div>

        <div class="highlight">
            <h3>🎯 Ihr nächster Schritt:</h3>
            <p>Loggen Sie sich jetzt in Ihr Dashboard ein und erkunden Sie alle verfügbaren Funktionen. Unser intuitives Interface macht es Ihnen leicht, sofort produktiv zu werden.</p>
            <div style="text-align: center; margin: 20px 0;">
                <a href="{{ activation_url }}" class="btn">Dashboard öffnen</a>
            </div>
        </div>

        <div style="background-color: #fff3cd; border: 1px solid #ffeaa7; border-radius: 5px; padding: 15px; margin: 20px 0;">
            <p><strong>💡 Tipp:</strong> Bookmarken Sie Ihr Dashboard für schnellen Zugriff: <a href="{{ verification_url }}" style="color: #4a90e2;">{{ domain }}</a></p>
        </div>

        <div class="footer">
            <p><strong>{{ site_name }} Team</strong></p>
            <p>Ihre moderne Arbeitsplattform für effiziente Zusammenarbeit</p>

            <div class="social-links">
                <a href="https://{{ domain }}">Website</a> |
                <a href="mailto:kontakt@{{ domain }}">Support</a>
            </div>

            <p style="font-size: 12px; color: #999; margin-top: 20px;">
                Diese E-Mail wurde automatisch generiert. Bitte antworten Sie nicht auf diese E-Mail.<br>
                © {{ current_year }} {{ site_name }}. Alle Rechte vorbehalten.
            </p>
        </div>
    </div>
</body>
</html>'''

    improved_text_content = '''Willkommen bei Workloom, {{ user_name }}!

Vielen Dank für Ihre Registrierung am {{ registration_date }}!

Wir freuen uns sehr, Sie als neues Mitglied in unserer Workloom-Community begrüßen zu dürfen.

🚀 Ihre neuen Möglichkeiten:
• Chat-System für direkte Kommunikation
• Shopify-Integration für E-Commerce
• PDF-Suche und KI-Zusammenfassungen
• Video-Hosting für Ihre Projekte
• Organisationstools: Notizen, Boards, Termine
• Amortisationsrechner für Finanzanalysen
• Statistiken & Analytics
• Sichere Dateifreigabe

🎯 Nächster Schritt:
Öffnen Sie jetzt Ihr Dashboard: {{ verification_url }}

💡 Tipp: Bookmarken Sie {{ domain }} für schnellen Zugriff!

Mit freundlichen Grüßen
Ihr {{ site_name }} Team

---
Diese E-Mail wurde automatisch generiert.
© {{ current_year }} {{ site_name }}. Alle Rechte vorbehalten.'''

    # Update the main welcome template
    welcome_template = EmailTemplate.objects.filter(name='Willkommen bei Workloom - E-Mail bestätigen').first()
    if welcome_template:
        welcome_template.html_content = improved_html_content
        welcome_template.text_content = improved_text_content
        welcome_template.save()
        print("✅ Welcome email template updated with improved content")
    else:
        print("❌ Welcome email template not found")

    # Remove duplicate template if it exists
    duplicate_template = EmailTemplate.objects.filter(name='Willkommen & E-Mail Verifizierung').first()
    if duplicate_template:
        duplicate_template.delete()
        print("✅ Duplicate email template removed")
    else:
        print("ℹ️ No duplicate template found to remove")


def reverse_welcome_email_template(apps, schema_editor):
    """
    Reverse the changes - restore original template state
    """
    # This is intentionally minimal as we don't want to restore the old state
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.RunPython(update_welcome_email_template, reverse_welcome_email_template),
    ]
