# Generated by Django 5.2.1 on 2025-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0003_auto_20250929_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-freundlicher Name (wird automatisch generiert falls leer)', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
