# Generated by Django 5.2.1 on 2026-03-30 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_type', models.CharField(choices=[('start', 'Start-Frame'), ('end', 'End-Frame'), ('unassigned', 'Nicht zugewiesen')], default='unassigned', max_length=20)),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='video/frames/')),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('generating', 'Wird generiert'), ('done', 'Fertig'), ('error', 'Fehler')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Generierter Frame',
                'verbose_name_plural': 'Generierte Frames',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Projektname')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Projekt',
                'verbose_name_plural': 'Video Projekte',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StillImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='video/stills/', verbose_name='Bild')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='still_image', to='video.videoproject')),
            ],
            options={
                'verbose_name': 'Stillbild',
                'verbose_name_plural': 'Stillbilder',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField(blank=True, verbose_name='Szene-Prompt')),
                ('duration', models.PositiveIntegerField(default=5, verbose_name='Dauer (Sek)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/scenes/')),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('generating', 'Wird generiert'), ('done', 'Fertig'), ('error', 'Fehler')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_end_in_scenes', to='video.generatedframe')),
                ('start_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_start_in_scenes', to='video.generatedframe')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='video.videoproject')),
            ],
            options={
                'verbose_name': 'Szene',
                'verbose_name_plural': 'Szenen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Produktname')),
                ('image', models.ImageField(upload_to='video/products/', verbose_name='Bild')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='video.videoproject')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.AddField(
            model_name='generatedframe',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='video.videoproject'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Charaktername')),
                ('image', models.ImageField(upload_to='video/characters/', verbose_name='Bild')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='video.videoproject')),
            ],
            options={
                'verbose_name': 'Charakter',
                'verbose_name_plural': 'Charaktere',
            },
        ),
    ]
