# Generated by Django 5.2.1 on 2026-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='model_choice',
            field=models.CharField(choices=[('ltx2-distilled', 'LTX-2 Distilled (schnell, I2V)'), ('ltx2-full', 'LTX-2 Full (langsam, FLF2V)'), ('cogvideox', 'CogVideoX 1.5 (I2V, alternative)'), ('wan-flf2v', 'Wan 2.2 FLF2V (Empfohlen)')], default='wan-flf2v', max_length=20),
        ),
        migrations.AddField(
            model_name='scene',
            name='with_audio',
            field=models.BooleanField(default=False, verbose_name='Ambient Audio'),
        ),
    ]
