# Generated by Django 5.2.1 on 2026-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_scene_model_choice_scene_with_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='aspect_ratio',
            field=models.CharField(choices=[('auto', 'Auto'), ('16:9', '16:9 (Querformat)'), ('9:16', '9:16 (Hochformat)'), ('1:1', '1:1 (Quadrat)')], default='auto', max_length=10, verbose_name='Bildformat'),
        ),
        migrations.AddField(
            model_name='scene',
            name='fps',
            field=models.PositiveIntegerField(choices=[(16, '16 fps'), (24, '24 fps'), (30, '30 fps')], default=24, verbose_name='FPS'),
        ),
        migrations.AddField(
            model_name='scene',
            name='guidance_scale',
            field=models.FloatField(default=5.0, verbose_name='Guidance Scale'),
        ),
        migrations.AddField(
            model_name='scene',
            name='negative_prompt',
            field=models.TextField(blank=True, default='', verbose_name='Negativer Prompt'),
        ),
        migrations.AddField(
            model_name='scene',
            name='num_steps',
            field=models.PositiveIntegerField(default=30, verbose_name='Inference Steps'),
        ),
        migrations.AddField(
            model_name='scene',
            name='seed',
            field=models.BigIntegerField(default=42, verbose_name='Seed'),
        ),
    ]
