# Generated by Django 5.2.1 on 2026-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_scene_aspect_ratio_scene_fps_scene_guidance_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='gpu_choice',
            field=models.CharField(choices=[('T4', 'T4 (16GB, $0.59/h) — kleinere Modelle'), ('L4', 'L4 (24GB, $0.80/h)'), ('A10', 'A10 (24GB, $1.10/h)'), ('L40S', 'L40S (44GB, $1.95/h) — CPU Offload'), ('A100-80', 'A100 80GB ($2.50/h)'), ('H100', 'H100 80GB ($3.95/h) — schnell')], default='L40S', max_length=10, verbose_name='GPU Server'),
        ),
    ]
