# Generated by Django 5.2.1 on 2026-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_scene_gpu_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='render_cost',
            field=models.FloatField(default=0, verbose_name='Render-Kosten ($)'),
        ),
        migrations.AddField(
            model_name='scene',
            name='render_duration_sec',
            field=models.FloatField(default=0, verbose_name='Render-Dauer (Sek)'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='gpu_choice',
            field=models.CharField(choices=[('T4', 'T4 16GB ($0.59/h)'), ('L4', 'L4 24GB ($0.80/h)'), ('A10', 'A10 24GB ($1.10/h)'), ('L40S', 'L40S 44GB ($1.95/h)'), ('A100-40', 'A100 40GB ($2.10/h)'), ('A100', 'A100 80GB ($2.50/h)'), ('RTX6000', 'RTX PRO 6000 48GB ($3.03/h)'), ('H100', 'H100 80GB ($3.95/h)'), ('H200', 'H200 141GB ($4.54/h)'), ('B200', 'B200 192GB ($6.25/h)')], default='L40S', max_length=10, verbose_name='GPU Server'),
        ),
    ]
