# Generated by Django 5.2.1 on 2026-04-04 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_scene_celery_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('laozhang', 'LaoZhang.ai (Sora 2, Veo 3.1)'), ('renderful', 'Renderful (Wan, Kling, Seedance)'), ('fal', 'Fal.ai (LTX-2, Wan, 600+ Modelle)'), ('siliconflow', 'SiliconFlow (Wan, Hunyuan)')], default='laozhang', max_length=20)),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video API Key',
                'verbose_name_plural': 'Video API Keys',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
