# Generated by Django 5.2.1 on 2026-04-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='video/audio/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_model',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Audio-Modell'),
        ),
        migrations.AddField(
            model_name='scene',
            name='voiceover_text',
            field=models.TextField(blank=True, default='', verbose_name='Gesprochener Text'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='model_choice',
            field=models.CharField(choices=[('veo-3.1-fast', 'Veo 3.1 Fast (Google, empfohlen)'), ('veo-3.1', 'Veo 3.1 (Google, hohe Qualität)'), ('sora-2', 'Sora 2 (OpenAI)'), ('sora-2-pro', 'Sora 2 Pro (OpenAI, beste Qualität)'), ('wan-2.1', 'Wan 2.1 (Alibaba, günstig)'), ('wan-2.6', 'Wan 2.6 (Alibaba, neuestes)'), ('kling-v2.6', 'Kling v2.6 (mit Audio)'), ('seedance-1.5-pro', 'Seedance 1.5 Pro (ByteDance)'), ('hailuo-2.3', 'Hailuo 2.3 (MiniMax)')], default='wan-flf2v', max_length=20),
        ),
    ]
