# Generated by Django 5.2.1 on 2026-04-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_voiceover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='gpu_choice',
            field=models.CharField(choices=[('auto', 'Automatisch (API)')], default='L40S', max_length=10, verbose_name='GPU Server'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='model_choice',
            field=models.CharField(choices=[('wan-2.2', 'Wan 2.2 (GPU)'), ('wan-2.1', 'Wan 2.1 (GPU)'), ('hunyuanvideo', 'HunyuanVideo 1.5 (GPU)'), ('veo-3.1-fast', 'Veo 3.1 Fast (API)'), ('veo-3.1', 'Veo 3.1 (API)'), ('veo-3.1-fast-fl', 'Veo 3.1 Fast + Startbild (API)'), ('veo-3.1-fl', 'Veo 3.1 + Startbild (API)'), ('sora-2', 'Sora 2 (API)'), ('sora-2-pro', 'Sora 2 Pro (API)'), ('minimax-m2.1', 'MiniMax M2.1 (API)'), ('minimax-m2.5', 'MiniMax M2.5 (API)'), ('minimax-m2.7', 'MiniMax M2.7 (API)'), ('seedance-1.5-pro', 'Seedance 1.5 Pro'), ('seedance-1.0-pro', 'Seedance 1.0 Pro'), ('seedance-1.0-pro-fast', 'Seedance 1.0 Fast'), ('seedance-1.0-lite', 'Seedance 1.0 Lite'), ('kling-v3.0-pro', 'Kling v3.0 Pro'), ('kling-v2.6', 'Kling v2.6'), ('kling-v1.6', 'Kling v1.6'), ('kling-v1.5', 'Kling v1.5'), ('kling-v1', 'Kling v1'), ('hailuo-2.3', 'Hailuo 2.3'), ('vidu-q1', 'Vidu Q1'), ('vidu-q2', 'Vidu Q2'), ('ltx-2-distilled', 'LTX-2 Distilled'), ('hunyuanvideo', 'HunyuanVideo 13B'), ('cogvideox', 'CogVideoX 5B')], default='wan-2.2', max_length=30),
        ),
        migrations.AlterField(
            model_name='videoapikey',
            name='provider',
            field=models.CharField(choices=[('laozhang', 'LaoZhang.ai (Sora 2, Veo 3.1)'), ('renderful', 'Renderful (Wan, Kling, Seedance)'), ('fal', 'Fal.ai (LTX-2, Wan, 600+ Modelle)'), ('siliconflow', 'SiliconFlow (Wan, Hunyuan)'), ('thunder', 'Thunder Compute A100 (Self-Hosted, ab \\$0.01/Video)')], default='laozhang', max_length=20),
        ),
    ]
