# Generated by Django 5.2.1 on 2026-04-07 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_scene_gpu_choice_alter_scene_model_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUServerState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('is_manually_started', models.BooleanField(default=False, verbose_name='Manuell gestartet')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Letzte Aktivität')),
                ('auto_shutdown_scheduled', models.BooleanField(default=False, verbose_name='Auto-Shutdown geplant')),
            ],
            options={
                'verbose_name': 'GPU Server Status',
                'verbose_name_plural': 'GPU Server Status',
            },
        ),
        migrations.AlterField(
            model_name='scene',
            name='model_choice',
            field=models.CharField(choices=[('wan-2.2', 'Wan 2.2'), ('wan-2.1', 'Wan 2.1'), ('hunyuanvideo', 'HunyuanVideo 1.5'), ('ltx-2-distilled', 'LTX-2 Distilled'), ('cogvideox', 'CogVideoX 5B')], default='wan-2.2', max_length=30),
        ),
        migrations.CreateModel(
            name='SceneVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='video/renders/', verbose_name='Video-Datei')),
                ('render_duration_sec', models.FloatField(default=0, verbose_name='Render-Dauer (Sek)')),
                ('render_cost', models.FloatField(default=0, verbose_name='Render-Kosten ($)')),
                ('model_used', models.CharField(max_length=30, verbose_name='Verwendetes Modell')),
                ('status', models.CharField(choices=[('rendering', 'Wird gerendert'), ('done', 'Fertig'), ('error', 'Fehler')], default='rendering', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False, verbose_name='Ausgewählt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendered_videos', to='video.scene')),
            ],
            options={
                'verbose_name': 'Gerendertes Video',
                'verbose_name_plural': 'Gerenderte Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
