# Generated by Django 5.2.1 on 2026-04-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_scene_video_and_gpu_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='render_progress',
            field=models.IntegerField(default=0, verbose_name='Render-Fortschritt (%)'),
        ),
        migrations.AlterField(
            model_name='videoapikey',
            name='provider',
            field=models.CharField(choices=[('renderful', 'Renderful (Wan, Kling, Seedance)')], default='renderful', max_length=20),
        ),
    ]
