# Generated by Django 5.2.1 on 2026-04-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_scene_model_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuserverstate',
            name='auto_shutdown_minutes',
            field=models.IntegerField(default=10, verbose_name='Auto-Shutdown Minuten'),
        ),
    ]
