# Generated by Django 5.2.1 on 2026-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_gpuserverstate_auto_shutdown_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='end_frame_prompt',
            field=models.TextField(blank=True, default='', verbose_name='End-Frame Prompt'),
        ),
        migrations.AddField(
            model_name='scene',
            name='frame_model',
            field=models.CharField(blank=True, choices=[('nano-banana', 'Nano Banana 2'), ('flux-pulid', 'FLUX + PuLID')], default='nano-banana', max_length=20, verbose_name='Frame-Modell'),
        ),
        migrations.AddField(
            model_name='scene',
            name='start_frame_prompt',
            field=models.TextField(blank=True, default='', verbose_name='Start-Frame Prompt'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='model_choice',
            field=models.CharField(choices=[('wan-2.2', 'Wan 2.2'), ('wan-2.1', 'Wan 2.1'), ('wan-flf2v', 'Wan FLF2V'), ('hunyuanvideo', 'HunyuanVideo 1.5'), ('hunyuan', 'HunyuanVideo'), ('ltx-video', 'LTX-Video 2B'), ('ltx-2-distilled', 'LTX-2 Distilled'), ('cogvideox', 'CogVideoX 5B'), ('hunyuanvideo-rp', 'HunyuanVideo 1.5 I2V (RunPod)')], default='wan-2.2', max_length=30),
        ),
    ]
