# Generated by Django 5.2.1 on 2026-04-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_scene_end_frame_prompt_scene_frame_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='voice_reference_audio',
            field=models.FileField(blank=True, null=True, upload_to='video/voice_refs/', verbose_name='Voice-Clone Referenz'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='audio_model',
            field=models.CharField(blank=True, default='piper-thorsten-medium', max_length=60, verbose_name='Audio-Modell'),
        ),
    ]
