# Generated by Django 5.2.1 on 2026-04-14 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_scene_voice_reference_audio_alter_scene_audio_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceClone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name der Stimme')),
                ('audio_file', models.FileField(upload_to='video/voice_clones/', verbose_name='Audio-Referenz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_clones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Clone',
                'verbose_name_plural': 'Voice Clones',
                'ordering': ['-created_at'],
            },
        ),
    ]
