# Generated by Django 5.2.1 on 2026-04-14 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_voiceclone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='voice_clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='video.voiceclone', verbose_name='Aktive Voice-Clone'),
        ),
    ]
