# Generated by Django 5.2.1 on 2026-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_scene_voice_clone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='flux_guidance',
            field=models.FloatField(default=3.5, verbose_name='FLUX Guidance (CFG)'),
        ),
        migrations.AddField(
            model_name='scene',
            name='flux_resolution',
            field=models.CharField(choices=[('1024', '1024×1024 (quadratisch, schnell)'), ('1080_h', '1920×1080 (FullHD horizontal)'), ('1080_v', '1080×1920 (FullHD vertikal/Shorts)'), ('2048', '2048×2048 (2K, langsam)')], default='1024', max_length=10, verbose_name='FLUX-Auflösung'),
        ),
        migrations.AddField(
            model_name='scene',
            name='flux_steps',
            field=models.PositiveIntegerField(default=24, verbose_name='FLUX Inference Steps'),
        ),
        migrations.AddField(
            model_name='scene',
            name='hunyuan_cfg',
            field=models.FloatField(default=6.0, verbose_name='Hunyuan CFG'),
        ),
        migrations.AddField(
            model_name='scene',
            name='hunyuan_flow_shift',
            field=models.FloatField(default=7.0, verbose_name='Hunyuan Flow Shift'),
        ),
        migrations.AddField(
            model_name='scene',
            name='hunyuan_resolution',
            field=models.CharField(choices=[('480p', '480p (832×480, schnell)'), ('720p', '720p (1280×720, hohe Qualität)')], default='480p', max_length=10, verbose_name='Hunyuan-Auflösung'),
        ),
        migrations.AddField(
            model_name='scene',
            name='hunyuan_steps',
            field=models.PositiveIntegerField(default=20, verbose_name='Hunyuan Inference Steps'),
        ),
        migrations.AddField(
            model_name='scene',
            name='pulid_cfg',
            field=models.FloatField(default=1.0, verbose_name='PuLID Gesichts-Gewicht'),
        ),
        migrations.AddField(
            model_name='scene',
            name='quality_preset',
            field=models.CharField(choices=[('draft', 'Draft (schnell)'), ('balanced', 'Balanced (empfohlen)'), ('ultra', 'Ultra (beste Qualität)'), ('custom', 'Custom')], default='balanced', max_length=20, verbose_name='Qualitäts-Preset'),
        ),
    ]
