# Generated by Django 5.2.1 on 2026-04-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_scene_flux_guidance_scene_flux_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='overlay_pos_h',
            field=models.CharField(choices=[('left', 'Links'), ('center', 'Zentriert'), ('right', 'Rechts')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='scene',
            name='overlay_pos_v',
            field=models.CharField(choices=[('top', 'Oben'), ('middle', 'Mitte'), ('bottom', 'Unten')], default='bottom', max_length=10),
        ),
        migrations.AddField(
            model_name='scene',
            name='overlay_style',
            field=models.CharField(choices=[('classic', 'Classic (weiß + schwarze Box)'), ('modern', 'Modern (große Outline, keine Box)'), ('subtitle', 'Subtitle (klein, unten)'), ('title', 'Title (groß, oben)')], default='classic', max_length=10),
        ),
        migrations.AddField(
            model_name='scene',
            name='text_overlay',
            field=models.TextField(blank=True, default='', verbose_name='Text-Overlay'),
        ),
    ]
