# Generated by Django 5.2.1 on 2026-04-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_scene_overlay_pos_h_scene_overlay_pos_v_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='frame_model',
            field=models.CharField(blank=True, choices=[('nano-banana', 'Nano Banana 2'), ('flux-pulid', 'FLUX + PuLID')], default='flux-pulid', max_length=20, verbose_name='Frame-Modell'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='overlay_pos_v',
            field=models.CharField(choices=[('top', 'Oben'), ('middle', 'Mitte'), ('bottom', 'Unten')], default='middle', max_length=10),
        ),
        migrations.AlterField(
            model_name='scene',
            name='overlay_style',
            field=models.CharField(choices=[('classic', 'Classic (weiß + schwarze Box)'), ('modern', 'Modern (große Outline, keine Box)'), ('subtitle', 'Subtitle (klein, unten)'), ('title', 'Title (groß, oben)')], default='modern', max_length=10),
        ),
    ]
