# Generated by Django 5.2.1 on 2026-04-14 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0020_alter_scene_frame_model_alter_scene_overlay_pos_v_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(upload_to='video/characters/', verbose_name='Hauptbild'),
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='video/characters/', verbose_name='Referenzbild')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='video.character')),
            ],
            options={
                'verbose_name': 'Charakter-Referenzbild',
                'verbose_name_plural': 'Charakter-Referenzbilder',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
