# Generated by Django 5.2.1 on 2026-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_alter_character_image_characterimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='model_choice',
            field=models.CharField(choices=[('wan-2.2', 'Wan 2.2'), ('wan-2.1', 'Wan 2.1'), ('wan-flf2v', 'Wan FLF2V'), ('hunyuanvideo', 'HunyuanVideo 1.5'), ('hunyuan', 'HunyuanVideo'), ('ltx-video', 'LTX-Video 2B'), ('ltx-2-distilled', 'LTX-2 Distilled'), ('cogvideox', 'CogVideoX 5B'), ('hunyuanvideo-rp', 'HunyuanVideo 1.5 I2V (RunPod)')], default='hunyuanvideo-rp', max_length=30),
        ),
    ]
