# Generated by Django 5.2.1 on 2026-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0023_add_music_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='frame_style',
            field=models.CharField(choices=[('photorealistic', 'Fotorealistisch'), ('cinematic', 'Cinematic / Film'), ('editorial', 'Editorial / Magazin'), ('documentary', 'Dokumentarisch'), ('warm-portrait', 'Warmes Portrait'), ('anime', 'Anime / Manga'), ('illustration', 'Illustration'), ('watercolor', 'Aquarell'), ('3d-render', '3D Render'), ('none', 'Kein Stil (nur Prompt)')], default='photorealistic', max_length=20, verbose_name='Frame-Stil'),
        ),
    ]
