# Generated by Django 5.2.1 on 2026-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_add_frame_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='video/project_music/', verbose_name='Projekt-Musikdatei'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='music_genre',
            field=models.CharField(blank=True, choices=[('', 'Kein Genre'), ('cinematic', 'Cinematic / Filmmusik'), ('lofi', 'Lo-Fi / Chill'), ('corporate', 'Corporate / Business'), ('epic', 'Epic / Trailer'), ('ambient', 'Ambient / Atmosphärisch'), ('happy', 'Happy / Fröhlich'), ('sad', 'Sad / Melancholisch'), ('dramatic', 'Dramatisch / Spannend'), ('romantic', 'Romantisch'), ('electronic', 'Electronic / Synth'), ('acoustic', 'Akustisch / Gitarre'), ('piano', 'Piano / Klavier')], default='', max_length=20, verbose_name='Musik-Genre'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='music_prompt',
            field=models.TextField(blank=True, default='', verbose_name='Musik-Prompt'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='music_volume',
            field=models.FloatField(default=0.3, verbose_name='Musik-Lautstärke (0-1)'),
        ),
    ]
