# Generated by Django 5.2.1 on 2026-03-23 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0009_add_subtitle_words_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', models.TextField(verbose_name='Keywords (eine pro Zeile)')),
                ('template', models.CharField(choices=[('job_intro', 'Berufsvorstellung'), ('product', 'Produktvideo'), ('tutorial', 'Tutorial/HowTo'), ('facts', 'Fakten-Video'), ('comparison', 'Vergleich A vs B'), ('top_list', 'Top 5/10 Liste'), ('motivation', 'Motivation'), ('news', 'News/Update'), ('ranking', 'Ranking'), ('tips', 'Tipps & Tricks'), ('myth_busting', 'Mythen aufdecken'), ('secrets', 'Geheimtipps'), ('mistakes', 'Häufige Fehler'), ('day_in_life', 'Ein Tag als...')], default='job_intro', max_length=50, verbose_name='Template')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('youtube_shorts', 'YouTube Shorts'), ('instagram_reels', 'Instagram Reels'), ('instagram_post', 'Instagram Post (1:1)')], default='tiktok', max_length=50, verbose_name='Plattform')),
                ('voice', models.CharField(choices=[('echo', 'Echo (männlich, natürlich)'), ('onyx', 'Onyx (männlich, tief)'), ('nova', 'Nova (weiblich, warm)'), ('alloy', 'Alloy (neutral)'), ('shimmer', 'Shimmer (weiblich, sanft)'), ('fable', 'Fable (britisch)')], default='echo', max_length=50, verbose_name='Stimme')),
                ('watermark', models.BooleanField(default=False, verbose_name='Wasserzeichen')),
                ('total_count', models.IntegerField(default=0, verbose_name='Gesamt')),
                ('completed_count', models.IntegerField(default=0, verbose_name='Fertig')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Fehlgeschlagen')),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('processing', 'In Bearbeitung'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20, verbose_name='Status')),
                ('cost_total', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Gesamt Kosten ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vidgen_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Job',
                'verbose_name_plural': 'Batch Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titel/Thema')),
                ('template', models.CharField(choices=[('job_intro', 'Berufsvorstellung'), ('product', 'Produktvideo'), ('tutorial', 'Tutorial/HowTo'), ('facts', 'Fakten-Video'), ('comparison', 'Vergleich A vs B'), ('top_list', 'Top 5/10 Liste'), ('motivation', 'Motivation'), ('news', 'News/Update'), ('ranking', 'Ranking'), ('tips', 'Tipps & Tricks'), ('myth_busting', 'Mythen aufdecken'), ('secrets', 'Geheimtipps'), ('mistakes', 'Häufige Fehler'), ('day_in_life', 'Ein Tag als...')], default='job_intro', max_length=50, verbose_name='Template')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('youtube_shorts', 'YouTube Shorts'), ('instagram_reels', 'Instagram Reels'), ('instagram_post', 'Instagram Post (1:1)')], default='tiktok', max_length=50, verbose_name='Plattform')),
                ('voice', models.CharField(choices=[('echo', 'Echo (männlich, natürlich)'), ('onyx', 'Onyx (männlich, tief)'), ('nova', 'Nova (weiblich, warm)'), ('alloy', 'Alloy (neutral)'), ('shimmer', 'Shimmer (weiblich, sanft)'), ('fable', 'Fable (britisch)')], default='echo', max_length=50, verbose_name='Stimme')),
                ('script', models.TextField(blank=True, verbose_name='Generiertes Skript')),
                ('overlay_file', models.FileField(blank=True, null=True, upload_to='vidgen/overlays/%Y/%m/', verbose_name='Overlay (Bild/Video)')),
                ('overlay_start', models.IntegerField(default=5, verbose_name='Overlay Start (Sekunden)')),
                ('watermark', models.BooleanField(default=False, verbose_name='Wasserzeichen hinzufügen')),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('script', 'Skript wird generiert'), ('audio', 'Audio wird generiert'), ('clips', 'Clips werden gesucht'), ('rendering', 'Video wird gerendert'), ('compressing', 'Video wird komprimiert'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20, verbose_name='Status')),
                ('progress', models.IntegerField(default=0, verbose_name='Fortschritt (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('cost_tts', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TTS Kosten ($)')),
                ('cost_whisper', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Whisper Kosten ($)')),
                ('cost_script', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Skript Kosten ($)')),
                ('cost_total', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Gesamt Kosten ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='vidgen.batchjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vidgen_projects', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vidgen_project', to='videos.video', verbose_name='Generiertes Video')),
            ],
            options={
                'verbose_name': 'Video Projekt',
                'verbose_name_plural': 'Video Projekte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PexelsClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pexels_id', models.CharField(max_length=50, verbose_name='Pexels Video ID')),
                ('search_query', models.CharField(max_length=200, verbose_name='Suchbegriff')),
                ('video_file', models.FileField(upload_to='vidgen/clips/%Y/%m/', verbose_name='Video-Datei')),
                ('duration', models.FloatField(default=0, verbose_name='Dauer (Sekunden)')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='vidgen.videoproject')),
            ],
            options={
                'verbose_name': 'Pexels Clip',
                'verbose_name_plural': 'Pexels Clips',
                'ordering': ['project', 'order'],
            },
        ),
    ]
