# Generated by Django 5.2.1 on 2026-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='title_position',
            field=models.CharField(choices=[('top', 'Oben'), ('center', 'Mitte'), ('bottom', 'Unten')], default='top', max_length=20, verbose_name='Titel-Position'),
        ),
    ]
