# Generated by Django 5.2.1 on 2026-03-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0002_add_title_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='custom_script',
            field=models.TextField(blank=True, help_text='Optional: Eigenen Sprechtext eingeben (überspringt KI-Generierung)', verbose_name='Eigener Text'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='template',
            field=models.CharField(choices=[('job_intro', '👔 Berufsvorstellung'), ('product', '🛍️ Produktvideo'), ('tutorial', '📚 Tutorial/HowTo'), ('facts', '💡 Fakten-Video'), ('comparison', '⚖️ Vergleich A vs B'), ('top_list', '🏆 Top 5/10 Liste'), ('motivation', '🔥 Motivation'), ('tips', '✨ Tipps & Tricks'), ('hook_story', '🎣 Hook + Story (Viral-Format)'), ('pov', '👀 POV-Video'), ('storytime', '📖 Storytime'), ('hot_take', '🌶️ Hot Take / Meinung'), ('before_after', '↔️ Vorher/Nachher'), ('myth_busting', '🔍 Mythen aufdecken'), ('secrets', '🤫 Geheimtipps'), ('mistakes', '❌ Häufige Fehler'), ('day_in_life', '📅 Ein Tag als...'), ('unpopular_opinion', '💬 Unpopular Opinion'), ('things_nobody_tells', '🤐 Dinge die keiner sagt'), ('this_or_that', '🤔 Dies oder Das'), ('custom', '✍️ Eigener Text')], default='job_intro', max_length=50, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='template',
            field=models.CharField(choices=[('job_intro', '👔 Berufsvorstellung'), ('product', '🛍️ Produktvideo'), ('tutorial', '📚 Tutorial/HowTo'), ('facts', '💡 Fakten-Video'), ('comparison', '⚖️ Vergleich A vs B'), ('top_list', '🏆 Top 5/10 Liste'), ('motivation', '🔥 Motivation'), ('tips', '✨ Tipps & Tricks'), ('hook_story', '🎣 Hook + Story (Viral-Format)'), ('pov', '👀 POV-Video'), ('storytime', '📖 Storytime'), ('hot_take', '🌶️ Hot Take / Meinung'), ('before_after', '↔️ Vorher/Nachher'), ('myth_busting', '🔍 Mythen aufdecken'), ('secrets', '🤫 Geheimtipps'), ('mistakes', '❌ Häufige Fehler'), ('day_in_life', '📅 Ein Tag als...'), ('unpopular_opinion', '💬 Unpopular Opinion'), ('things_nobody_tells', '🤐 Dinge die keiner sagt'), ('this_or_that', '🤔 Dies oder Das'), ('custom', '✍️ Eigener Text')], default='job_intro', max_length=50, verbose_name='Template'),
        ),
    ]
