# Generated by Django 5.2.1 on 2026-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0003_add_custom_script_and_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='target_duration',
            field=models.IntegerField(default=45, help_text='Ungefähre Zieldauer des Videos', verbose_name='Video-Dauer (Sekunden)'),
        ),
    ]
