# Generated by Django 5.2.1 on 2026-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0004_add_target_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='overlay_position',
            field=models.CharField(choices=[('center', 'Mitte'), ('top', 'Oben'), ('bottom', 'Unten'), ('left', 'Links'), ('right', 'Rechts'), ('top-left', 'Oben Links'), ('top-right', 'Oben Rechts'), ('bottom-left', 'Unten Links'), ('bottom-right', 'Unten Rechts')], default='center', max_length=20, verbose_name='Overlay Position'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='overlay_width',
            field=models.IntegerField(default=60, help_text='Prozent der Videobreite (10-100)', verbose_name='Overlay Breite (%)'),
        ),
    ]
