# Generated by Django 5.2.1 on 2026-03-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0005_add_overlay_position_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='overlay_duration',
            field=models.IntegerField(default=0, help_text='0 = bis zum Ende des Videos', verbose_name='Overlay Dauer (Sekunden)'),
        ),
    ]
