# Generated by Django 5.2.1 on 2026-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0006_add_overlay_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='emoji_animations',
            field=models.BooleanField(default=False, help_text='Emojis bei bestimmten Woertern einblenden', verbose_name='Emoji-Animationen'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='intro_style',
            field=models.CharField(choices=[('none', 'Kein Intro'), ('fade', 'Fade In'), ('zoom', 'Zoom In'), ('slide_up', 'Slide von unten'), ('glitch', 'Glitch Effekt'), ('typewriter', 'Typewriter')], default='none', max_length=30, verbose_name='Intro-Style'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='lower_third_start',
            field=models.IntegerField(default=0, help_text='Wann einblenden (0 = aus)', verbose_name='Lower Third Start (Sek)'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='lower_third_text',
            field=models.CharField(blank=True, help_text='z.B. Name | Titel', max_length=100, verbose_name='Lower Third Text'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='progress_bar_color',
            field=models.CharField(default='#FFD700', max_length=20, verbose_name='Progress Bar Farbe'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='show_progress_bar',
            field=models.BooleanField(default=False, verbose_name='Progress Bar anzeigen'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='transition_style',
            field=models.CharField(choices=[('cut', 'Harter Schnitt'), ('fade', 'Ueberblenden'), ('zoom', 'Zoom'), ('slide_left', 'Slide Links'), ('slide_right', 'Slide Rechts')], default='cut', max_length=30, verbose_name='Clip-Uebergaenge'),
        ),
    ]
