# Generated by Django 5.2.1 on 2026-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0007_add_video_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='audio_ducking',
            field=models.BooleanField(default=True, help_text='Musik leiser wenn gesprochen wird', verbose_name='Audio-Ducking'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='background_music',
            field=models.CharField(choices=[('none', 'Keine Musik'), ('upbeat', 'Upbeat/Froelich'), ('corporate', 'Corporate/Business'), ('emotional', 'Emotional/Dramatic'), ('chill', 'Chill/Relaxed'), ('news', 'News/Serious'), ('tech', 'Tech/Modern'), ('acoustic', 'Acoustic/Warm')], default='none', max_length=50, verbose_name='Hintergrundmusik'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='color_grading',
            field=models.CharField(choices=[('none', 'Original'), ('warm', 'Warm'), ('cold', 'Kalt'), ('vintage', 'Vintage'), ('neon', 'Neon'), ('bw', 'Schwarz-Weiss'), ('cinematic', 'Cinematic')], default='none', max_length=20, verbose_name='Color Grading'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='fact_box_text',
            field=models.CharField(blank=True, help_text='z.B. 85% der Deutschen...', max_length=200, verbose_name='Fakten-Box Text'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='fact_box_time',
            field=models.IntegerField(default=0, help_text='0 = keine Fakten-Box', verbose_name='Fakten-Box Einblenden (Sek)'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='is_discussion',
            field=models.BooleanField(default=False, help_text='Zwei Personen debattieren', verbose_name='Diskussions-Format'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='ken_burns_effect',
            field=models.BooleanField(default=False, help_text='Langsames Zoom/Pan auf Clips', verbose_name='Ken Burns Effekt'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='music_volume',
            field=models.IntegerField(default=20, help_text='0-100, empfohlen: 15-25', verbose_name='Musik-Lautstaerke (%)'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='quote_author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zitat-Autor'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='quote_text',
            field=models.TextField(blank=True, help_text='Wird gross animiert eingeblendet', verbose_name='Zitat-Text'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='quote_time',
            field=models.IntegerField(default=0, help_text='0 = kein Zitat', verbose_name='Zitat Einblenden (Sek)'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='sound_effects',
            field=models.BooleanField(default=False, help_text='Whoosh bei Uebergaengen, Pling bei Punkten', verbose_name='Sound-Effekte'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='speaker1_name',
            field=models.CharField(blank=True, default='Pro', max_length=50, verbose_name='Sprecher 1 Name'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='speaker1_voice',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sprecher 1 Stimme'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='speaker2_name',
            field=models.CharField(blank=True, default='Contra', max_length=50, verbose_name='Sprecher 2 Name'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='speaker2_voice',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sprecher 2 Stimme'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='template',
            field=models.CharField(choices=[('job_intro', '👔 Berufsvorstellung'), ('product', '🛍️ Produktvideo'), ('tutorial', '📚 Tutorial/HowTo'), ('facts', '💡 Fakten-Video'), ('comparison', '⚖️ Vergleich A vs B'), ('top_list', '🏆 Top 5/10 Liste'), ('motivation', '🔥 Motivation'), ('tips', '✨ Tipps & Tricks'), ('hook_story', '🎣 Hook + Story (Viral-Format)'), ('pov', '👀 POV-Video'), ('storytime', '📖 Storytime'), ('hot_take', '🌶️ Hot Take / Meinung'), ('before_after', '↔️ Vorher/Nachher'), ('myth_busting', '🔍 Mythen aufdecken'), ('secrets', '🤫 Geheimtipps'), ('news_style', '📺 News-Format'), ('story_vertical', '📱 Story (9:16)'), ('discussion', '🎭 Diskussion (2 Sprecher)'), ('mistakes', '❌ Häufige Fehler'), ('day_in_life', '📅 Ein Tag als...'), ('unpopular_opinion', '💬 Unpopular Opinion'), ('things_nobody_tells', '🤐 Dinge die keiner sagt'), ('this_or_that', '🤔 Dies oder Das'), ('custom', '✍️ Eigener Text')], default='job_intro', max_length=50, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='template',
            field=models.CharField(choices=[('job_intro', '👔 Berufsvorstellung'), ('product', '🛍️ Produktvideo'), ('tutorial', '📚 Tutorial/HowTo'), ('facts', '💡 Fakten-Video'), ('comparison', '⚖️ Vergleich A vs B'), ('top_list', '🏆 Top 5/10 Liste'), ('motivation', '🔥 Motivation'), ('tips', '✨ Tipps & Tricks'), ('hook_story', '🎣 Hook + Story (Viral-Format)'), ('pov', '👀 POV-Video'), ('storytime', '📖 Storytime'), ('hot_take', '🌶️ Hot Take / Meinung'), ('before_after', '↔️ Vorher/Nachher'), ('myth_busting', '🔍 Mythen aufdecken'), ('secrets', '🤫 Geheimtipps'), ('news_style', '📺 News-Format'), ('story_vertical', '📱 Story (9:16)'), ('discussion', '🎭 Diskussion (2 Sprecher)'), ('mistakes', '❌ Häufige Fehler'), ('day_in_life', '📅 Ein Tag als...'), ('unpopular_opinion', '💬 Unpopular Opinion'), ('things_nobody_tells', '🤐 Dinge die keiner sagt'), ('this_or_that', '🤔 Dies oder Das'), ('custom', '✍️ Eigener Text')], default='job_intro', max_length=50, verbose_name='Template'),
        ),
    ]
