# Generated by Django 5.2.1 on 2026-03-24 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0008_add_extended_effects'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(verbose_name='Prompt/Beschreibung')),
                ('mood', models.CharField(blank=True, max_length=30, verbose_name='Stimmung')),
                ('audio_file', models.FileField(upload_to='music_library/', verbose_name='Audio-Datei')),
                ('duration', models.IntegerField(default=30, verbose_name='Dauer (Sek)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=0, verbose_name='Nutzungen')),
                ('tags', models.CharField(blank=True, help_text='Komma-getrennte Tags', max_length=200)),
            ],
            options={
                'verbose_name': 'Musik-Track',
                'verbose_name_plural': 'Musik-Tracks',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
    ]
