# Generated by Django 5.2.1 on 2026-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0009_add_music_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='custom_music_prompt',
            field=models.TextField(blank=True, help_text='z.B. Epische Orchestermusik mit Trommeln, dramatisch', verbose_name='Musik-Beschreibung'),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='music_duration',
            field=models.IntegerField(default=0, help_text='0 = automatisch (Video-Laenge)', verbose_name='Musik-Laenge (Sek)'),
        ),
    ]
