# Generated by Django 5.2.1 on 2026-03-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0010_add_custom_music_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='custom_music_prompt',
        ),
        migrations.RemoveField(
            model_name='musictrack',
            name='music_duration',
        ),
    ]
