# Generated by Django 5.2.1 on 2026-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0012_add_custom_music_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='resolution',
            field=models.CharField(choices=[('1080p', '1080p (Full HD)'), ('720p', '720p (HD - schneller)')], default='1080p', max_length=10, verbose_name='Aufloesung'),
        ),
    ]
