# Generated by Django 5.2.1 on 2026-03-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0013_add_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='render_backend',
            field=models.CharField(choices=[('local', 'Lokal (Hetzner Server)'), ('modal', 'Modal Cloud (GPU - schneller)')], default='local', help_text='Modal ist schneller aber kostet ~2 Cent/Video', max_length=20, verbose_name='Render Backend'),
        ),
    ]
