# Generated by Django 5.2.1 on 2026-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0015_add_quote_fact_duration_and_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Audio-Datei'),
        ),
    ]
