# Generated by Django 5.2.1 on 2026-03-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0016_videoproject_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='selected_music_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='vidgen.musictrack', verbose_name='Ausgewählter Musik-Track'),
        ),
    ]
