# Generated by Django 5.2.1 on 2026-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0017_add_selected_music_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Status-Nachricht'),
        ),
    ]
