# Generated by Django 5.2.1 on 2026-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidgen', '0018_add_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Celery Task ID'),
        ),
    ]
