# Generated by Django 5.2.1 on 2025-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_sucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderposition',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Einheit (Stk, m², kg, etc.)', max_length=50),
        ),
    ]
