# Generated by Django 5.2.1 on 2025-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_sucher', '0003_fix_tenderposition_unit_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsummary',
            name='ai_model',
            field=models.CharField(choices=[('openai_gpt4o', 'OpenAI GPT-4o (128k Token, $2.50/$10.00 pro 1M Token)'), ('openai_gpt4o_mini', 'OpenAI GPT-4o Mini (128k Token, $0.15/$0.60 pro 1M Token)'), ('openai_gpt4_turbo', 'OpenAI GPT-4 Turbo (128k Token, $10.00/$30.00 pro 1M Token)'), ('openai_gpt4', 'OpenAI GPT-4 (8k Token, $30.00/$60.00 pro 1M Token)'), ('openai_gpt35_turbo', 'OpenAI GPT-3.5 Turbo (16k Token, $0.50/$1.50 pro 1M Token)'), ('google_gemini_pro', 'Google Gemini Pro (1M Token, $0.50/$1.50 pro 1M Token)'), ('google_gemini_flash', 'Google Gemini Flash (1M Token, $0.075/$0.30 pro 1M Token)'), ('anthropic_claude_opus', 'Anthropic Claude-3 Opus (200k Token, $15.00/$75.00 pro 1M Token)'), ('anthropic_claude_sonnet', 'Anthropic Claude-3.5 Sonnet (200k Token, $3.00/$15.00 pro 1M Token)'), ('anthropic_claude_haiku', 'Anthropic Claude-3 Haiku (200k Token, $0.25/$1.25 pro 1M Token)')], help_text='Verwendetes KI-Modell', max_length=30),
        ),
    ]
